export const authCopy = {
  en: {
    eyebrow: "A CLEARER PICTURE STARTS HERE",
    lineOne: "One question.",
    lineTwo: "A clearer",
    lineThree: "beginning.",
    story:
      "A place for your health questions, the documents behind them, and the conversations that help you understand.",
    sample: "ILLUSTRATIVE CONVERSATION",
    sampleQuestion: "Where should I start with my lab report?",
    sampleAnswer:
      "Start with the part you want to understand. You can add your report to the conversation for context.",
    note: "Your questions. Your pace.",
    noteDetail: "Make room for a clearer conversation.",
    smallPrint:
      "Information to help you understand. Medical decisions belong with your doctor.",
    loginEyebrow: "GOOD TO SEE YOU AGAIN",
    registerEyebrow: "MAKE YOURSELF AT HOME",
    loginTitle: "Welcome back.",
    registerTitle: "Your next chapter.",
    loginSubtitle: "Sign in and pick up where you left off.",
    registerSubtitle: "Create an account to start your conversation.",
    showPassword: "Show password",
    hidePassword: "Hide password",
    emailDivider: "or sign in with email",
    passwordHelp: "At least 8 characters.",
    privacy: "Privacy",
    terms: "Terms",
    contact: "Need help?",
    home: "Back to home",
    registrationFailed: "We couldn't create your account. Please try again.",
    loginFailed: "We couldn't sign you in. Check your details and try again.",
    haveAccount: "Already have an account?",
    noAccount: "New here?",
    namePlaceholder: "Your full name",
    termsIntro: "I agree to the",
    and: "and",
  },
  az: {
    eyebrow: "DAHA AYDIN BİR BAŞLANĞIC",
    lineOne: "Bir sual.",
    lineTwo: "Daha aydın",
    lineThree: "bir başlanğıc.",
    story:
      "Sağlamlıq suallarınız, onlarla bağlı sənədlər və məlumatları anlamağa kömək edən söhbətlər üçün bir yer.",
    sample: "SÖHBƏT NÜMUNƏSİ",
    sampleQuestion: "Analiz nəticələrimi anlamağa haradan başlayım?",
    sampleAnswer:
      "Anlamaq istədiyiniz hissədən başlayın. Daha çox məlumat üçün analiz sənədini söhbətə əlavə edə bilərsiniz.",
    note: "Sizin suallarınız. Sizin tempiniz.",
    noteDetail: "Daha aydın bir söhbətə yer açın.",
    smallPrint:
      "Məlumatları anlamağa kömək edir. Tibbi qərarları həkiminizlə müzakirə edin.",
    loginEyebrow: "SİZİ YENİDƏN GÖRMƏK XOŞDUR",
    registerEyebrow: "XOŞ GƏLMİSİNİZ",
    loginTitle: "Yenidən salam.",
    registerTitle: "Yeni bir başlanğıc.",
    loginSubtitle: "Hesabınıza daxil olun və qaldığınız yerdən davam edin.",
    registerSubtitle: "Hesab yaradın və söhbətə başlayın.",
    showPassword: "Şifrəni göstər",
    hidePassword: "Şifrəni gizlət",
    emailDivider: "və ya e-poçt ilə daxil olun",
    passwordHelp: "Ən azı 8 simvol.",
    privacy: "Məxfilik",
    terms: "İstifadə şərtləri",
    contact: "Kömək lazımdır?",
    home: "Ana səhifəyə qayıt",
    registrationFailed: "Hesab yaradıla bilmədi. Yenidən cəhd edin.",
    loginFailed:
      "Daxil olmaq mümkün olmadı. Məlumatlarınızı yoxlayın və yenidən cəhd edin.",
    haveAccount: "Artıq hesabınız var?",
    noAccount: "Burada yenisiniz?",
    namePlaceholder: "Adınız və soyadınız",
    termsIntro: "Qəbul edirəm:",
    and: "və",
  },
};
