export const authCopy = {
  en: {
    eyebrow: "A CLEARER PICTURE STARTS HERE",
    lineOne: "One question.",
    lineTwo: "A clearer",
    lineThree: "beginning.",
    story:
      "A place for your health questions, the documents behind them, and the conversations that help you understand.",
    sample: "ILLUSTRATIVE CONVERSATION",
    sampleQuestion: "Where should I start with my lab report?",
    sampleAnswer:
      "Start with the part you want to understand. You can add your report to the conversation for context.",
    note: "Your questions. Your pace.",
    noteDetail: "Make room for a clearer conversation.",
    smallPrint:
      "Information to help you understand. Medical decisions belong with your doctor.",
    loginEyebrow: "GOOD TO SEE YOU AGAIN",
    registerEyebrow: "MAKE YOURSELF AT HOME",
    loginTitle: "Welcome back.",
    registerTitle: "Your next chapter.",
    loginSubtitle: "Sign in and pick up where you left off.",
    registerSubtitle: "Create an account to start your conversation.",
    showPassword: "Show password",
    hidePassword: "Hide password",
    emailDivider: "or sign in with email",
    passwordHelp: "At least 8 characters.",
    privacy: "Privacy",
    terms: "Terms",
    contact: "Need help?",
    home: "Back to home",
    registrationFailed: "We couldn't create your account. Please try again.",
    loginFailed: "We couldn't sign you in. Check your details and try again.",
    haveAccount: "Already have an account?",
    noAccount: "New here?",
    namePlaceholder: "Your full name",
    termsIntro: "I agree to the",
    and: "and",
  },
  az: {
    eyebrow: "AZDOC İLƏ SÖHBƏT",
    lineOne: "Sağlamlıqla",
    lineTwo: "bağlı sualınız",
    lineThree: "var?",
    story:
      "Əlamətlər, analiz nəticələri və dərmanlar haqqında soruşun. Söhbətə tibbi sənəd də əlavə edə bilərsiniz.",
    sample: "SÖHBƏT NÜMUNƏSİ",
    sampleQuestion: "Analiz cavabımı göndərə bilərəm?",
    sampleAnswer:
      "Bəli. PDF faylını və ya sənədin şəklini söhbətə əlavə edə bilərsiniz.",
    note: "Ailəniz üçün ayrıca qeydlər.",
    noteDetail: "Allergiyaları, dərmanları və ölçüləri hər ailə üzvü üçün saxlayın.",
    smallPrint:
      "Cavabları süni intellekt hazırlayır. azdoc həkimi əvəz etmir.",
    loginEyebrow: "HESABINIZA GİRİŞ",
    registerEyebrow: "QEYDİYYAT",
    loginTitle: "Hesabınıza daxil olun.",
    registerTitle: "Hesab yaradın.",
    loginSubtitle: "Söhbətlərinizə və ailənizin sağlamlıq qeydlərinə keçin.",
    registerSubtitle: "Ailənizin sağlamlıq məlumatlarını hesabınızda saxlayın.",
    showPassword: "Şifrəni göstər",
    hidePassword: "Şifrəni gizlət",
    emailDivider: "və ya e-poçt ilə daxil olun",
    passwordHelp: "Ən azı 8 simvol.",
    privacy: "Məxfilik",
    terms: "İstifadə şərtləri",
    contact: "Kömək lazımdır?",
    home: "Ana səhifəyə qayıt",
    registrationFailed: "Hesab yaradıla bilmədi. Yenidən cəhd edin.",
    loginFailed:
      "Daxil olmaq mümkün olmadı. Məlumatlarınızı yoxlayın və yenidən cəhd edin.",
    haveAccount: "Artıq hesabınız var?",
    noAccount: "Hesabınız yoxdur?",
    namePlaceholder: "Adınız və soyadınız",
    termsIntro: "Qəbul edirəm:",
    and: "və",
  },
};
