export const authCopy = {
  ru: {
    eyebrow: "ЧАТ С AZDOC",
    lineOne: "Есть вопрос",
    lineTwo: "о вашем",
    lineThree: "здоровье?",
    story:
      "Спросите о симптомах, анализах и лекарствах. К чату можно прикрепить медицинский документ.",
    sample: "ПРИМЕР ПЕРЕПИСКИ",
    sampleQuestion: "Можно отправить результаты анализов?",
    sampleAnswer: "Да. Прикрепите PDF или фотографию документа к чату.",
    note: "Отдельные записи для членов семьи.",
    noteDetail:
      "Сохраняйте аллергии, лекарства и измерения для каждого человека.",
    smallPrint:
      "Ответы готовит искусственный интеллект. azdoc не заменяет врача.",
    loginEyebrow: "ВХОД В АККАУНТ",
    registerEyebrow: "РЕГИСТРАЦИЯ",
    loginTitle: "Войдите в аккаунт.",
    registerTitle: "Создайте аккаунт.",
    loginSubtitle: "Откройте свои чаты и медицинские записи семьи.",
    registerSubtitle: "Сохраняйте сведения о здоровье семьи в своем аккаунте.",
    showPassword: "Показать пароль",
    hidePassword: "Скрыть пароль",
    emailDivider: "или войдите по электронной почте",
    passwordHelp: "Не менее 8 символов.",
    privacy: "Конфиденциальность",
    terms: "Условия использования",
    contact: "Нужна помощь?",
    home: "На главную",
    registrationFailed: "Не удалось создать аккаунт. Попробуйте снова.",
    loginFailed: "Не удалось войти. Проверьте данные и попробуйте снова.",
    haveAccount: "Уже есть аккаунт?",
    noAccount: "Нет аккаунта?",
    namePlaceholder: "Ваши имя и фамилия",
    termsIntro: "Я принимаю",
    and: "и",
  },
  en: {
    eyebrow: "A CLEARER PICTURE STARTS HERE",
    lineOne: "One question.",
    lineTwo: "A clearer",
    lineThree: "beginning.",
    story:
      "A place for your health questions, the documents behind them, and the conversations that help you understand.",
    sample: "ILLUSTRATIVE CONVERSATION",
    sampleQuestion: "Where should I start with my lab report?",
    sampleAnswer:
      "Start with the part you want to understand. You can add your report to the conversation for context.",
    note: "Your questions. Your pace.",
    noteDetail: "Make room for a clearer conversation.",
    smallPrint:
      "Information to help you understand. Medical decisions belong with your doctor.",
    loginEyebrow: "GOOD TO SEE YOU AGAIN",
    registerEyebrow: "MAKE YOURSELF AT HOME",
    loginTitle: "Welcome back.",
    registerTitle: "Your next chapter.",
    loginSubtitle: "Sign in and pick up where you left off.",
    registerSubtitle: "Create an account to start your conversation.",
    showPassword: "Show password",
    hidePassword: "Hide password",
    emailDivider: "or sign in with email",
    passwordHelp: "At least 8 characters.",
    privacy: "Privacy",
    terms: "Terms",
    contact: "Need help?",
    home: "Back to home",
    registrationFailed: "We couldn't create your account. Please try again.",
    loginFailed: "We couldn't sign you in. Check your details and try again.",
    haveAccount: "Already have an account?",
    noAccount: "New here?",
    namePlaceholder: "Your full name",
    termsIntro: "I agree to the",
    and: "and",
  },
  az: {
    eyebrow: "AZDOC İLƏ SÖHBƏT",
    lineOne: "Sağlamlıqla",
    lineTwo: "bağlı sualınız",
    lineThree: "var?",
    story:
      "Əlamətlər, analiz nəticələri və dərmanlar haqqında soruşun. Söhbətə tibbi sənəd də əlavə edə bilərsiniz.",
    sample: "SÖHBƏT NÜMUNƏSİ",
    sampleQuestion: "Analiz cavabımı göndərə bilərəm?",
    sampleAnswer:
      "Bəli. PDF faylını və ya sənədin şəklini söhbətə əlavə edə bilərsiniz.",
    note: "Ailəniz üçün ayrıca qeydlər.",
    noteDetail:
      "Allergiyaları, dərmanları və ölçüləri hər ailə üzvü üçün saxlayın.",
    smallPrint: "Cavabları süni intellekt hazırlayır. azdoc həkimi əvəz etmir.",
    loginEyebrow: "HESABINIZA GİRİŞ",
    registerEyebrow: "QEYDİYYAT",
    loginTitle: "Hesabınıza daxil olun.",
    registerTitle: "Hesab yaradın.",
    loginSubtitle: "Söhbətlərinizə və ailənizin sağlamlıq qeydlərinə keçin.",
    registerSubtitle: "Ailənizin sağlamlıq məlumatlarını hesabınızda saxlayın.",
    showPassword: "Şifrəni göstər",
    hidePassword: "Şifrəni gizlət",
    emailDivider: "və ya e-poçt ilə daxil olun",
    passwordHelp: "Ən azı 8 simvol.",
    privacy: "Məxfilik",
    terms: "İstifadə şərtləri",
    contact: "Kömək lazımdır?",
    home: "Ana səhifəyə qayıt",
    registrationFailed: "Hesab yaradıla bilmədi. Yenidən cəhd edin.",
    loginFailed:
      "Daxil olmaq mümkün olmadı. Məlumatlarınızı yoxlayın və yenidən cəhd edin.",
    haveAccount: "Artıq hesabınız var?",
    noAccount: "Hesabınız yoxdur?",
    namePlaceholder: "Adınız və soyadınız",
    termsIntro: "Qəbul edirəm:",
    and: "və",
  },
};
