-- Letting somebody say an answer was wrong.
--
-- Required by Google Play: an app whose content is generated by AI must offer
-- in-app reporting of offensive or harmful output, and the reports must inform
-- how the content is moderated. It is also the only channel we have for
-- learning that the assistant said something bad, which matters more here than
-- the policy does.
--
-- The reported message is referenced, not copied. It is already stored once and
-- it is the person's own conversation; duplicating it into a moderation table
-- would put clinical content somewhere it does not need to be.

CREATE TABLE answer_report (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    chat_message_id BIGINT NOT NULL,
    -- WRONG, HARMFUL, OFFENSIVE, OTHER. What kind of wrong it was.
    reason VARCHAR(24) NOT NULL,
    -- What the person chose to add. Optional, and theirs.
    note VARCHAR(1000) NULL,
    -- Who reported it, where we know. A guest session has no user.
    reported_by_user_id BIGINT NULL,
    guest_session_id VARCHAR(255) NULL,
    -- OPEN, REVIEWED, ACTIONED. Somebody has to be able to work through them.
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_at DATETIME(6) NULL,
    CONSTRAINT fk_answer_report_message FOREIGN KEY (chat_message_id)
        REFERENCES chat_messages (id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_report_user FOREIGN KEY (reported_by_user_id)
        REFERENCES users (id) ON DELETE SET NULL,
    KEY idx_answer_report_status (status, created_at)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
