-- The 42 Liv Bona Dea doctors the first import missed.
--
-- V22 was built from a saved copy of the hospital's directory page and caught
-- 70 of the doctors listed there. The hospital's own list now has 112; a
-- patient searching for a doctor they have been told to see, and not finding
-- them, concludes the directory is wrong - which it was. This adds the rest,
-- read from the same public profiles in the same way.
--
-- Everything V22 said still holds: none of these doctors asked to be listed,
-- so every row is UNCLAIMED with bookings off, and repeats only what the
-- hospital publishes. Photos are hosted by us, never linked.
--
-- Data only. Ten departments the hospital has that our taxonomy did not are
-- added as specialties first, so no listing lands without a translated name.

INSERT IGNORE INTO specialty (code, name_az, name_en, name_ru, patient_facing, ai_specialty_code, sort_order) VALUES
('bariatric-surgery','Bariatrik cərrahiyyə','Bariatric Surgery','Бариатрическая хирургия',1,'general',100),
('dentistry','Stomatologiya','Dentistry','Стоматология',1,'general',101),
('home-care','Evdə tibbi xidmət','Home Medical Care','Медицинская помощь на дому',1,'general',102),
('medical-aesthetics','Medikal estetika','Medical Aesthetics','Эстетическая медицина',1,'derma',103),
('pediatric-intensive-care','Uşaq reanimasiyası','Paediatric Intensive Care','Детская реанимация',1,'pediatric',104),
('breast-surgery','Süd vəzi cərrahiyyəsi','Breast Surgery','Маммология',1,'general',105),
('pediatric-endocrinology','Uşaq endokrinologiyası','Paediatric Endocrinology','Детская эндокринология',1,'pediatric',106),
('pediatric-cardiology','Uşaq kardiologiyası','Paediatric Cardiology','Детская кардиология',1,'pediatric',107),
('child-psychology','Uşaq və yeniyetmə psixologiyası','Child and Adolescent Psychology','Детская и подростковая психология',1,'psych',108),
('interventional-radiology','İnvaziv radiologiya','Interventional Radiology','Интервенционная радиология',1,'general',109);

SET @clinic_id = (SELECT id FROM clinic WHERE slug = 'liv-bona-dea-hospital');

INSERT IGNORE INTO doctor
    (full_name, slug, specialty_code, qualifications, years_experience, bio,
     photo_url, languages, verification, source, accepts_bookings, active, created_at, updated_at)
VALUES
    ('Doç.Dr. ANAR MAHMUDOV', 'doc-dr-anar-mahmudov', 'dermatology', 'Azerbaycan Tibb Universiteti 2000-2006 | Sechenov adina Moskva Tibb Universiteti ordinatura 2006-2008 | Aspirantura 2008-2011', 20, 'İş təcrübəsi: Sechenov klinikasi; Medlux klinikasi ( Moskva) 2008-2018; Bonadea, National Prime Hospital 2008-2022; Liv Bona Dea Hospital - 2023 - indiyənə qədər; 1. Mahmudov A, Olisova O, Borovaya A. Antimicrobial peptide LL-37 and its level in acne patients undergoing blue light therapy. Russian Journal of skin and sexually-transmitted diseases 2012; 4:51-53. (In Russian); 2. Mahmudov A, Olisova O, Pinson I, Verkhoglyad I. Blue light in acne treatment. Plastic and aesthetic surgery 2010; 3:487- 490. (In Russian); 3. Olisova O, Mahudov A. External acne treatment. Dermatology. Supplement to Consilium Medicum 2010; 3:8-10. (In Russian); 4. Olisova O, Mahmudov A. Topical therapy of acne. Experimental and Clinical dermatology 2011; 6: 3-6. (In Russian); 5. Olisova O, Verkhoglyad I, Pinson I, Mahmudov A. Acne treatment. Experimental and clinical cosmetic dermatology 2010; 1:11-15. (In Russian); 6. Mahmudov A, Olisova O. (2010, May) Blue light therapy in acne treatment. Articles of dermatological conference "Topical issues in dermatovenerology and dermato oncology".pp.143-145.(In Russian); 7. Olisova O, Ivanova E, Mahmudov A. (2010, December). Blue light (405-420nm) in acne treatment. Morphofunctional caracteristics of the skin. Modern aspects of dermatovenerology.pp.111-112. (In Russian).', '/doctor-photos/doc-dr-anar-mahmudov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Doç.Dr. FƏRİD RƏFİYEV', 'doc-dr-ferid-refiyev', 'bariatric-surgery', '1998-2004 ATU-nin 1-ci müalicə-profilaktika fakültəsi ( Fərqlənmə ilə) | 2004-2006 cı illər ATU-nun 1-ci cərrahi xəstəliklər kafedrasının klinik ordinatoru | 2006-2009-ci illər ATU-nun 1-ci cərrahi xəstəliklər kafedrasının aspirantı | 2007-ci ildə "Miniinvaziv cərrahiyyə" "Laparoskopik cərrahiyyə" kurslarını Almaniyanın (Berlin şəhəri) "Vivantes Humbolt klinikum" və "DrK klinikum Westend" klinikalarında keçib. Prof. Dr.Ernest Kraas-ın "Laparoskopik cərrahiyyənin mütəxəssisi" adına layiq görülmüşdür. | 20...', 22, 'İş təcrübəsi: 2007-2015-ci illərdə Uniklinika xəstəxanasının cərrahiyyə şöbəsinin müdiri; 2015-2023 Medera Hospitalda Cərrahiyyə Şöbəsinin Müdiri vəzifəsində çalışıb; 2023- Liv Bonadea Hospitalda Metabolik-Bariatrik mərkəzinin rəhbəri vəzifəsində çalışır.', '/doctor-photos/doc-dr-ferid-refiyev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. ABBASƏLİ ABBASƏLİYEV', 'uzm-dr-abbaseli-abbaseliyev', 'cardiology', '9 Eylül Universiteti (İzmir/Türkiyə) 1991-1997 | Ege Universteti Kardiologiya Bölməsində Uzmanlık 1997-2001', 29, 'İş təcrübəsi: 2001-2003 Ataklp Ürək xəstəlikləri xəstəxanasında Uzman həkim; 2003-2006 Mərkəzi Klinika Kardioloq/ Şöbə müdürü; 2006-20017 Mərkəzi Neftçilər Xəstəxanası Kardioloq/Şöbə müdürü; 2017-2022 Resbuklika Diaqnostika Mərkəzi Kardioloq/ İnvaziv kardiologiya Bölməsinin müdürü; Avropa Kardiologiya Cəmiyyəti; Türkiyə Kardiloji Dərnəyi; Azərbaycan Kardiologiya Cəmiyyəti.', '/doctor-photos/uzm-dr-abbaseli-abbaseliyev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. ADİLƏ ADİLLİ', 'uzm-dr-adile-adilli', 'pathology', 'Bezmialem Vakıf Universiteti, Tibb Fakültəsi | Tibbi Patologiyada Mütəxəssislik Təlim Proqramı (Avqust, 2016-Avqust,2020) | Elmi-Tədqiqat Mamalıq ve Ginekologiya İnstitutu (Azərbaycan) | Mamalıq ve Ginekologiya ixtisası üzrə rezidentura təhsili (Sentyabr 2013-İyul 2016) | Azərbaycan Tibb Universiteti, Bakı, Azərbaycan | Diplom (Sentyabr 2006-İyul 2013)', NULL, NULL, '/doctor-photos/uzm-dr-adile-adilli.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. Alim Əkbərov', 'uzm-dr-alim-ekberov', 'general-surgery', 'Akdeniz Universiteti, Antalya, Türkiyə - 2016 - 2021 | Azərbaycan Tibb Universiteti, Bakı, Azərbaycan - 2008 - 2014', 12, 'Fəaliyyət sahələri: Qalın bağırsaq (Kolon) cərrahi xəstəlikləri (Kolon Kanseri-Bədxassəli şiş,poliplər,divertikulit,ülseratif kolit,Crohn), Düz bağırsaq (Rektum) cərrahi xəstəlikləri (Rektum Kanseri-Bədxassəli şiş,poliplər), Qaraciyərin və qaraciyər daxili öd yollarinin cərrahi xəstəlikləri ( HCC,Kolanjiokarsinoma,Hepatik adenoma,Kist hidatik-Exinokok), Öd kisəsi və qaraciyər xarici öd yollarının cərrahi xəstəlikləri (Öd kisəsi Kanseri,Öd daşı xəstəliyi,Xoledox Tümörleri,öd yollarının iatrojenik yaralanmaları), Pankreasın (mədəaltı vəzi) cərrahi xəstəlikləri (Pankreas kanseri,Psödokist,İPMN,seroz kistadenom), Mədə və Oniki barmaq bağırsaqın cərrahi xəstəlikəri (Mədə Karsinoması,duodenum karsinoması,perforasiya,qanama), Nazik bağırsaqların cərrahi xəstəlikləri (Crohn xəstəliyi,şişlər,bezoar,Meckel divertikuliti,qanama), Qarın Ön divarı və qasıq yırtıqları (qrija), Diafraqma Yırtıqı (Mədə yırtığı), Qalxanabənzər vəzinin cərrahi xəstəlikləri (zob xəstəliyi,Toksik Guatr,Tiroid karsinoması,Multinoduler Guatr), Anorektal Xəstəliklər (anal çat,hemoroid-babasil,anal apses,anal fistula), Böyrəküstü vəzinin cərrahi xəstəlikləri (Adenoma,karsinoma,feoxromasitoma).
İş təcrübəsi: 2016-2021 Akdeniz Universitesi hastanesi Araştırma Görevlisi (Rezident Həkim),Antalya,Türkiyə; 2021-2022 Bioloji Təbabət Klinikası həkim-ümumi cərrahiyyə mütəxəssisi; 2022-2024 Yeni Klinika Həkim-Ümumi cərrahiyyə mütəxəssisi; 2024......Liv Bonadea international hospital həkim-Ümumi Cərrahiyyə mütəxəssisi.', '/doctor-photos/uzm-dr-alim-ekberov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. Anar Qurbanov', 'uzm-dr-anar-qurbanov', 'pediatric-intensive-care', 'Tibv Üniversiteti, 2004-2010 | Merkezi Klinik Xestexana, İnternatura, 2010-2011 | Hacettepe Üniversitesi Tıp Fakültesi Çocuk Sağlığı ve Hastalıkları, 2014-2019 | Ankara Üniversiteti Tıb Fakültesi Çocuk Yoğun Bakım, 2019-2022', 16, 'İş təcrübəsi: Hacettepe Üniversitesi Tıp Fakültesi Çocuk Sağlığı ve Hastalıkları. Aprel 2014 - Yanvar 2019; Özel Lokman Hekim Üniversitesi: Pediatri Uzmanı. Fevral 2019 - Noyabr 2019; Ankara Üniversiteti Tıb Fakültesi Çocuk Yoğun Bakım. Noyabr 2019 - Noyabr 2022; Merkezi Klinik Xestexana, Pediatrik Yoğun Bakım (Şöbə müdiri), Noyabr 2022-May 2024; Liv Bona Dea Hospıtal-2024; Araştırma Görevlisi; Hacettepe Üniversitesi Tıb Fakültesi Çocuk Sağlığı ve Hastalıkları ABD Araştırma Görevlisi Ankara (Aprel 2014 TUS imtahanı ile) 2014 İyul - 2019 Yanvar; Ankara Üniversitesi Tıb Fakültesi Çocuk Sağlığı ve Hastalıkları ABD, Çocuk Yoğun Bakım Bilim Dalı Yan Dal Araştırma Görevlisi (Dekabır 2018 YDUS imtahanı ile) 2019 Kasım - 2022 Kasım.', '/doctor-photos/uzm-dr-anar-qurbanov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. AYDAN İSGƏNDƏRZADƏ', 'uzm-dr-aydan-isgenderzade', 'child-psychology', '2008-ci ildə 661 bal toplayaraq Azərbaycan Dövlət Tibb Universitetinin II. Müalicə Profilaktika Fakültəsinə daxil olmuşdur və həmin fakültədən 2014-cü ildə fərqlənmə diplomu ilə məzun olmuşdur. Bu müddət ərzində Ankara Universiteti Ankara Tibb Fakülteti Mama-qinekologiya Kafedrasında (8 iyul 2011-10 Avqust 2011), eləcə də İstanbul Universiteti Çapa Tibb Fakülteti Mama-qinekologiya Kafedrasında (15 iyul 2012-12 Avqust 2012) təlim keçmişdir. | 2016-2020 İstanbul Universiteti Uşaq və Yeniyetmə Psixiatriyası...', 6, 'Fəaliyyət sahələri: Depressiya, Təşviş pozuntusu, Diqqət əksikliyi və hiperaktiv pozuntu, Sidik / nəcis tutma problemləri, Xüsusi öyrənmə pozuntusu, İnternet asılılığı, Qidalanma və yemək pozuntusu, Özünə zərər verici davranışlar, Autizm Spektr Pozuntusu, İnkişaf pozuntusu, Nitq pozuntusu, Davranış pozuntusu, Travma Sonrası Stres Pozuntusu, Tik pozuntusu, Tibbi xəstəliyə uyğunlaşma, Psixosomatik pozuntu, Akademik problemlər, Ailə problemləri, Uşaqlarda inkişafın təqibi, Valideyn Maarifləndirməsi.', '/doctor-photos/uzm-dr-aydan-isgenderzade.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. AYGÜN HƏMİDOVA', 'uzm-dr-aygun-hemidova', 'obstetrics-gynecology', 'Azərbaycan Tibb Universiteti- Tibb Fakültəsi- 2005-2011 | Akdeniz Universiteti Tibb Fakültəsi - Qadın Xəstəlikləri və doğum uzmanlığı- 2015-2020', 15, NULL, '/doctor-photos/uzm-dr-aygun-hemidova.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. Aynurə Həmidova', 'uzm-dr-aynure-hemidova', 'obstetrics-gynecology', 'Azərbaycan Tibb Universiteti Müalicə İşi 2004-2010 | Ankara Qazi Universiteti Uzmanlıq təhsili 2012-2016', 16, 'Fəaliyyət sahələri: Normal və riskli hamiləliklərin təqibi , Normal və cərrahi doğum, Ginekoloji xəstəliklərin diaqnostika və müalicəsi , Bütün növ açıq,laparaskopik(qapalı) ,vaginal ginekoloji əməliyyatlar, Sonsuzluğun müalicəsi, Aşılama(İntrauterin inseminasiya) , Süni mayalanma.
İş təcrübəsi: Qazi Universiteti Hastanesi (Ankara, Türkiyə)Qadın Xəstəlikləri Doğum və Süni Mayalanma 2012- 2016; Qadın xəstəlikləri və doğum üzrə Araşdırma mütəxəssisi 2016- 2017; Özel Erdem Hastanesi Çamlıca (İstanbul, Türkiyə); Özel Esencan Hastanesi (İstanbul, Türkiyə) 2017-2018; Ege Hospital; Baki Medikal Plaza; Leyla Medical Center; Liv Bona Dea Hospital 2022; Sertifikatlar Və kurslar; GYNOCAS (Gynecology Cadaver School ) -2.Pelvik Anatomi ve Cerrahi Kadavra Kursu (28-29 Mayis 2016 Ankara ,Turkiye ); IV.Jinekolojide Laparaskopik Cerrahi Kursu- (04.2016-Ankara,Türkiyə); TJOD Ankara Şubesi. Jinekolojik Endoskopi Dərnəyi.Etlik- Zübeydəhanım; Laparokopi, Histereskopi və Acil Obstetrik Sütür kursu (03.2016-Ankara,Türkiyə); Gazi Universiteti Tibb Fakültəsi; Numunəvi Həkim Olmaga Doğru (11.2012- İzmir, Türkiyə); Ege Universiteti Tibb Fakultəsi; Temel Epidemiyoloji Kursu (04.2012 - Ankara,Türkiyə); Üreme Sağlığı ve İnfertilite Derneği); Türkiyə Türkcesi Eğitim Sertifikası (12.2011-Bakı, Azərbaycan); T.C Bakü Büyükelçiliği Milli Eğitim Bakanlığı; Tibb Doktorluğu Denklik Belgesi (07.2011 -Bakı, Azərbaycan)T.C Bakü Büyükelçiliği Milli Eğitim Bakanlığı; Iç Anadolu Kontrasepsiyon kongresi (19-20mart 2016 TJOD Ankara Şubesi); Postgraduated Training Course Fetal Heart Examination .World School of Perinatal Medicine (18 yanvar 2019 Bakı, Azərbaycan); Perinatal Təbabət Üzrə Konfrans (24-25 yanvar 2020 Bakı, Azərbaycan ); Mamalıq vəziyyətlərinin və ginekoloji xəstəliklərin diaqnostikasında və müalicəsində yeni aspektlər (4 mart 2020 Bakı Azərbaycan ); Uroginekoloji elmi praktik beynəlxalq tibbi konfrans (23 yanvar 2022 Bakı Azərbaycan ); Fetal Medicine and Prenatal Diagnosis Congress (12,13 fevral 2022 Bakı Azərbaycan ); ESHRE 38th Annual Meeting .3-6 July Milan, Italy.', '/doctor-photos/uzm-dr-aynure-hemidova.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. AYNURƏ RÜSTƏMZADƏ', 'uzm-dr-aynure-rustemzade', 'gastroenterology', 'Azərbaycan Tibb Universiteti - Müalicə işi (2005-2011) | Marmara Universiteti Pendik Eğitim və Araştırma Xəstəxanası - Daxili xəstəliklər uzmanlığı (2017-2021) | İstanbul Universiteti, İstanbul Tibb Fakultəsi - Gastroenterologiya və Hepatologiya Uzmanlığı | Course of patients with Ulcerative colitis who have achieved disease clearance from the moment of diagnosis." | Journal of Crohn''s and Colitis | 19.Supplement_1 (2025): i2067-i2068. | Factors Determining the Prognosis of Chronic Intestinal Pseudoobstr...', 15, NULL, '/doctor-photos/uzm-dr-aynure-rustemzade.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. AZƏR ƏLİZADƏ', 'uzm-dr-azer-elizade', 'orthopedics', 'Azərbaycan Tibb Univeristeti 2006-2013 | Ankara Universiteti Tibb fakültəsi Ortopediya və Travmatoloji bölümü 2015-2020', 13, 'İş təcrübəsi: Ankara Universiteti Xəstəxanası 2015-2020; Ankara Acıbadem Universiteti 2021-2022; Ankara Özəl Natomed xəstəxanasi Ortopediya və Travmatologiya uzmanı 2020-2022; Respublika Klinik Xəstəxanası 2022-2023; Nizami Tibb Mərkəzi 2023-2024; 2022 2023 Badam medical center ,; Mediland hospital Ortopediya və Travmatoloji uzmanı.', '/doctor-photos/uzm-dr-azer-elizade.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. AZƏR QULUZADƏ', 'uzm-dr-azer-quluzade', 'neurology', 'Istanbul Bezmi-Alem Universiteti Xəstəxanası Nevrologiya Kafedrası, 2016-2020 | Lənkəran şəhəri Mərkəzi Xəstəxanası Terapiya Şöbəsi Internatura, 2010-2011 | Azərbaycan Dövlət Tibb Universiteti Müalicə-Profilaktika fakültəsi, 2004-2010', 16, NULL, '/doctor-photos/uzm-dr-azer-quluzade.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. BƏHRUZ ƏLİYEV', 'uzm-dr-behruz-eliyev', 'pediatric-cardiology', 'Pediatrik Kardiologiya üzrə Alt ixtisas Təhsili İstanbul Universiteti İstanbul Tibb Fakültəsi Pediatrik Kardiologiya İxtisası 2016-2019 | İxtisaslaşma Təhsili İstanbul Universiteti İstanbul Tibb Fakültəsi Uşaq sağlamlığı və xəstəlikləri Şöbəsi 2011-2015 | Tibb Təhsili Atatürk Universiteti Tibb Fakültəsi 2007 | Tibb Təhsili Azərbaycan Tibb Universiteti1998-2004', 22, 'Fəaliyyət sahələri: Pediatrik ekokardioqrafiya, Kompleks anadangəlmə ürək xəstəlikləri diaqnozu, Qazanılmış ürək xəstəlikləri diaqnozu və təqibi, Ürək çatışmazlığı diaqnozu və təqibi, Preoperativ diaqnoz və postoperativ exokardioqrafik təqib, Transezofageal exokardioqrafiya, Epikardial exokardioqrafiya, Kateter angioqrafiya, Kompleks anadangəlmə ürək xəstəliklərində diaqnostik kateter angioqrafiya, Hemodinamik tədqiqatlar və vazoreaktivlik testi, İnvaziv (interventional) kardiologiya, Cihazla (device) bağlama prosedurları (PDA, ASD, VSD, Pulmonar anteqrad axın və s.), Arteriya və/və ya vena embolizasiyası (Spiral və ya vaskulyar cihazla), Balon atrial septostomiya, Stent prosedurları (PDA stenti, RVOT stent implantasiyası, aorta koarktasiya stenti, vaskulyar stent, atrial septal stentləmə), Balon angioplastika ve valvuloplastika prosedurları (Pulmonar və aorta), Pediatrik ürək ritm pozuntuları, Pediatrik EKG dəyərləndirmə, Pediatrik ritmin holterlə dəyərləndirilməsi, Kardiak aritmiyaların diaqnoz, müalicə və təqibi, Transkateter müvəqqəti və daimi kardiostimulyator yerləşdirilməsi.', '/doctor-photos/uzm-dr-behruz-eliyev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. CABİR GÜLMALIYEV', 'uzm-dr-cabir-gulmaliyev', 'cardiovascular-surgery', 'Ege Universiteti - İzmir, TÜRKİYƏ Tibb Fakültəsi 09/2004 - 06/2010 | Ege Universiteti Tibb Fakültəsi - İzmir, TÜRKİYƏ 07/2009 - 06/2010. | Bakırköy Dr.Sadi Konuk Təhsil və Araşdırma Xəstəxanası Ürək-damar Cərrahiyyəsi şöbəsi - İstanbul, TÜRKİYƏ 03/2011 - 03/2016', 17, 'İş təcrübəsi: 07/2009 - 07/2010. Ege Universiteti Xəstəxanasında internatura; 03/2011 - 03/2016. İstanbul Bakırköy Dr.Sadi Konuk Təhsil və Araşdırma Xəstəxanası Ürək-damar Cərrahiyyəsi şöbəsinin rezidenti; 10/2016 - 10/2017. Naxçıvan Hərbi Hospitalının ürək-damar cərrahı; 4/2016 - 07/2018. Naxçıvan Diaqnostika və Müalicə Mərkəzində ürək-damar cərrahı; 2018-...... Liv Bona Dea Xəstəxanası; Heart Surg Forum. 2015 Aug 30;18(4):E151-3. doi: 10.1532/hsf.1368; Turk Gogus Kalp Damar 2014;22(3):489-495. doi: 10.5606/tgkdc.dergisi.2014.9415; Ulus Travma Acil Cerr Derg, January 2014, Vol. 20, No. 1; HSR Proc Intensive Care Cardiovasc Anesth. 2013;5(2):119-20; Anadolu Kardiyol Derg. 2013 May 10. doi: 10.5152/akd.2013.136; Ann Thorac Surg. 2013 Apr;95(4):1443-5. doi: 10.1016/j.athoracsur.2012.08.080; October 26-29, 2013 Istanbul, Turkey. Annals of Vascular Diseases Vol 6, Supplement (2013); İnternational Journal of Cardiyology Volume 155, Supplement 1, Pages iii-vi, S1-S240 (March 2012) Abstracts of the 8th International Congress of Update in Cardiology and Cardiovascular Surgery Pages S62-S63; İnternational Journal of Cardiyology Volume 155, Supplement 1, Pages iii-vi, S1-S240 (March 2012) Abstracts of the 8th International Congress of Update in Cardiology and Cardiovascular Surgery Pages S63; 12.Ulusal Kalp-Damar Cerrahisi Kongresi, 8-11 Kasım 2012 Antalya,Türkiye; 12.Ulusal Kalp-Damar Cerrahisi Kongresi, 8-11 Kasım 2012 Antalya,Türkiye; 12.Ulusal Kalp-Damar Cerrahisi Kongresi, 8-11 Kasım 2012 Antalya, Türkiye; Koşuyolu Kalp Dergisi doi: 10.5578/kkd.6456; Koşuyolu Kalp Dergisi doi: 10.5578/kkd.6164; Cukurova Med J 2016;41(Suppl 1):5-7 DOI: 10.17826/cutf.254573; Damar Cer Derg 2016. doi: 10.9739/uvcd.2015-43581; Cukurova Med J 2018;43(Suppl 1):222-229 DOI: 10.17826/cumj.422290; 29 ekim-1 kasım 2015 Antalya. Damar Cerrahisi Dergisi 2015:(suppl; X.Adli Bilimler Sempozyumu 13-16 Kasım Ankara, Türkiye; 26-29 ekim 2013 İstanbul. Damar Cerrahisi Dergisi 2013:22(suppl) S38.', '/doctor-photos/uzm-dr-cabir-gulmaliyev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. CAVANŞİR VAHABOV', 'uzm-dr-cavansir-vahabov', 'gastroenterology', 'Azərbaycan Tibb Universiteti, Müalicə İşi - 2003-2009 | Hacettepe Universiteti Xəstəxanası, Daxili Xəstəliklər - 2013-2017 | Hacettepe Universiteti Xəstəxanası, Qastroenterologiya - 2018-2021', 17, 'Fəaliyyət sahələri: Ağız, Qida borusu, Nazik bağırsaq, Qaraciyər, Öd yolları və mədəaltı vəzi və s.
İş təcrübəsi: Ankara Özəl Koru Xəstəxanası, Daxili xəstəliklər, mütəxəssisi - 2017-2019; Lokman Həkim Ankara Xəstəxanası, Daxili xəstəliklər, mütəxəssisi - 2019-2020; Ankara Özəl Koru Xəstəxanası, Daxili xəstəliklər, mütəxəssisi - 2020-2021; EGE Hospital, Qastroenteroloq, 2021-2024; Liv Bona Dea Hospital, Qastroenteroloq.', '/doctor-photos/uzm-dr-cavansir-vahabov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('UZM. Dr. ELÇİN ŞİRİNOV', 'uzm-dr-elcin-sirinov', 'emergency-medicine', 'Azərbaycan Tibb Universiteti (2010 - 2016) | Ege Universiteti Tıp Fakültesi Hastanesi Acil Tıp Anabilim Dalı - Acil Tıp Uzmanı (2021-2025)', 10, NULL, '/doctor-photos/uzm-dr-elcin-sirinov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. ELNUR QASIMOV', 'uzm-dr-elnur-qasimov', 'pediatrics', '2000-2006 Azərbaycan Tibb Universiteti - Pediatriya fakultəsi | 2006-2007 6№ Uşaq Kliniki Xəstəxanası - İnternatura | 2016-2020 İstanbul Üniversitesi Cerrahpaşa Tıp Fakultesi, Çocuk Sağlığı ve Hastalıkları Bölümü - Uzmanlıq', 20, 'Fəaliyyət sahələri: Yenidoğulmuş körpələrin təqibi, Yarımçıqdoğulmuş körpələrin təqibi, Peyvəndlərin aparılması, Uşaq sağlamlığının izlənilməsi (0-18 yaş), Uşaqlarda iştahsızlıq, Böyümə və inkişafın yaşıdlarından geri qalması, İnfeksion xəstəliklər, Tənəffüs sistemi xəstəlikləri, Mədə bağırsaq sistemi xəstəlikləri, Sidik ifrazat sistemi xəstəlikləri, Allergik xəstəliklər, Anemiyalar, Uşaqlarda təxirəsalınmaz tibbi dəyərləndirmə və təxirəsalınmaz yardımın göstərilməsi, Uşaqlarda pediatriyanın digər dar sahələri üzrə ola biləcək sağlamlıq problemlərinin aşkarlanması və yönləndirilməsi və s.
İş təcrübəsi: 2010 - 2011; Hacıqabul rayon mərkəzi xəstəxanası; 2021 - 2024; Leyla Medical Center - Neonatalogiya və Pediatriya.', '/doctor-photos/uzm-dr-elnur-qasimov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. ƏHMƏD ABDULLAYEV', 'uzm-dr-ehmed-abdullayev', 'ophthalmology', '2004-2010. Azərbaycan Tibb Universiteti- Müalicə Profilaktika Fakultəsi | 2011-2015. Ankara Universiteti Göz Xəstəlikləri Kafedrası Uzmanlıq təhsili', 16, 'Fəaliyyət sahələri: Katarakta əməliyyatı ( Monofokal, Edof, Trifokal linzalar, ikincili linza qoyulması), Retina xəstəliklərinin medikal müalicəsi, Qlaukoma ( göz təzyiqi xəstəliyi) xəstəliyinin medikal və cərrahi müalicəsi, Çəpgözlük və onun cərrahi müalicəsi, Excimer lazer cərrahiyyəsi ( Femto-Lasik, PRK, SMİLE), Kornea xəstəliklərinin müalicəsi (medikal müalicə və Keratoplastika əməliyyatı), Keratokonus xəstəliyinin Kross linking metodu ilə müalicəsi, Üveit xəstəliyinin müalicəsi, Göz yaşı kanal tıxanıqlığının müalicəsi ( DSR əməliyyatı), Uşaqlarda göz yaşı kanal tıxanıqlığının sondalama üsulu ilə açılması.
İş təcrübəsi: 2016-2024. Celamig Göz Klinikası; 2019-2022. Elmi Tədqiqat Tibbi Bərpa İnstitutu; 2019. Almanya Köln LasikWelt Klinikası- Excimer Lazer kursu.', '/doctor-photos/uzm-dr-ehmed-abdullayev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. ƏKBƏR HACIYEV', 'uzm-dr-ekber-haciyev', 'pathology', 'Hacettepe Universiteti, Hacettepe Universitetinin Patologiya şöbəsi, Tibb fakültəsi, Ankara, Türkiyə | Naqoya Universiteti, Tibb İnstitutu, Şiş Patologiya Laboratoriyası, Yaponiya, 2018,', NULL, NULL, '/doctor-photos/uzm-dr-ekber-haciyev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. FUAD MUSTAFAYEV', 'uzm-dr-fuad-mustafayev', 'gastroenterology', 'Azərbaycan Tibb Universiteti Bakı/Azərbaycan, 2001-2007 | Ankara Atatürk Eğitim ve Araştırma Hastanesi İç Hastalıkları Ankara/Türkiyə, 2012-2017 | Hacettepe Üniversitesi Tıp Fakültesi Gastroenteroloji BD Ankara/Türkiye, 2018-2021', 19, 'Fəaliyyət sahələri: Daxili xəstəliklər və Qastroenterologiya.
İş təcrübəsi: Xaçmaz MRX / Anestezioloq Reanimatoloq 08/2007 - 11/2009, Xaçmaz/Azərbaycan; Ankara Atatürk Eğitim ve Araştırma Hastanesi / İç Hastalıkları Asist. Dr 08/2012 - 01/2017, Ankara/Türkiye; Lokman Hekim Akay Hastanesi / İç Hastalıkları Uzm. Dr 06/2017 - 05/2018, Ankara/Türkiye; Özel Koru Ankara Hastanesi / İç Hastalıkları Uzm. Dr 07/2018 - 07/2019, Ankara/Türkiye; Hacettepe Üniversitesi Tıp Faklütesi / Gastroenteroloji Fellowship 07/2019 - 12/2021, Ankara/Türkiye; Lokman Hekim Üniversitesi Ankara Hastanesi / İç Hastalıkları Uzm. Dr 09/2019 - 10/2021, Ankara/Türkiye; Ege Hospital / Qastroenteroloq Uzm. Dr 01/2022 - 09/2022 , Bakı/Azərbaycan; Yeni Klinika / Qastroenteroloq Uzm. Dr 10/2022 - 12/2024 , Bakı/Azərbaycan.', '/doctor-photos/uzm-dr-fuad-mustafayev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. GÜLNAR ƏZİMOVA', 'uzm-dr-gulnar-ezimova', 'pediatrics', 'I müalicə profilaktika fakultəsi - Azərbaycan Tibb Universiteti (2004-2010) Bakı, Azərbaycan Uşaq sağlamlığı və xəstəlikləri uzmanlıq təhsili - İnönü Universiteti (2016-2020) Malatya, Türkiyə', 16, 'Fəaliyyət sahələri: Yenidoğulmuşların problemləri, Uşaqlarda nefroloji xəstəliklər, Endokrin sistem xəstəlikləri, Qastrointestinal sistem xəstəlikləri, Uşaq acil xəstəlikləri, Sağlam uşaq inkişaf izlənməsi, Uşaq reanimasiyası, Uşaq allergik xəstəlikləri, Uşaq infeksiyon xəstəlikəri və .s.
İş təcrübəsi: Füzuli rayon mərkəzi xəstəxanası - İnternatura (2010-2011) Füzuli, Azərbaycan; Füzuli rayon mərkəzi xəstəxanası - Həkim terapevt (2011-2016) Füzuli, Azərbaycan; Özəl ADN Xəstəxanası - Uzman Pediatr / Neonatoloq (2020-2022) Gaziantep, Türkiyə; Leyla medikal center - Uzman Pediatr / Neonatoloq (01.06.2022-18.12.2023) Bakı, Azərbaycan; Liv bona dea hospital - Uzman Pediatr / Neonatoloq (19.12.2023-davam) Bakı, Azərbaycan.', '/doctor-photos/uzm-dr-gulnar-ezimova.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. GÜNEL MƏMMƏDOVA', 'uzm-dr-gunel-memmedova', 'breast-surgery', 'İstanbul Universiteti Cərrahpaşa Tibb Fakültəsi | Marmara Universiteti Pendik Eğitim Araştırma Xəstəxanası', NULL, NULL, '/doctor-photos/uzm-dr-gunel-memmedova.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. HÜSEYİN CAVİT AYDOĞDU', 'uzm-dr-huseyin-cavit-aydogdu', 'pediatrics', 'İstanbul Üniversitesi İstanbul Tıp Fakültes | 1988-1994', 32, NULL, '/doctor-photos/uzm-dr-huseyin-cavit-aydogdu.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. İLKİN MƏCİDOV', 'uzm-dr-ilkin-mecidov', 'pediatric-endocrinology', NULL, NULL, NULL, '/doctor-photos/uzm-dr-ilkin-mecidov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. İRANƏ QORÇİYEVA', 'uzm-dr-irane-qorciyeva', 'obstetrics-gynecology', 'Orta təhsil - 283 nömrəli məktəb - 1996-2006 | Ali təhsil Azərbaycan Tibb Universiteti Pediatriya - 2006-2012 | Rezidentura təhsili Elmi Tədqiqat Mamalıq və Ginekologiya Universiteti Mamalıq və Ginekologiya - 2012-2017 | Uzmanlıq təhsili Bezmi Alem Vakıf Universitesi Hastanesi Qadın Xəstəlikləri və Doğum - 2017-2022', 20, 'Fəaliyyət sahələri: Normal doğuş, Qeysəriyyə, Qeysəriyyə sonrası normal doğuş, Vaginoplastika, Estetik əməliyyatlar, Açıq və Qapalı ginekoloji cərrahi əməliyyatlar, Laparoskopik əməliyyatlar, Vaginal cərrahiyyə, Histeroskopiya, Sidik qaçırma, Sonsuzluq.', '/doctor-photos/uzm-dr-irane-qorciyeva.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. Kurtuluş Yıldız', 'uzm-dr-kurtulus-yildiz', 'ophthalmology', NULL, 21, 'İş təcrübəsi: Liv Bona Dea Hospital, Bakı, Azərbaycan Oftalmolog | 2025 - davam edir; Batıgöz Bakı Oftalmoloq | 2021 - 2025; Dünyagöz Oftalmoloq | 2010 - 2020; İstanbul Kartal Göz Oftalmoloq | 2007-2010; Bursa Orhan Gazi Dövlət Xəstəxanası Oftalmoloq | 2005-2007.', '/doctor-photos/uzm-dr-kurtulus-yildiz.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. LEYLA HƏSƏNƏLİYEVA', 'uzm-dr-leyla-heseneliyeva', 'pathology', 'Başkent Universiteti Tibb Fakultəsi, Tibbi Patologiya bölümü, ixtisas təhsili (Dekabr 2019 - Mart 2024) | Elmi Tədqiqat Hematologiya və Transfuziologiya İnstitutu, Hematologiya ixtisas təhsili (Sentyabr 2014 - Fevral 2016) | Azərbaycan Tibb Universiteti, Müalicə İşi fakultəsi (Sentyabr 2008 - İyun 2014)', NULL, 'Fəaliyyət sahələri: Gastrointestinal sistem patologiyası, Sidik - cinsiyyət sistemi patologiyası, Süd vəzisi patologiyası, Dəri xəstəlikləri patologiyası, Tiroid patologiyası, Ağciyər xəstəlikləri patologiyası, Sinir sistemi patologiyası.', '/doctor-photos/uzm-dr-leyla-heseneliyeva.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. LEYLA MƏSIMOVA', 'uzm-dr-leyla-mesimova', 'neurology', '2005-2011-ci il Azərbaycan Tibb Universiteti | 2016-2020-ci il Uzmanlıq Ümraniye Təhsil və Araşdırma Xəstəxanası, | Nevrologiya Bölümü, İnsult Mərkəzi Nevroloq.', 15, 'İş təcrübəsi: 2021-2022-ci il Maltepe Ersoy Xəstəxanası,; EEQ və EMQ üzrə mütəxəssis Türkiyə; 2022-ci ildən etibarən Baku Medical Plaza Nevroloq; Hal-hazırda Liv Bona Dea Hospital-da Nevroloq.', '/doctor-photos/uzm-dr-leyla-mesimova.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. NƏZRİN TAĞIZADƏ', 'uzm-dr-nezrin-tagizade', 'psychiatry', 'Sumqayıt Dövlət Universiteti - Psixologiya, Bakalavr (2018-2022) | Doğuş Universiteti (Türkiyə) - Klinik (Tibbi) Psixologiya, Magistratura (2022-2024)', 4, NULL, '/doctor-photos/uzm-dr-nezrin-tagizade.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. NİCAT VƏLİYEV', 'uzm-dr-nicat-veliyev', 'pediatric-surgery', 'Azərbaycan Tibb Universiteti - 2010 | Azərbaycan Tibb Üniversiteti, İnternatura təhsili - 2011 | T.C Yükseköğretim Kurulu Başkanlığı Denklik Diplomu - 2012 | Marmara Universiteti, Uşaq Cərrahiyəsi Kafedrası, Uşaq cərrahiyyəsi uzmanlıq təhsil - 2018', 8, 'Fəaliyyət sahələri: Yenidoğulmuşların anadangəlmə qüsurlarının cərrahiyyəsi, Uşaq və yenidoğulmuşların qarın boşluğu organlarının cərrahiyyəsi, Uşaq və yenidoğulanların torakal (döş qəfəsi orqanları) cərrahiyyəsi, Uşaqlarda bədxassəli və xoşxassəli şişlərin cərrahiyyəsi (neyroblastoma, wilms şişi, metastatik ağciyər şişləri, mədə şişləri, teratomalar, yumurtalıq və testis şişləri), Laparaskopik cərrahi müdaxilələr, Torakoskopik cərrahi müdaxilələr, Bronkoskopik cərrahi müdaxilələr, Endoskopik cərrahi müdaxilələr, Uşaq urologiyası ve cinsiyyət orqanlarının inkişaf qüsurları, Uşaqlarda travma yönətimi, Uşaqların təcili cərrahi xəstəlikləri (kəskin apendisit, invaginasiya, yad cisim aspirasiyası, perforasiyalar ve s.), İnguinal və skrotal cərrahilər (qasıq yırtığı, enməmiş testis, hidrosel), Uşaqlarda Boyun bölgəsinin anadangəlmə və sonradan əmələ gələn cərrahi xəstəlikləri, Sünnət, Uşaq cərrahiyyəsi klinikası ve reanimasiyasının idarə olunması.
İş təcrübəsi: 25.04.2018-15.09.2019 Marmara Universiteti Pendik Eğitim və Araşdırma Xəstəxanası, Uşaq Cərrahiyyəsi uzmanı; 15.09.2018 - 12.03.2020 Marmara Üniversiteti Tibb Fakültəsi, Uşaq cərrahiyyəsi kafedrasında müəllim (Dr.Öğretim üyesi - asistant professor), uzman doktor; 13.03.2020 - 30.08.2020 özəl Gebze Yüzyıl Xəstəxanası, İstanbul; 01.09.2020 - 30.06.20204 Bakı şəhərində yerləşən özəl EGE HOSİTAL xəstəxanasında uşaq cərrahiyyəsi uzmanı; 01.07.2024 tarixindən etibarən Liv Bona Dea Hospitalda uşaq cərrahiyyəsi uzmanı olaraq fəaliyyət.', '/doctor-photos/uzm-dr-nicat-veliyev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. RÖVŞANƏ HƏSƏNZADƏ', 'uzm-dr-rovsane-hesenzade', 'pediatrics', '2012-2018Azərbaycan Tibb Universiteti - Müalicə Tibbi Proflaktika fakultəsi | 2020-2024 Hacettepe Üni | versitesi Tıp Fakultesi, Çocuk Sağlığı ve Hastalıkları Bölümü - Uzmanlıq', 8, NULL, '/doctor-photos/uzm-dr-rovsane-hesenzade.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. RUSLAN ƏSƏDOV', 'uzm-dr-ruslan-esedov', 'interventional-radiology', 'Azərbaycan Tibb Universiteti (2000-2006) | Marmara Üniversitesi Radyoloji ABD uzmanlık təhsili(2010-2015) | Marmara Üniversitesi Radyoloji ABD yabancı uyruklu öğretim görevlisi (2015-2018)', 20, 'Fəaliyyət sahələri: Invaziv və diaqnostik radiologiya.
İş təcrübəsi: Baki Medikal Plaza invaziv və diaqnostik radioloq həkim (2018-2024); Liv Bona Dea Hospital invaziv və diaqnostik radioloq (2024-).', '/doctor-photos/uzm-dr-ruslan-esedov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. SELİME AYDOĞDU', 'uzm-dr-selime-aydogdu', 'pediatric-hematology-oncology', 'Selçuk Üniversiteti Merap Tibb fakültəsi /Konya/ Türkiyə, 09/1987-07/1993 | İstanbul Zeynep Kamil Kadın Doğum ve Çocuk Hastalıkları Xəstəxanası /İstanbul/Türkiye, 07/1995-11/1999 | Yandal Uzmanlık: İstanbul Üniversiteti, İstanbul Tibb Fakültəsi (Çapa) /İstanbul/Türkiye 03/2014-11/2017', 32, 'Fəaliyyət sahələri: Qan xəstəlikləri (Hematologiya), Anemiyalar; qidalanma ilə bağlı anemiyalar: dəmir, B12 vitamini, fol turşusu çatışmazlığı, Hemolitik anemiyalar: Talassemiya, oraqvari hüceyrə xəstəliyi, G6FD çatışmazlığı, irsi siferositoz, Sümük iliyi çatışmazlıqları: Anadangəlmə və qazanılmış aplastik anemiya, neytropeniyalar, Trombosit xəstəlikləri: İTP, trombositlərin funksional pozuntuları, Hemorragik diatezlər: Hemofiliya, Villebrand xəstəliyi, Onkologiya, kəskin və xroniki leykozlar(ALL, AML, KML, JMML), Beyin şişləri, Limfomalar (Xoçkin və qeyri xoçkin limfomalar), Solid tümörlər (Wilms neyroblastoma, germ hüceyrəli tümörlər , rabdomiosarkoma, osteosarkoma, ewing sarkoma), Sümük iliyi köçürülməsi və hüceyrəvi müalicə.
İş təcrübəsi: 1994-1999. Zeynep Kamil Eğitim ve Araştırma Xəstəxanası/ Çocuk Sağlığı ve Hastalıkları Klinikası Asistan doktor, /İstanbul/Türkiyə; 2002-2010 Özel Darülaceze tibb mərkəzi, uşaq sasağlamlığı və xəstəlikləri Uzmanı, /İstanbul/Türkiyə; 2010-2014 TC . Sağlık Bakanlığı Ümraniye Eğitim ve Araştırma Xəstəxanası, Uşaq sağlamlığı və xəstəlikləri Uzmanı/Başasistan /İstanbul/Türkiye; 2014-2017 İstanbul Üniversiteti İstanbul Tibb fakültəsi/Uşaq Hematologiya və Onkologiya bilim dalı, Uşaq hematologiya və Onkologiya yan dal asistanı /İstanbul/Türkiyə; 2019-2021 Sivas Numune Xəstəxanası, Uşaq Hematologiya və Onkologiya Uzmanı, Sivas/Türkiyə; 2021-2024 Sağlık Bilimleri Üniversiteti Ümraniye Eğitim ve Araştırma Xəstəxanası.', '/doctor-photos/uzm-dr-selime-aydogdu.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm. Dr. SEVİL MƏMMƏDOVA', 'uzm-dr-sevil-memmedova', 'obstetrics-gynecology', NULL, NULL, NULL, '/doctor-photos/uzm-dr-sevil-memmedova.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. SƏBİNƏ FƏRZƏLİYEVA', 'uzm-dr-sebine-ferzeliyeva', 'internal-medicine', 'Azərbaycan Tibb Universiteti 2009-2015 | Hacettepe Tıp Fakultəsi İç Hastaliklari anabilim dalı 2017-2022', 11, 'Fəaliyyət sahələri: Arterial hipertenziya, qastrointestinal və qaraciyər xəstəlikləri, vitamin çatışmazlıqları, anemiyalar, şəkərli diabet, qalxanabənzər vəz xəstəlikləri, osteoporoz, böyrək xəstəlikləri, ağciyər xəstəlikləri, səbəbi bilinməyən qızdırmanın araşdırılması.', '/doctor-photos/uzm-dr-sebine-ferzeliyeva.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Uzm.Dr. YALÇIN MİRZƏYEV', 'uzm-dr-yalcin-mirzeyev', 'pediatrics', 'Azərbaycan Tibb Universiteti - 2005 - 2011 | Ankara Universiteti Tibb Fakültəsi Uşaq Sağlamlığı və Xəstəlikləri şöbəsi, təcrübə təhsili - 2008 - 2009 | Hacettepe Universiteti Tibb Fakültəsi Uşaq Sağlamlığı və Xəstəlikləri şöbəsi, İxtisas təhsili - 2012 - 2017', 17, 'İş təcrübəsi: Antalya Özəl Olimpos Xəstəxanası - 2017-2018 Respublika Diaqnostika Mərkəzi - 2018-2019 Antalya Özel Olimpos Xəstəxanası - 2019-2020; Bursa VM Medikal Park Xəstəxanası - 2020-2021; Leyla Medikal Center-pediatriya və neonatalogiya şöbə müdiri - 2021 - 2024; Liv Bona Dea Hospital - 2024 - Hal-hazırda.', '/doctor-photos/uzm-dr-yalcin-mirzeyev.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Dr. GÜNAY FEYZİYEVA', 'dr-gunay-feyziyeva', 'medical-aesthetics', 'Azarbaycan Tibb Universiteti - 2003-2009 | İstanbul Tibb Fakültəsi - 2023 səhiyyənin idarə olunması', 17, 'Fəaliyyət sahələri: Üzün Konturplastikası(Full Face), Çənə , yanaq, alin, dodaq dolgusu, Mezoterapiya, Mezoterapiya Piqment lekelerinin müalicəsi, Sac tökülmesi ve diger saç xestelikleri, Papillomalar, ziyil, mazol xesteliklerinin Fotona lazer ilə müalicəsi, Onixomikoz (dirnaq göbaleyi, xesteliklerinin Fotona lazer ilə müalicesi), Kiçik kapilyar damarların fotona lazer ilə götürülməsi və müalicəsi, Botulinoterapiyanin üz nahiyesine tətbiqi, Hiperhidrozun,plantar hiperhidroz(aşırı tərləmə)Botulinoterapiya ilə müalicəsi.', '/doctor-photos/dr-gunay-feyziyeva.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Dr. MERVE HAKAN', 'dr-merve-hakan', 'dentistry', 'Ayrancı Anadolu Lisesi, Ankara - 2006-2010 | Yakın Doğu Üniversitesi Diş Həkimliyi Fakültəsi - 2010-2015', 16, 'İş təcrübəsi: 2015-2016 Özel Diş Kliniği, Bursa; 2016-2019 Balıkesir Ağız ve Diş Sağlığı Merkezi; 2019-2024 Merve Hakan Diş Kliniği, Balıkesir.', '/doctor-photos/dr-merve-hakan.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Dr. SƏBİNƏ QULİYEVA', 'dr-sebine-quliyeva', 'home-care', 'Ondokuz Mayıs Universiteti, | Tibb Fakültəsi 2014-2020 | PSİKYATRKK DANISHMANLIK VE REHBERLİK - ONDOKUZ MAYIS UNİVERSİTESİ, SAMSUN/İLKADIM | Eyl | 2011 | Tem | 2012 | MID WIFE WORK - BAKU BASE MEDIKAL SCHOOL, BAKI/YASAMAL RAYONU | Eyl | 2006 | Tem | 2010 | FEN LİSESİ - 111 NUMARALI RÖVŞEN NASİROV ADINA, BAKÜ/NESIMI | Eyl | 1994 | May | 2005', 6, 'Fəaliyyət sahələri: Evdə Tibbi Baxım.
İş təcrübəsi: ŞÖBE MÜDÜRÜ VE YETKİLİ HEKİM - ÖZEL EGEPOL HASTANELERI EVDE SAĞLIK BİRİMİ, IZMIR /KONAK; Mar 2023; ŞÖBE MÜDÜRÜ VE YETKİLİ HEKİM - ÖZEL DERMAN HASTANESİ EVDE SAĞLIK MERKEZİ, IZMIR/GÖZTEPE - Ağu 2022 - Mar 2023; Özel Evde Sağlik kurumu şöbe müdürü - Özel Evde Sağlık Merkezı, SAMSUN/DEREBAHÇE - Eki 2021 - Nis 2022; Acil Servis Hekimi - ATASAM HASTANELERİ SAMSUN /ATAKUM, Samsun/Atakum - Şub 2021 - Ağu 2021; Acil Hekimi Ondokuz Mayis Universitesi, Samsun - Ara 2020 - Mar 2021.', '/doctor-photos/dr-sebine-quliyeva.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Dr. ŞƏMSİ AXUNDOV', 'dr-semsi-axundov', 'emergency-medicine', NULL, NULL, NULL, '/doctor-photos/dr-semsi-axundov.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Dr. ÜLVİYYƏ QULIYEVA', 'dr-ulviyye-quliyeva', 'neurology', 'Azərbaycan Tibb Universiteti - MD (2001) | Uşaq Nevroloji Xəstəxanası - Pediatrik nevrologiya, | Fellowship | (2007) | Danimarka Epilepsiya Mərkəzi, Dianalund, Danimarka - Pediatrik epileptologiya və EEG, | Fellowship (2013) | David Tvildiani Medical University - Phd (2020) | Harvard T.H. Chan School of Public Health - Tədqiqatda məsuliyyətli davranış kursu (2024) | Harvard Medical School, Boston Children''s Hospital - Postdoktoral təhsil (2024)', NULL, NULL, '/doctor-photos/dr-ulviyye-quliyeva.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW()),
    ('Dr. VƏFA NƏSİFOVA', 'dr-vefa-nesifova', 'endocrinology', '2004-2010 Azerbaycan Tibb Universiteti, 2-ci Müalicə Profilaktika Fakültəsi | 2012-2017 Istanbul Universiteti Istanbul Tibb Fakültəsi, Daxili Xəstəliklər Uzmanliq Təhsili | 2019-2022 Istanbul Universiteti Istanbul Tibb Fakültəsi, Endokrinologiya və Metabolizma Xəstəlikləri Uzmanliq Təhsili | Türkiye Endokrinoloji ve Metabolizma Derneği (TEMD) | Endocrine Society', 16, NULL, '/doctor-photos/dr-vefa-nesifova.webp', 'az', 'UNCLAIMED', 'livhospital.az', 0, 1, NOW(), NOW());

-- Attach them to the hospital, as V22 did for the first seventy.
INSERT INTO doctor_clinic (doctor_id, clinic_id)
SELECT d.id, @clinic_id FROM doctor d
WHERE d.source = 'livhospital.az'
  AND @clinic_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM doctor_clinic dc
      WHERE dc.doctor_id = d.id AND dc.clinic_id = @clinic_id);
