-- The 102 doctors Yeni Klinika publishes, as 101 new listings and one
-- addition to a doctor already here.
--
-- Read from yeniklinika.gov.az on 2026-09-19, in Azerbaijani. The seventh
-- source, and a state hospital rather than a private one.
--
-- The count is 102 and two readings agree. The directory page renders all 102
-- at once, which is easy to mistake for a slice because it also carries
-- data-lastpage="9" and a "Daha cox" button; requesting its nine ajax pages,
-- which need an X-Requested-With header or the server returns the whole page
-- again, gives 12 each and 6 on the last, and the union is exactly the same
-- 102 profiles. Neither list holds anything the other does not.
--
-- None of these doctors asked to be here. Every row is UNCLAIMED with
-- accepts_bookings = 0.
--
-- One of them is already in this directory. Turan Mammadaliyev is listed from
-- referansclc.com at Referans Merdekan Hospital: same specialty, same
-- university, same years - Qazi Universiteti 2011-2017 on both. He is one
-- doctor who works in two hospitals, so he gets a second clinic rather than a
-- second listing, which is the whole reason doctor_clinic is a join table.
--
-- Three other names already existed and are not the same people. Lale Aliyeva
-- here is an anaesthetist who qualified in 1996; the Lale Aliyeva at Merkezi
-- Klinika is a neurologist. Tural Mammadov here is an invasive cardiologist;
-- the one at Referans is a gastroenterologist. Their slugs are suffixed so
-- INSERT IGNORE cannot quietly drop them.
--
-- Two names repeat inside this hospital and are also two people each. Both
-- Nigar Bayramovas qualified in 2008-2014, but one is a paediatrician and the
-- other a radiologist, with different photographs. The two Sabina Tagiyevas
-- trained a decade apart, one at ATU and one at Hacettepe. Where a name
-- repeats, the photograph and the specialty both have to agree before the
-- pages are treated as one person.
--
-- The centres on this site - Cerrahiyye ve Transplantasiya, Somatika ve
-- STROK, Urek-Damar and the rest - are departments inside one building, not
-- separate addresses, so there is one clinic row.
--
-- Every doctor states their education, and 101 of them have a portrait at
-- 800x1200, the largest any source has offered. Their host answers an A record
-- but will not resolve through the system resolver, so the fetch has to pin
-- the address.
--
-- Data only.

-- Speech and language therapy: a logoped is who a parent is sent to when a
-- child is not speaking, and nothing in the taxonomy covered it.
INSERT IGNORE INTO specialty (code, name_az, name_en, name_ru, patient_facing, ai_specialty_code, sort_order) VALUES
('speech-therapy','Loqopediya','Speech and Language Therapy','Логопедия',1,'general',118);

INSERT INTO clinic (name, slug, address, city, phone, description, active, created_at, updated_at)
SELECT * FROM (SELECT
    'Yeni Klinika' AS name, 'yeni-klinika' AS slug,
    'Heydər Əliyev prospekti 142, Bakı' AS address, 'Bakı' AS city,
    '+994 12 505 62 31' AS phone,
    'Yeni Klinika, Bakı. Siyahı klinikanın yeniklinika.gov.az saytındakı həkim kataloqu əsasında hazırlanıb.' AS description,
    1 AS active, NOW() AS created_at, NOW() AS updated_at) AS c
WHERE NOT EXISTS (SELECT 1 FROM clinic WHERE slug = 'yeni-klinika');

-- INSERT IGNORE, not ON DUPLICATE KEY: MariaDB on production does not take
-- the row-alias form, and a slug that somehow already exists should be left
-- alone rather than overwritten by a scrape.
INSERT IGNORE INTO doctor
    (full_name, slug, specialty_code, qualifications, years_experience, bio,
     photo_url, languages, verification, source, accepts_bookings, active, created_at, updated_at)
VALUES
    ('Aytac Quliyeva', 'aytac-quliyeva', 'psychology', NULL, NULL, 'Psixoloq. Şöbə: Somatika və STROK Mərkəzi.', '/doctor-photos/aytac-quliyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Ahdab Əzim', 'dr-ahdab-ezim', 'obstetrics-gynecology', NULL, NULL, 'Mama-ginekoloq. Şöbə: Mamalıq və Ginekologiya. İş təcrübəsi: 2012 - İstanbul Çapa Xəstəxanası: Ginekologiya üzrə təcrübə; 2013 - Vyanada - AKHA xəstəxanasında laparoskopik ginekologiya üzrə təcrübə (Avstriya); 2022 - Birləşmiş Ərəb Əmirlikləri: "Visitor lecture"; Azərbaycan Tibb Universiteti və Birləşmiş Ərəb Əmirliklərinin "Ras Al-Khaimah" Tibb Kolleci arasında olan tələbə mübadilə proqramının təşkilatçısı.', '/doctor-photos/dr-ahdab-ezim.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Almaz Əliyeva', 'dr-almaz-eliyeva', 'emergency-medicine', '2017-2023 - İ.M.Seçenov adına Birinci Moskva Dövlət Tibb Universitetinin Bakı filialı: Müalicə işi fakültəsi.', 3, 'Təcili və təxirəsalınmaz tibbi yardım üzrə həkim. Şöbə: Təcili və Təxirəsalınmaz Tibbi Yardım. İş təcrübəsi: 09/2019-10/2019 - Mərkəzi Klinika; 2019-2023 - 1 saylı Kliniki Tibbi Mərkəz; 2020-2023 - Bakı Sağlamlıq Mərkəzi; 2021-2023 - Mərkəzi Klinika; 04/2021 - Avrasiya Hospital; 10/2021 - 6 saylı Uşaq Kliniki Xəstəxanası; 2022 - K. Fərəcova adına Elmi-Tədqiqat Pediatriya İnstitutu - OMD; 06/2022 - Elmi-Tədqiqat Mamalıq və Ginekologiya İnstitutu; 07/2022 - Şamama Ələsgərova adına 5 nömrəli Kliniki Doğum Evi; 12/2022 - Zəfəran Hospital; 12/2022-01/2023 - Respublika Perinatal Mərkəz; 03/2023 - MəhkəməTibbi Ekspertiza və Patoloji Anatomiya Birliyi; 04/2023 - Milli Onkologiya Mərkəzi..', '/doctor-photos/dr-almaz-eliyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Aygül Daşdəmir', 'dr-aygul-dasdemir', 'internal-medicine', '2006-2012 - Azərbaycan Tibb Universiteti: Bakalavr - müalicə işi fakültəsi | 2017-2021 - Qazi Universiteti, tibb fakültəsi: Rezidentura - daxili xəstəliklər', 14, 'Terapevt. Şöbə: Terapiya. Müalicə etdiyi xəstəliklər: Endokrin xəstəliklər (qalxanabənzər vəzi, diabet); Yüksək təzyiq (arterial hipertenziya); Lipid mübadilə pozğunluğu; Qan azlığı (anemiya); Vitamin və mineral əskiklikləri; Mədə-bağırsaq sistemi xəstəlikləri; Tənəffüs sistemi xəstəlikləri.', '/doctor-photos/dr-aygul-dasdemir.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Aygül Qurbanova', 'dr-aygul-qurbanova', 'emergency-medicine', '2009-2015 - Azərbaycan Tibb Universiteti: Pediatriya fakültəsi.', 11, 'Təcili və təxirəsalınmaz tibbi yardım (uşaq) üzrə həkim. Şöbə: Təcili və Təxirəsalınmaz Tibbi Yardım. İş təcrübəsi: 2016 2017 - Gəncə şəhər 3 nömrəli Uşaq Poliklinikası: Sahə pediatrı; 2022 - Dövlət Həkimləri təkmilləşdirmə İnstitutu: İxtisas üzrə kurs; 2023 - Yeni Klinika: Təcili tibbi yardım (uşaq) üzrə həkim.. Kurslar: Basic life support; Advanced life support; Pediatric advanced life support; Neonatal Reanimasiya Proqramı - NRP..', '/doctor-photos/dr-aygul-qurbanova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Aynur Hacıyeva', 'dr-aynur-haciyeva', 'radiology', '1988-1994 - Azərbaycan Tibb Universiteti: Bakalavr - Müalicə-profilaktika | Elmi-Tədqiqat Kardiologiya İnstitutu: İnternatura.', 32, 'Radioloq. Şöbə: Radiologiya. İş təcrübəsi: 2001 - Türkiyə Yüksək İxtisas Xəstəxanası; 2001-2010 - Mərkəzi Klinik Xəstəxana: Radioloq; 2009 - İstanbul Capa Xəstəxanası; 2013-2016 - Mərkəzi Hərbi Hospital: Radioloq; 2018-2023 - Mərkəzi Klinik Xəstəxana: Radioloq; 2018 - Marmara Universiteti; 2023 - Yeni Klinika: Radioloq..', '/doctor-photos/dr-aynur-haciyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Aynur Hüseynova', 'dr-aynur-huseynova', 'radiology', '2003-2009 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2009-2010 - Azərbaycan Tibb Universitetinin Onkoloji Klinikası: Şüa-diaqnostika fakültəsi - İnternatura.', 17, 'Radioloq. Şöbə: Radiologiya.', '/doctor-photos/dr-aynur-huseynova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Aynur İsmayılova', 'dr-aynur-ismayilova', 'pediatrics', NULL, NULL, 'Uzman pediatr. Şöbə: Reproduktiv Sağlamlıq və Ailə Planlaması Mərkəzi.', '/doctor-photos/dr-aynur-ismayilova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Aysel Ağalarova', 'dr-aysel-agalarova', 'rheumatology', NULL, NULL, 'Revmatoloq. Şöbə: Terapiya.', '/doctor-photos/dr-aysel-agalarova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Aysel Əhmədova', 'dr-aysel-ehmedova', 'anesthesiology', NULL, NULL, 'Anestezioloq-reanimatoloq. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi.', '/doctor-photos/dr-aysel-ehmedova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Aysel Həsənova', 'dr-aysel-hesenova', 'emergency-medicine', '2017-2023 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi.', 3, 'Təcili və təxirəsalınmaz tibbi yardım üzrə həkim. Şöbə: Təcili və Təxirəsalınmaz Tibbi Yardım. İş təcrübəsi: 2020-2021 - Gəncə Beynəlxalq Xəstəxanası, Kardiologiya şöbəsi: Həkim asistenti; 2022 - Tədris Cərrahiyyə Xəstəxanası, Reanimasiya şöbəsi: Tibb bacısı; 2023 - Kliniki Tibbi Mərkəz, Cərrahi Reanimasiya: Tibb bacısı.. Kurslar: EKQ,CPR..', '/doctor-photos/dr-aysel-hesenova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Ayşən Xanlarlı', 'dr-aysen-xanlarli', 'anesthesiology', NULL, NULL, 'Anestezioloq-reanimatoloq. Şöbə: Reanimasiya.', '/doctor-photos/dr-aysen-xanlarli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Azad Süleymanov', 'dr-azad-suleymanov', 'urology', '2000-2007 - Xoca Əhməd Yasəvi adına Beynəlxalq Qazax-Türk Universiteti: Tibb fakültəsi | 2007-2008 - Azərbaycan Tibb Universiteti: İnternatura - Cərrahiyyə | 2015-2018 - Azərbaycan Tibb Universiteti: Doktorantura - Urologiya', 19, 'Uroloq. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. Müalicə etdiyi xəstəliklər: Böyrək, sidik axarı, sidik kisəsi daşlarının əməliyyatı (açıq və endoskopik); Böyrək əməliyyatları (açıq və qapalı); Skrotal cərrahiyyə; Kişi sonsuzluğu; Prostat vəzin hiperplaziyası (müalicə və cərrahiyyəsi); Perkutan nefrolitotomiya (PCNL).. Üzvlük: Azərbaycan Reproduktiv Təbabət Assosiasiyası; Türkiyə Urologiya Dərnəyi..', '/doctor-photos/dr-azad-suleymanov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Azər Məmmədov', 'dr-azer-memmedov', 'radiology', 'Azərbaycan Tibb Universiteti: Hərbi Tibb fakültəsi, Hərbi-həkim işi | Azərbaycan Tibb Universiteti: Hərbi Tibb fakültəsi, Şüa diaqnostikası | 2014-2019 - Silahlı Qüvvələrin Baş Klinik Hospitalı - Rezidentura təhsili | 2014-2019 - Milli Onkologiya Mərkəzi, Tədris Terapevtik Klinikası, Mərkəzi Klinika - Rezidentura təhsili.', 7, 'Radioloq. Şöbə: Radiologiya. İş təcrübəsi: 2013-2014 - N saylı hərbi hissə - Hərbi hissənin tibb məntəqə rəisi; 2014-2019 - Silahlı Qüvvələrin Baş Klinik Hospitalı; 2014-2019 - Tədris Cərrahiyyə klinikası, Milli onkologiya mərkəzi - Rezidentura təhsili; 2019-2024 - Naxçıvan Qarnizonu Mərkəzi Hospitalı - Radiologiya şöbəsinin baş ordinatoru (Son 4 ildə şöbə rəsinin vəzifəsini icra edib).. Kurslar: 2015 - Türkiyə Respublikası Ankara şəhəri Gülhanə Hərbi Tibb Akademiyası - Radiologiya kursu; 2018 - Türkiyə Respublikası Ankara şəhəri Gülhanə Hərbi Tibb Akademiyası - Radiologiya kursu..', '/doctor-photos/dr-azer-memmedov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr.Cəmilə Əhmədova', 'dr-cemile-ehmedova', 'neonatology', '2005-2011 - Azərbaycan Tibb Universiteti, Pediatriya fakültəsi | 2012-2017 K.Y.Fərəcova adına Elmi-Tədqiqat Pediatriya İnstitutu: Pediatr ixtisası üzrə rezidentura.', 15, 'Neonatoloq. Şöbə: Neonatologiya. İş təcrübəsi: 2017-2022 - 26 saylı Birləşmiş Şəhər Xəstəxanası/Xəzər Tibb Mərkəzi: Doğum şöbəsində Neonatoloq; 2020-2023 - K.Y.Fərəcova adına Elmi-Tədqiqat Pediatriya İnstitutu: Reanimatologiya-anesteziologiya şöbəsi, Həkim-reanimatoloq, Elmi bölmə üzrə kiçik elmi işçi; 2023 cü ildən - Yeni Klinika: Neonatoloq..', '/doctor-photos/dr-cemile-ehmedova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Coşqun Piriyev', 'dr-cosqun-piriyev', 'home-care', '2017-2023 - Azərbaycan Tibb Universiteti: Müalicə və profilaktika fakültəsi | 2022 - "Romed Klinikum Wasservurg am Inn" Almaniya Damar cərrahiyyəsi şöbəsi | 2024 - Almaniya, "Anna-Hospital Herne" - Travmatologiya şöbəsi.', 3, 'Evdə tibbi xidmət üzrə həkim. Şöbə: Evdə Tibbi Xidmət. İş təcrübəsi: 2020-2023 - Yeni Klinika: Anesteziologiya-reanimasiya şöbəsi; 2023-2024 - Yeni Klinika: Təcili və təxirəsalınmaz tibbi yardım şöbəsi; 2024 - Yeni Klinika: Evdə tibbi xidmət şöbəsi..', '/doctor-photos/dr-cosqun-piriyev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Əkbər Quliyev', 'dr-ekber-quliyev', 'neonatology', '2000-2006 - Azərbaycan Tibb Universiteti - Həkim pediatr | 2007 - Gəncə şəhəri 2 № Uşaq Xəstəxanası - İnternatura | 2008-2010 - Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutu - Pediatriya üzrə ordinatura | 2018 - Sağlık Bilimleri Universitesi Kanuni Sultan Suleyman Eğitim Ve Araştırma Hastanesi - Uzman Doktor.', 20, 'Uzman neonatoloq-pediatr. Şöbə: Neonatologiya. Müalicə etdiyi xəstəliklər: Sağlam uşaq izlənməsi, böyümə və inkişaf dəyərləndirilməsi; Qidalanma; Anemiyalar; Mədə-bağırsaq sistemi xəstəlikləri; Tənəffüs sistemi xəstəlikləri; Allergik xəstəliklər; Sidik-ifrazat sistemi xəstəlikləri; İnfeksiyon xəstəliklər; Yenidoğulmuşların aylıq rutin müayinələri.. İş təcrübəsi: 2009 -2015 - Gəncə şəhəri 1 saylı Uşaq Poliklinikası: Həkim pediatr; 2019-2020 - Leyla Medical Centre: Pediatriya və Neontalogiya şöbəsinin müdiri; 2020 - Respublika Diaqnostika Mərkəzi - Pediatriya və neontalogiya şöbəsinin müdiri; 2023 - Yeni Klinika: Neonatologiya şöbəsinin müdiri..', '/doctor-photos/dr-ekber-quliyev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Elçin Əlizadə', 'dr-elcin-elizade', 'general-surgery', '2008-2014 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2016-2021 - İstanbul Universiteti Tibb fakültəsi: Ümumi Cərrahiyyə ixtisası üzrə uzmanlıq təhsili.', 12, 'Ümumi Cərrahiyyə Uzmanı. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İcra etdiyi əməliyyatlar: Onkoloji xəstəliklərin açıq və qapalı üsullarla cərrahi əməliyyatları; Mədə-bağırsaq xəstəliklərinin laparoskopik və açıq üsullarla əməliyyatları; Qalxanabənzər və qalxanabənzərətrafı vəzilərin cərrahiyyəsi; Süd vəzi cərrahiyyəsi; Qaraciyər, öd yolları və mədəaltı vəzi cərrahiyyəsi.. Kurslar: Təməl cərrahiyyə kursu; Damar cərrahiyyəsi kursu; Differensial tiroid xərçəngində cərrahi genişlik və boyun metastazlarının gedişinə yanaşma; Cərrahlar üçün Tiroid Ultrasonoqrafiyası Təlim Kursu; Kolorektal xərçənglərdə cari yanaşma kursu; Aşağı ətrafların fasiotomiyası - simulyasiya kursu..', '/doctor-photos/dr-elcin-elizade.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr.Elgin Hacızadə', 'dr-elgin-hacizade', 'cardiovascular-surgery', '2008-2014 - Azərbaycan Dövlət Tibb Universiteti: Hərbi Tibb Fakultəsi | 2018-2023- Gülhane Eğitim ve Araştırma Hastanesi: Ürək-damar cərrahiyyəsi üzrə uzmanlıq təhsili.', 12, 'Ürək-Damar Cərrahiyyəsi Uzmanı. Şöbə: Ürək-Damar Mərkəzi. İcra etdiyi əməliyyatlar: Aorta-koronar şuntlama; Minimal invaziv (kiçik kəsiklər ilə) aorta koronar șuntlama əməliyyatları; Minimal invaziv (kiçik kəsiklər ilə) ürək qapağı əməliyyatları; Döyünən ürəkdə (ürəyi dayandırmadan) icra edilən aorta-koronar șuntlama əməliyyatları; Aorta qapaq əməliyyatları (dəyişdirilməsi və təmiri); Aort qapağın Neoküspidizasiyası (Ozaki əməliyyatı); Mitral qapaq əməliyyatları (dəyişdirilməsi və təmiri); Triküspit qapaq əməliyyatları (dəyişdirilməsi və təmiri); Qulaqcıqlar arası çəpər defekti təmiri əməliyyatı; Çıxan aortanın anevrizma əməliyyatları; Qarın aortasının anevrizma əməliyyatları; Yuxu arteriyası əməliyyatı; Periferik arteriyaların əməliyyatları; Arteriovenoz fistula açılması əməliyyatı; Aorta anevrizması - diseksiyon əməliyyatları.. İş təcrübəsi: 2022 - Aorta qapağı təmiri kursu - Fellowship (Almanya, Saarland University, Hamburg); 2023 - Ürək transplantasiyası və Assist device cərrahiyyəsi - Fellowship (Türkiyə, Ankara Şehir Hastanesi, Ürək çatışmazlığı cərrahiyyəsi şöbəsi)..', '/doctor-photos/dr-elgin-hacizade.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Ellada Nağıyeva', 'dr-ellada-nagiyeva', 'pediatrics', '2003-2009 - Azərbaycan Tibb Universiteti: Pediatriya fakültəsi | 2009-2010 - Abşeron rayonu Mərkəzi Xəstəxanası: internatura | 2011-2016 Azərbaycan Tibb Universiteti Tədris Terapevtik Klinika: Pediatriya üzrə rezidentura.', 17, 'Həkim-pediatr. Şöbə: Reproduktiv Sağlamlıq və Ailə Planlaması Mərkəzi. İş təcrübəsi: 2020 PALS Pediatric Advanced Life Support Baku 2021 Həkimləri Təkmilləşdirmə İnstitutu; 2018- 2021 Euromed- həkim pediatr; 2021-2023 Kəpəz hospital- həkim pediatr; 2023-2024 10 saylı uşaq poliklinikası- həkim-pediatr..', '/doctor-photos/dr-ellada-nagiyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Elnur Ziyadov', 'dr-elnur-ziyadov', 'urology', '2006-2012- Azərbaycan Tibb Universiteti: Müalicə işi | 2012-2015 - Akademik M.Cavadzadə adına RKUX: Rezidentura təhsili | 2015-2020 - Çukurova Univerisiteti - Uzmanlıq təhsili', 14, 'Uzman uroloq-androloq. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. Müalicə etdiyi xəstəliklər: Sidik yolları infeksiyaları (pielonefrit, sistit, uretrit); Polikistik böyrək və böyrəyin digər kistik xəstəlikləri; Böyrək daşı müalicəsi: (Böyrək daşı, sidik axarı daşları və sidik kisəsi daşlarının cərrahi və dərman müalicəsi); Hematuriya (sidikdə qan); Kişilərdə sidiyə çıxma problemləri və prostat vəzi xəstəlikləri; Qadınlarda sidik qaçırma problemləri (dərman və cərrahi müalicəsi); Kişi sonsuzluğu, varikosele və digər androloji xəstəliklər; Böyrəküstü vəzi xəstəlikləri (adenoma, kista); Uşaqlarda uroloji xəstəliklər (sidik çıxarıcı yollarda anadan gəlmə anomaliyalar, enməmiş xaya, varikosele)..', '/doctor-photos/dr-elnur-ziyadov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Elşən Nəcəfov', 'dr-elsen-necefov', 'orthopedics', NULL, NULL, 'Uzman travmatoloq-ortoped. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi.', '/doctor-photos/dr-elsen-necefov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Elşən Qədimov', 'dr-elsen-qedimov', 'general-surgery', '1999-2005 - Azərbaycan Tibb Universiteti: Müalicə işi faküləsini fərqlənmə diplomu ilə bitirib. | 2005-2008 - Rusiya Federasiyasında ümumi cərrahiyyə ixtisası üzrə klinik ordinatura təhsili.', 21, 'Ümumi cərrahiyyə şöbəsinin müdiri. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İcra etdiyi əməliyyatlar: Ümumi cərrahi əməliyyatlar; Paralel olaraq Laparoskopik, Varikoz, Tiroidektomiya və qarın boşluğuna dair əməliyyatlar; Bura daxildir: öd, mədə ,bağırsaq, qara ciyər və dalaq əməliyyatları..', '/doctor-photos/dr-elsen-qedimov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Elvin Əliyev', 'dr-elvin-eliyev', 'gastroenterology', '2009-2014 - Naxçıvan Dövlət Universiteti: Tibb fakültəsi', 12, 'Qastroenterologiya şöbəsinin müdiri. Şöbə: Qastroenterologiya.', '/doctor-photos/dr-elvin-eliyev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Elvin Tanrıverdi', 'dr-elvin-tanriverdi', 'general-surgery', '2001 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2003-2009 - İstanbul Universiteti,İstanbul Tibb Fakültəsi: Həkim | 2009-2024 - Muğla Sıtkı Koçman Universiteti, Tibb Fakültəsi Xəstəxanası, Ümumi Cərrahiyə Kafedrası - Həkim ümumi cərrah', 25, 'Uzman ümumi cərrah. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İcra etdiyi əməliyyatlar: Açıq və qapalı (laparoskopik) cərrahi əməliyyatlar. İş təcrübəsi: Son iş yeri - Bakı Sağlamlıq Mərkəzi, Həkim ümumi cərrah - 2024-2025.', '/doctor-photos/dr-elvin-tanriverdi.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Elvira Babaşova', 'dr-elvira-babasova', 'cardiology', NULL, NULL, 'İnvaziv-kardioloq. Şöbə: Ürək-Damar Mərkəzi. Müalicə etdiyi xəstəliklər: Ürəyin işemik xəstəliyi; Miokard infarktı; Stenokardiya; Arterial hipertenziya; Hiperlipidemiyalar; Ürək çatışmazlığı; Kardiomiopatiyalar; Aritmiyalar; Qapaq xəstəlikləri; Ürək qüsurlarının diaqnostikası.. Üzvlük: Azərbaycan Kardiologiya Cəmiyyəti (AKC); Avropa Kardiologiya Cəmiyyəti (ESC); Amerika Kardiologiya Cəmiyyəti (AHA); Türkiyə Kardiologiya Cəmiyyəti (TKD)..', '/doctor-photos/dr-elvira-babasova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Emil Qasımov', 'dr-emil-qasimov', 'anesthesiology', NULL, NULL, 'Reanimasiya və anesteziologiya şöbəsinin müdiri. Şöbə: Reanimasiya.', '/doctor-photos/dr-emil-qasimov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Emin Nəsirov', 'dr-emin-nesirov', 'neurology', '2003-2009 - Azərbaycan Tibb Universiteti: II Müalicə Profilaktika fakültəsi | 2009-2011 - Ukrayna/Kiyev - Şupik adına Milli Tibbi Akademiyanın Nəzdində Kiyev Əyalət Klinik Xəstəxanası: Nevrologiya üzrə kliniki ordinatura | 2015-2017 - Türkiyə/İstanbul - "Bezmialem Vakıf Üniversitesi" Tibb Fakültəsi Xəstəxanası: Nevrologiya üzrə ixtisasartırma kursu | 2017 fevral-iyul - İstanbul Universiteti - İstanbul Tibb Fakültəsi Xəstəxanası: Epilepsiya və Elektroneyrofiziologiya şöbəsində kurs.', 17, 'Nevroloq. Şöbə: Nevrologiya. Müalicə etdiyi xəstəliklər: İşemik ve hemorargik insult; Beynin vaskulyar xəstəlikləri; Periferik sinir sistemi xəstəlikləri; Baş ağrıları; Parkinson və hərəkət pozğunluğu xəstəliyi; Epilepsiya; Baş dönməsi, vertigo..', '/doctor-photos/dr-emin-nesirov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Fariz Hüseynov', 'dr-fariz-huseynov', 'general-surgery', NULL, NULL, 'Ümumi cərrahiyyə uzmanı. Şöbə: Ümumi Cərrahiyyə.', '/doctor-photos/dr-fariz-huseynov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Fatimə Qafarova', 'dr-fatime-qafarova', 'pediatrics', '2010-2016 - Azərbaycan Dövlət Tibb Universiteti: Pediatriya fakültəsi | 2016-2020 - Ə.Əliyev adına Həkimləri Təkmilləşdirmə İnstitutu, Pediatriya fakültəsi: Rezidentura.', 10, 'Pediatr. Şöbə: Pediatriya. İş təcrübəsi: 2021-2023 - 17 saylı Şəhər Poliklinikası: Həkim-pediatr..', '/doctor-photos/dr-fatime-qafarova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Fatma Məmmədli', 'dr-fatma-memmedli', 'dermatology', NULL, NULL, 'Dermatoveneroloq. Şöbə: Terapiya. Müalicə etdiyi xəstəliklər: Ekzemalar; Psoriaz (pullu dəmrov); Sızanaqlar (akne və rozasea); Dərinin bakterial xəstəlikləri; Dərinin göbələk xəstəlikləri; Dərinin virus xəstəlikləri; Piqment xəstəlikləri; Müxtəlif tipli saç tökülmələri; Seboreya; Qırmızı-yastı, çəhrayı, əlvan dəmrov; Dırnaq xəstəlikləri və s..', '/doctor-photos/dr-fatma-memmedli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Fəxriyyə Quliyeva', 'dr-fexriyye-quliyeva', 'emergency-medicine', '2008-2014 Azərbaycan Tibb Universiteti: Bakalavr - Müalicə işi fakültəsi | 2014-2019 - Bakı Sağlamlıq Mərkəzi: Terapiya ixtisası üzrə rezidentura təhsili | 2022 - Dokuz Eylül Üniversitesi, Tıp Fakültesi Hastanesi, Acil Tıp Anabilim Dalı: Klinik təcrübə | 2022 - "Uluslararası Medikal Kurtarma Ekibi Temel Eğitimi" - Türkiyə, İzmir | 2023 - Kocaeli Üniversitesi, Tıp Fakultesi Hastanesi, Acil Tıp Anabilim Dalı: Klinik təcrübə', 12, 'Təcili və təxirəsalınmaz tibbi yardım şöbəsinin müdiri. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi.', '/doctor-photos/dr-fexriyye-quliyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Fidan Ələsgərova', 'dr-fidan-elesgerova', 'hematology', '2011-2017 - Azərbaycan Tibb Universiteti- Müalicə işi fakültəsi | 2018-2022 - Azərbaycan Tibb Universiteti Tədris Terapevtik Klinika: Hematologiya şöbəsi - Rezidentura', 9, 'Hematoloq. Şöbə: Hematologiya. Müalicə etdiyi xəstəliklər: Anemiyalar; Polisitemiya; Trombositopeniya; Limfomalar; Çoxsaylı Mieloma; Leykemiya.. İş təcrübəsi: Milli Hematologiya və Transfuziologiya Mərkəzi; 2021 - TC İzmir Ege Üniversitesi Tıp Fakültesi Hastanesi: Hematoloji Bilim Dalı - 3aylıq təcrübə; 2022 TC Erciyes Üniversitesi Tıp Fakültesi Hastanesi: Erciyes Transplant Merkezi - 5 aylıq təcrübə.', '/doctor-photos/dr-fidan-elesgerova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Firdovsi Fərhadzadə', 'dr-firdovsi-ferhadzade', 'thoracic-surgery', NULL, NULL, 'Torakal cərrahiyyə uzmanı. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi.', '/doctor-photos/dr-firdovsi-ferhadzade.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Göyçək Məmmədli', 'dr-goycek-memmedli', 'pediatric-intensive-care', NULL, NULL, 'Reanimatoloq. Şöbə: Uşaq Reanimasiya.', '/doctor-photos/dr-goycek-memmedli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Gülay Məmmədova', 'dr-gulay-memmedova', 'cardiology', NULL, NULL, 'İnvaziv-kardioloq. Şöbə: Kardiologiya.', '/doctor-photos/dr-gulay-memmedova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Gülnar Abdullayeva', 'dr-gulnar-abdullayeva', 'neurology', '2004-2010 - Odlar Yurdu Universiteti: Müalicə işi fakültəsi | 2010 -2011 - Azərsutikinti Xəstəxanası: Terapiya ixtisası üzrə internatura | 2017 - Nutrisiologiya ve dietologiyanın əsasları kursu (ANDOP) | 2018 - Yeni Yüzyıl Üniversitesi, Gaziosmanpaşa Hastanesi: Qidalanma və dietologiya şöbəsi: Təcrübəçi həkim (İstanbul) | 2021-2022 - Topkapı Üniversitesi: Bütüncül Sağlık Uzmanlığı kursu (İstanbul)', 16, 'Dietoloq. Şöbə: Somatika və STROK Mərkəzi. İş təcrübəsi: 2006-2009- A.F. Qarayev adına 2 saylı Uşaq Klinik Xəstəxanası: Kiçik tibb işçisi; 2009-2010-Akademik Zərifə Əliyeva adına Milli Oftalmologiya Mərkəzi: Pəhriz tibb bacısı; 2016-2021- Müharibə Veteranları Respublika Xəstəxanası: Həkim-dietoloq.', '/doctor-photos/dr-gulnar-abdullayeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Gülxar Süleymanova', 'dr-gulxar-suleymanova', 'neurology', NULL, NULL, 'Uzman terapevt. Şöbə: Somatika və STROK Mərkəzi. Müalicə etdiyi xəstəliklər: Hipertenziya; Hiperlipidemiya; Tiroid (qalxanabənzər vəzi) xəstəlikləri; Şəkərli diabet; Osteoporoz; Bronxial astma; Xroniki obstruktiv ağciyər xəstəliyi; Anemiyalar; Revmatoid artrit; Qaraciyər xəstəlikləri.. İş təcrübəsi: 2021-2023 - Respublika Diaqnostika Mərkəzi: Həkim-terapevt; 2023 - Yeni Klinika: Həkim-terapevt..', '/doctor-photos/dr-gulxar-suleymanova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Günay Allahverdiyeva', 'dr-gunay-allahverdiyeva', 'general-surgery', '2006-2012: Azərbaycan Tibb Universiteti - Müalicə-profilaktika II fakültəsi | 2013-2018: Mərkəzi Neftçilər Xəstəxanası "Cərrahiyyə və orqan transplantasiyası" mərkəzində rezidentura təhsili.', 14, 'ümumi cərrah, transplantoloq. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İcra etdiyi əməliyyatlar: Qaraciyər və böyrək transplantasiyası; Qaraciyər və öd yolları əməliyyatları(xoş və bədxassəli şişlər, kistlərin rezeksiyası); Mədəaltı vəzi əməliyyatları; Dalaq əməliyyatları; Böyrəküstü vəzi əməliyyatları; Mədə və bağırsaq əməliyyatları; Öd kisəsi əməliyyatı; Qarın boşluğu yırtıqları.. İş təcrübəsi: 2018-2023 "Bona dea İnternational hospital" ümumi və transplantasiya cərrahı; 2023-cü ildən Yeni klinikada ümumi və transplantasiya cərrahı.. Kurslar: Ondokuzmayis Üniversitesi Tıp Fakültesi Hastanesi Genel Cerrahi Anabilim Dalında staj 23.07.2010-20.08.2010; Koç University Hospital , Organ Transplantation Clinical Observership Program between 01 October-01 November 2019; International Visiting Scholars Training Program at the Division of Liver Transplantation and Hepatobiliary Surgery at Asan Medical Center, Seoul, South Korea, from October 11,2022 to November 11,2022.; 5th Congress of International Advanced HBP Surgery October 18 (Wed) - 21 (Sat), 2023 at Kongresshaus Zurich, Switzerland.; 2024-completed Belt and Road İnitiative Liver Minimally İnvasive Technology İnternational Training Course. March 31.2024-April 20.2024 at West China Hospital of Sichuan University. Laparoscopic training course January 25th to 29th 2025 World; Laparoscopy Training Institute Dubai Healthcare City, Dubai, UAE; Fellowship in minimal access surgery on Wednesday 29th January 2025 at Clinical Surgical Training Center, University of Sharjah ,UAE.; MEMBERSHIP of WORLD ASSOCIATION OF LAPAROSCOPIC SURGEONS since 29.01.2025 lifetime.', '/doctor-photos/dr-gunay-allahverdiyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Günel Əsgərova', 'dr-gunel-esgerova', 'radiology', NULL, NULL, 'Revmatoloq. Şöbə: Radiologiya.', '/doctor-photos/dr-gunel-esgerova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Günel Rzazadə', 'dr-gunel-rzazade', 'radiology', '2010-2016 - Azərbaycan Tibb Universiteti: Müalicə-profilaktika fakültəsi | 2016-2020 - Azərbaycan Tibb Universiteti, Tədris Cərrahiyyə Klinikası: Şüa-diaqnostikası ixtisası üzrə rezidentura | 2019 - Ege Universiteti Tibb fakültəsi Xəstəxanası: Radiologiya üzrə təcrübə | 2020-2021 - Mərkəzi Klinika: Rezidentura', 10, 'Radioloq. Şöbə: Radiologiya. İş təcrübəsi: 2022 - Yeni Klinika, Radiologiya şöbəsi: Həkim-radioloq..', '/doctor-photos/dr-gunel-rzazade.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Həmzət Cigərov', 'dr-hemzet-cigerov', 'urology', '2005-2011 - Azərbaycan Tibb Universiteti | 2012-2018 - "Klinikum Wilhelmshaven": Uzmanlıq təhsili (facharzt).', 15, 'Uroloq. Şöbə: Urologiya. İcra etdiyi əməliyyatlar: Nefrektomiya - böyrəyin çıxarılması (açıq və laparoskopik - qapalı); Parsial nefrektomiya (böyrəyin hissəvi rezeksiyası); Pieloplastika - böyrək ləyəni daralmasının ləğvi (açıq və qapalı); Pielolitotomiya - böyrək ləyəni daşının çıxarılması (açıq və qapalı); Perkutan nefrolitotriosiya - PNL (qapalı böyrək daşı çərrahiyyəsi); Böyrək kistası rezeksiyası (açıq və qapalı); Sidik axarı daşı əməliyyatları (açıq və qapalı); Sidik kisəsinin daş və ya törəməyə görə açıq və qapalı (TUR) əməliyyatları; Radikal sistektomiya (sidik kisəsinin tamının çıxarılması) və yeni sidik yollarının yaradılması; Prostat vəzinin açıq və qapalı (TUR) əməliyyatları; Radikal prostatektomiya (prostat şişinə görə prostat vəzinin tamının çıxarılması); Sidik kanalının açıq və qapalı (endoskopik) əməliyyatları; Varikoselektomiya (genişlənmiş xaya damarlarının ləğvi); Xaya və xayalıq əməliyyatları; Cinsi alət (penis) üzərində və digər androloji əməliyyatlar; Qadınlarda sidik qaçırmasına görə asqı (TOT) əməliyyatı; Qadınlarda sidik kisəsi sallanması (sistosel) təmiri; Qadınlarda sidik kanalı ağzının polipinin (karunkul) kəsilməsi. İş təcrübəsi: 2018-2020 - Uniklinik Minden: Uzman həkim; 2020-2022 - Lohne Hospital: Şöbə müdiri (Oberarzt).', '/doctor-photos/dr-hemzet-cigerov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr.Hilal Budaqova', 'dr-hilal-budaqova', 'neonatology', '2003-2009 - Azərbaycan Tibb Universiteti: Pediatriya fakültəsi | 2009-2010 - K.Y. Fərəcova adına Elmi-Tədqiqat Pediatriya İnstitutun( ETPİ ): İnternatura', 17, 'Neonatoloq. Şöbə: Neonatologiya. İş təcrübəsi: 2011-2017 - Bakı şəhəri Təcili və Təxirəsalınmaz Tibbi Yardım Stansiyasının 6 saylı Bölməsi; 2017 -2021 - Azərbaycan Respublikası Silahlı Qüvvələrinin Baş Klinik Hospital; 2019-2025 - Baku Medical Plaza Medilux filialı; 2023 - Yeni Klinika..', '/doctor-photos/dr-hilal-budaqova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Humay Rzayeva', 'dr-humay-rzayeva', 'radiology', '2011-2017 - Azərbaycan Tibb Universiteti: Müalicə-profilaktika fakültəsi | 2017 ci il rezidentura imtahanı üzrə Respublika birincisi | 2017-2021 - Azərbaycan Tibb Universiteti: Rezidentura - Tədris Cərrahiyyə Klinikasında Şüa-diaqnostikası ixtisası | 2018-2019 və 2021-ci ildə Ege Universiteti Tibb fakültəsi xəstəxanası: Radiologiya üzrə tibbi praktika', 9, 'Radioloq. Şöbə: Somatika və STROK Mərkəzi.', '/doctor-photos/dr-humay-rzayeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. İbrahim Rufullayev', 'dr-ibrahim-rufullayev', 'infectious-diseases', NULL, NULL, 'İnfeksionist. Şöbə: Terapiya.', '/doctor-photos/dr-ibrahim-rufullayev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. İlahə Məcidova', 'dr-ilahe-mecidova', 'anesthesiology', '1999-2005 - Azərbaycan Tibb Universiteti: Tibb fakültəsi | 2009-2014 - İstanbul Universiteti, İstanbul Tibb Fakültəsi: Anesteziologiya və reanimasiya üzrə uzmanlıq təhsili.', 21, 'İntensiv terapiya və reanimasiya şöbəsinin müdiri. Şöbə: Reanimasiya. İş təcrübəsi: 2015-2018 - İzmir, Türkiyə, Reanimasiya: Məsul uzman həkim; 2018-2020 - İstanbul, Türkiyə, Əməliyyatxana: Məsul uzman həkim; 2020-2021 - İstanbul, Türkiyə Reanimasiya: Məsul uzman həkim; 2021 - Stralsund, Almaniya, Helios Hansa-Klinikum Hospitation; 2022-2023 - Azərbaycan Tibb Universiteti, Anesteziologiya və reanimasiya şöbəsi: Uzman həkim; 2024 - Yeni Klinika: İntensiv terapiya və reanimasiya şöbəsinin müdiri..', '/doctor-photos/dr-ilahe-mecidova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Lalə Əliyeva', 'dr-lale-eliyeva-yeniklinika', 'anesthesiology', '1990-1996 - Azərbaycan Dövlət Tibb Universiteti: Müalicə-profilaktika fakültəsi | 1996-1997 - M. Qədirli Adına Mərkəzi Hövzə Xəstəxanası: Anestezialogiya və reanimasiya ixtisası üzrə internatura', 30, 'Anestezioloq-reanimatoloq. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İş təcrübəsi: 1997-1999 - Ağcabədi rayon Mərkəzi Xəstəxanası: Həkim anestezioloq-reanimatoloq; 1999-2002 - H.Qasımov adına 1 nömrəli Doğum evi: Həkim anestezioloq-reanimatoloq; 2002-2007 - İbn-Seena Central Teaching Hospital Al Mukalla (Yəmən): Həkim-anestezioloq; 2007-2009 - H.Qasımov adına 1 nömrəli Doğum evi: Həkim anestezioloq-reanimatoloq; 2009-2020 - Mərkəzi Neftçilər Xəstəxanası: Həkim anestezioloq-reanimatoloq; 2020-2022 - Məlhəm Beynəlxalq Hospital: Həkim anestezioloq-reanimatoloq.. Kurslar: The English for Health Professionals program (EHP) June /2007 - November/2007 Australia, MELBOURNE LANGUAGE CENTRE.; Postgraduate course in Respiration Stockholm Sweden May/2014; Postgraduate course in Regional Anesthesia Stockholm Sweden June/2014; Postgraduate course in Intraoperative Neuromonitoring Berlin Germany May/2015; Postgraduate course in Ultrasound-Guided Regional Anesthesia June/2015. Berlin Germany; Ultrasound in Anesthesia Practice Certificate / San Antonio TX US April/2015; Postgraduate course in Ultrasound-Guided Regional Anesthesia June/2017 Geneva Switzerland.; Postgraduate course in Ultrasound-Guided Central Venous Catheter Placement June/2017Geneva Switzerland; Peripheral Nerve Blocks for Breast and Chest Wall Surgery (Ultrasound based) April 19 /2018 New York /USA.; Salzburg Weill Cornell Seminar in Trauma and Emergency Surgery, December 12-18, 2021 Austria; Salzburg CHOP Seminar in Pediatric Anesthesia and Critical Care, January 16-22, 2022.', '/doctor-photos/dr-lale-eliyeva-yeniklinika.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Lalə İsmayılova', 'dr-lale-ismayilova', 'general-surgery', '2006-2012: Azərbaycan Tibb Universiteti - Müalicə-profilaktika II fakültəsi | 2012-2018: Mərkəzi Neftçilər Xəstəxanası "Cərrahiyyə və orqan transplantasiyası" mərkəzində rezidentura təhsili.', 14, 'ümumi cərrah, transplantoloq. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İcra etdiyi əməliyyatlar: Qaraciyər və böyrək transplantasiyası; Qaraciyər və öd yolları əməliyyatları(xoş və bədxassəli şişlər, kistlərin rezeksiyası); Mədəaltı vəzi əməliyyatları; Dalaq əməliyyatları; Böyrəküstü vəzi əməliyyatları; Mədə və bağırsaq əməliyyatları; Öd kisəsi əməliyyatı; Qarın boşluğu yırtıqları.. Kurslar: Ondokuzmayis Üniversitesi Tıp Fakültesi Hastanesi Genel Cerrahi Anabilim Dalında staj 23.07.2010-20.08.2010; Koç University Hospital , Organ Transplantation Clinical Observership Program between 09 -27 December 2019; International Visiting Scholars Training Program at the Division of Liver Transplantation and Hepatobiliary Surgery at Asan Medical Center, Seoul, South Korea, from October 11,2022 to November 11,2022.; 5th Congress of International Advanced HBP Surgery October 18 (Wed) - 21 (Sat), 2023 at Kongresshaus Zurich, Switzerland.; Laparoscopic training course January 25th to 29th 2025 World Laparoscopy Training Institute Dubai Healthcare City, Dubai, UAE; Fellowship in minimal access surgery on Wednesday 29th January 2025 at Clinical Surgical Training Center, University of Sharjah ,UAE.; MEMBERSHIP of WORLD ASSOCIATION OF LAPAROSCOPIC SURGEONS since 29.01.2025 lifetime.', '/doctor-photos/dr-lale-ismayilova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Lamiyə Zahidli', 'dr-lamiye-zahidli', 'pediatrics', '2009-2015 - Azerbaycan Dövlət Tibb Universiteti: Müalicə-profilaktika fakültəsi | 2016-2020 - Respublika Uşaq Klinik Xəstəxanası: Pediatriya ixtisası üzrə rezidentura.', 11, 'Pediatr. Şöbə: Pediatriya. İş təcrübəsi: 2021-2023 - 3 Saylı Usaq Poliklinikası: Həkim-pediatr; 2022-2023 - Medera Hospital: Həkim-pediatr..', '/doctor-photos/dr-lamiye-zahidli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Lətifə Məmmədzadə', 'dr-letife-memmedzade', 'internal-medicine', '2011-2017 - Azərbaycan Tibb Universiteti: Müalicə profilaktika fakültəsi | 2017-2022 - Bakı Sağlamlıq Mərkəzi: Terapiya üzrə rezidentura təhsili.', 9, 'Terapevt. Şöbə: Terapiya. Müalicə etdiyi xəstəliklər: Anemiyalar (qan azlığı); Qaraciyər xəstəlikləri; Mədə-bağırsaq xəstəlikləri; Ağciyər xəstəlikləri; Böyrək xəstəlikləri; Vitamin çatışmazlığı; Tiroid vəzi xəstəlikləri; Şəkərli diabet; Arterial hipertenziya.', '/doctor-photos/dr-letife-memmedzade.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Məcid Haqverdiyev', 'dr-mecid-haqverdiyev', 'urology', '2005-2011 - Azərbaycan Tibb Universiteti: Müalicə profilaktika fakültəsi | 2016-2022 - Ege Universiteti: Urologiya.', 15, 'Uroloq-Androloq. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. Müalicə etdiyi xəstəliklər: Prostat vəzin hiperplaziyası (müalicə və cərrahiyyəsi); Sidik daşı xəstəliyi (açıq və endoskopik yolla əməliyyat); Uroloji daş xəstəlikləri əməliyyatları (açıq ve edoskopik); Perkutan nefrolitotomiya PCNL; Böyrək əməliyatları (açıq və qapalı); Sidik kisəsi törəmələri; Kişi Sonsuzluğu (müalicə və cərrahiyəsi); Skrotal cərrahiyyə.. Üzvlük: Uroloji Cərrahiyyə Cəmiyyəti; Türkiyə Urologiya Dərnəyi..', '/doctor-photos/dr-mecid-haqverdiyev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Minarə Çərkəzzadə', 'dr-minare-cerkezzade', 'neurology', NULL, NULL, 'İnsult Mərkəzinin (STROK) şöbə müdiri. Şöbə: Nevrologiya.', '/doctor-photos/dr-minare-cerkezzade.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Möhsüm Əsgərov', 'dr-mohsum-esgerov', 'general-surgery', '2005-2011 - Azərbaycan Tibb Universiteti: Müalicə işi, fərqlənmə diplomu | 2011-2016 - Azərbaycan Tibb Universiteti: Ümumi cərrahiyyə üzrə rezidentura | 2018-2021 - Azərbaycan Tibb Universiteti: Doktorantura', 15, 'Ümumi cərrah. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İcra etdiyi əməliyyatlar: Öd kisəsi və öd yolları cərrahiyyəsi (laparoskopik və açıq); Yırtıq əməliyyatları (qasıq yırtığı, göbək yırtığı, əməliyyatdan sonrakı yırtıqlar)- laparoskopik və açıq; Mədə xəstəliklərinin cərrahiyyəsi; Nazik və yoğun bağırsaq əməliyyatları; Qaraciyər və dalaq cərrahiyyəsi; Büzdümün dermoid kistasının ləğvi; Anal çat, anal fistul əməliyyatları; Babasilin lazerlə və klassik yolla əməliyyatları; Diafraqmal yırtığın laparoskopik yolla bərpası.. İş təcrübəsi: 2011-2012 - Respublika Klinik Xəstəxanası; 2012-2016 - ATU Tədris Cərrahiyyə Klinikası; 2014-2015 - İnönü Universiteti, Orqan transplantasiyası institutu, Malatya, Türkiyə; 2016-2018 - Avrasiya Hospital; 2018 - Bakı Şəhəri 20 saylı klinik xəstəxana; 2019-2020 - N.Tusi adına klinika, ümumi cərrah, cərrahiyyə şöbəsinin müdiri; 2020-2023 - Leyla Medical Center, ümumi cərrah, poliklinika şöbəsinin müdiri; 2023 - Yeni Klinika: Ümumi cərrah..', '/doctor-photos/dr-mohsum-esgerov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Münəvvər Muxtarova', 'dr-munevver-muxtarova', 'neurology', '2011-2017 - Azərbaycan Tibb Universiteti: I Müalicə-profilaktika fakültəsi | 2017-2021 - 3 saylı Şəhər Klinik Xəstəxanası: Nevrologiya ixtisası üzrə rezidentura.', 9, 'Nevroloq. Şöbə: Somatika və STROK Mərkəzi. Müalicə etdiyi xəstəliklər: Müxtəlif növ baş ağrıları; Başgicəllənmələr; Depressiya və digər nevrotik pozuntular; Serebrovaskulyar xəstəliklər (işemik ve hemorragik insult); Hərəkət pozuntuları (Parkinson xəstəliyi, narahat ayaqlar sindromu, tremor); Epilepsiya; Müxtəlif növ onurğa problemləri və radikulopatiyalar; Yuxu pozğunluğu; Sinir-əzələ xəstəlikləri; Neyropatiyalar.. İş təcrübəsi: 2015 - "İstanbul Şişli Etfal Eğitim ve Araştırma" Xəstəxanası:1 aylıq təcrübə kursu; Rezidentura təhsili zamanı Tədris Terapevtik Klinikada 2 ay klinik nevrologiya və EEQ üzrə, Neyrocerrahiyyə Xəstəxanasında isə 2 ay neyrocərrahiyyə və lumbar punksiya üzrə rotasiyada olub.. Üzvlük: Milli Nevroloqlar Assosasiyası üzvü; Epilepsiya Əleyhinə Beynəlxalq Liqa üzvü (İİAE).', '/doctor-photos/dr-munevver-muxtarova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Müşfiqə Quliyeva', 'dr-musfiqe-quliyeva', 'obstetrics-gynecology', '2007-2013 - Azərbaycan Dövlət Tibb Universiteti: Müalicə işi fakültəsi | 2016-2017 - Ankara Universiteti, Tibb Fakültəsi: Uzmanlıq təhsili - Anesteziologiya və Reanimasiya kafedrasının assistenti | 2018-2020 - Qazi Universisteti Tibb fakültəsi, Ginekologiya və mamalıq şöbəsi: Köməkçi həkim olaraq uzmanlıq | 2020-2022 - Ankara Şəhər Xəstəxanası, Ginekologiya və mamalıq şöbəsi: Uzmanlıq təhsili.', 13, 'Uzman mama-ginekoloq. Şöbə: Mamalıq və Ginekologiya. İş təcrübəsi: Abşeron Rayon Mərkəzi Xəstəxanası - Həkim-mama-ginekoloq; 2023 - Yeni Klinika: Həkim-mama-ginekoloq..', '/doctor-photos/dr-musfiqe-quliyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Natiq Məsimov', 'dr-natiq-mesimov', 'nephrology', '1995-2001 - Azərbaycan Tibb Universiteti: Müalicə-profilaktika fakültəsi | 2001-2002 - Respublika Klinik Xəstəxanası: Nefrologiya şöbəsində internatura | 2004-2005 - Əziz Əliyev adına Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutu: Nefrologiya və Hemodializ ixtisaslaşma kursu | 2011 - Tbilisi Dövlət Tibb Universiteti: Efferent Terapiya şöbəsi - Periton Dializi Kursu | 2016-2017 - İstanbul Şişli Hamidiye Etfal Eğitim ve Araştırma Hastanesi: Nefrologiya və Hemodializ ixtisasartırma kursu | 2018 - İst...', 25, 'Nefroloq. Şöbə: Terapiya. Müalicə etdiyi xəstəliklər: Kəskin və xroniki böyrək xəstəliyi; Kəskin və xroniki qlomerulonefritlər; Kəskin və xroniki pielonefrit; Diabetik və hipertonik nefropatiya; Hamiləlik nefropatiyası; Xroniki sistit; Prostatit; Prostat vəzinin hipertrofiyası; Böyrək daşı xəstəliyi; Sidik yolları infeksiyaları. İş təcrübəsi: 2004-2010 - Respublika Klinik Xəstəxanası: Hemodializ şöbəsi -Həkim-nefroloq; 2006-2007 - MedServis Tibb Mərkəzi: Həkim-nefroloq; 2010-2023 - Kliniki Tibbi Mərkəz: Nefrologiya və Hemodializ şöbəsi - Həkim-nefroloq.', '/doctor-photos/dr-natiq-mesimov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Nərmin Beydulova', 'dr-nermin-beydulova', 'neurology', '2010-2016 - Azərbaycan Tibb Universiteti: Müalicə-Profilaktika fakültəsi | 2018-2023 - Eskisehir Osmanqazi Tibb Fakültəsi Xəstəxanası - Daxili xəstəliklər üzrə uzman.', 10, 'Uzman terapevt. Şöbə: Somatika və STROK Mərkəzi. Müalicə etdiyi xəstəliklər: Endokrinoloji patologiyalar (şəkərli diabet, qalxanvari vəz, böyrəktüstü vəz xəstəlikləri); Arterial hipertenziya (qan təzyiqinin yüksəlməsi); Anemiyalar; Revmatoloji xəstəliklər; Mədə-bağırsaq və qaraciyər xəstəlikləri; Tənəffus sistemi xəstəlikləri; Xərcəng diaqnostikası.. İş təcrübəsi: 07-09.2014 - İstanbul Eğitim Arastırma Xəstəxanası: Təcili yardım və daxili xəstəliklər kursu; 2017-2018 - Ege Universiteti Tibb fakültəsi: Tibbi staj..', '/doctor-photos/dr-nermin-beydulova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Nərmin Əyyubova', 'dr-nermin-eyyubova', 'ent', '2010-2016- Azərbaycan Tibb Universiteti | 2017-2021 - Azərbaycan Tibb Universiteti: Rezidentura - Otorinolarinqoloq', 10, 'LOR. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi.', '/doctor-photos/dr-nermin-eyyubova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Nicat Mehralıyev', 'dr-nicat-mehraliyev', 'emergency-medicine', '2008-2014- Azərbaycan Tibb Universiteti: Pediatriya', 12, 'Təcili və təxirəsalınmaz tibbi yardım (uşaq) üzrə həkim. Şöbə: Təcili və Təxirəsalınmaz Tibbi Yardım. Müalicə etdiyi xəstəliklər: 0-18 yaş uşaqlar üçün Təcili və Təxirəsalınmaz yardım Kritik xəstə dəyərləndirilməsi; Allergik xəstəliklər; Mədə-bağırsaq sistemi xəstəlikləri; Müxtəlif virus və bakterial mənşəli xəstəliklər; Tənəffüs sistemi xəstəlikləri; Sidik yollarının infeksiyaları; Anemiyalar; Qurd xəstəlikləri və s.. İş təcrübəsi: 2015 - Medi Club Uşaq reanimasiya şöbəsi: Pediatr (assisent); 2016-2019 - Mədinə Tibb Mərkəzi: Həkim Pediatr; 2019-2024 - Xızı rayonu Mərkəzi Xəstəxanası, Giləzi ASM: Ailə həkimi (pediatr)..', '/doctor-photos/dr-nicat-mehraliyev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Nigar Bayramova', 'dr-nigar-bayramova', 'pediatrics', '2008-2014 - Azərbaycan Tibb Universiteti - Bakalavr | 2014-2015 - Almaniya - "Helios Klinikum Pforzheim" - Hospitasiya (tibbi təcrübə) | 2016-2021- Türkiyə - "Bezmialem Vakıf Üniversitesi Hastanesi"- Uzmanlıq təhsili', 12, 'Uşaq Sağlamlığı və Xəstəlikləri Uzmanı. Şöbə: Pediatriya. Müalicə etdiyi xəstəliklər: Sağlam uşaq izlənməsi, böyümə və inkişaf dəyərləndirilməsi; Qidalanma; Anemiyalar; Mədə-bağırsaq sistemi xəstəlikləri; Tənəffüs sistemi xəstəlikləri; Allergik xəstəliklər; Sidik-ifrazat sistemi xəstəlikləri; İnfeksiyon xəstəliklər; Yenidoğulmuşların aylıq rutin müayinələri..', '/doctor-photos/dr-nigar-bayramova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr.Nigar Bayramova', 'dr-nigar-bayramova-yeniklinika', 'radiology', '2008-2014 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi (fərqlənmə diplomu) | 2016-2017 - Kliniki Tibbi Mərkəz - Rezidentura | 2017-2020 - Respublika Diaqnostika Mərkəzi- Rezidentura.', 12, 'Radioloq. Şöbə: Somatika və STROK Mərkəzi.', '/doctor-photos/dr-nigar-bayramova-yeniklinika.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Nigar Məmmədli', 'dr-nigar-memmedli', 'neurology', '2008-2014 - Azərbaycan Tibb Universiteti: Müalicə-profilaktika fakültəsi | 2014-2018 - Azərbaycan Tibb Universitetinin Tədris-Terapevtik Klinikası - Endokrinologiya ixtisası üzrə rezidentura | 2017- İstanbul Üniversitesi Tıp Fakültesi: Endokrinoloji xəstəliklər üzrə məzuniyyət sonrası tədris kursu | 2018 - Ege Universiteti: Endokrinologiya və metabolizma xəstəlikləri kafedrasında təcrübə', 12, 'Endokrinoloq. Şöbə: Somatika və STROK Mərkəzi.', '/doctor-photos/dr-nigar-memmedli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr.Orxan Fərzəliyev', 'dr-orxan-ferzeliyev', 'pediatric-surgery', '2009 - 2015 - Azərbaycan Tibb Universiteti: Bakalavr - Müalicə işi fakültəsi | 2017 - 2022 - Hacettepe Universiteti: Tibb fakültəsi - Uşaq cərrahiyyəsi .', 11, 'Uşaq cərrahiyyəsi şöbəsinin müdiri. Şöbə: Reproduktiv Sağlamlıq və Ailə Planlaması Mərkəzi. İcra etdiyi əməliyyatlar: Yenidoğulmuş və körpələrin anadangəlmə cərrahi xəstəlikləri; Kəskin qarın; Qaraciyər ve öd yollarının cərrahiyyəsi; Uşaqlarda endokrin cərrahiyyəsi; Laparoskopik və torakoskopik cərrahi əməliyyatlar; Endoskopiya ve bronxoskopiya; Uşaqlarda uroloji cərrahi xəstəliklər..', '/doctor-photos/dr-orxan-ferzeliyev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Ramidə Bayramova', 'dr-ramide-bayramova', 'anesthesiology', '2007-2012 - Qazaxıstan Tibb Universiteti: Bakalavr - Müalicə işi fakültəsi | 2012-2014 - Qazaxıstan Tibb Universiteti: İnternatura | 2017-2020 - Azərbaycan Tibb Universiteti: Rezidentura- Anesteziologiya-reanimatologiya', 14, 'Reanimatoloq-anestezioloq. Şöbə: Anesteziologiya.', '/doctor-photos/dr-ramide-bayramova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Raminə Rzayeva', 'dr-ramine-rzayeva', 'emergency-medicine', '1996-2002 - Azərbaycan Tibb Universiteti | 2016-2020 - Sağlıq Bilimləri Universiteti, Şişli Etfal Eğitim və Araşdırma Xəstəxanası: Uşaq Sağlığı və Xəstəlikləri Ana Bilim Dalı (Tibbdə Uzmanlıq) - Asistan doktor | 2020-2021 - İstanbul Mədəniyyət Universiteti, Göztəpə Eğitim və Araştırma Xəstəxanası: Uşaq Sağlığı və Xəstəlikləri Ana Bilim Dalı (Tibbdə Uzmanlıq davamı ve məzuniyyət) - Asistan doktor/ Uzman doktor.', 24, 'Uşaq Təcili Tibbi Yardım şöbəsinin müdiri. Şöbə: Təcili və Təxirəsalınmaz Tibbi Yardım. Müalicə etdiyi xəstəliklər: Kritik xəstə dəğərləndirilməsi; Yenidoğulmuşların rutin müayinəsi və təqibi; Sağlam uşaq izlənməsi; Uşaqlarda qidalanma, böyümə və inkişafın izlənməsi; Usaqlarda nevroloji inkişafın izlənməsi; Anemiyalar; Allergik xəstəliklər; İnfeksiyon xəstəliklər; Mədə-bağırsaq sistemi xəstəlikləri; Tənəffüs sistemi xəstəlikləri; Sidik-ifrazat sistemi xəstəlikləri.. İş təcrübəsi: 2021- 2023 K. Fərəcova adına Elmi Tədqiqat Pediatriya İnstitutu: Həkim-pediatr, elmi işçi; 2023 - Mediclub: Həkim-pediatr; 2023 - Bakı Sağlamlıq Mərkəzi: Həkim-pediatr; 2023 - Yeni Klinika: Həkim-pediatr, Uşaq Təcili və Tibbi Yardım şöbəsinin müdiri..', '/doctor-photos/dr-ramine-rzayeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Rəfiqə Muradova', 'dr-refiqe-muradova', 'hematology', '2010-2016 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi-bakalavr | 2016-2022 - Milli Hematologiya ve Transfuziologiya Mərkəzi: Hematologiya ixtisası üzrə rezidentura | 2014 - TC "İstanbul Haseki Eğitim ve Araştırma Hastanesi"- Terapiya üzrə təcrübə | 28.07-22.12.2022 - TC Kayseri "Erciyes Üniversitesi Tıp Fakültesi, Erciyes Transplant Merkezi" - Sümük iliyi transplantasiyası üzrə rotasiya', 10, 'Hematoloq. Şöbə: Hematologiya və Sümük İliyi Nəqli Mərkəzi. Müalicə etdiyi xəstəliklər: Anemiya (qan azlığı); Trombositopeniyalar və trombositozlar (trombosit hüceyrələrin azlığı və ya çoxluğu); Hemoqlobinopatiyalar; Trombositopatiyalar; Tromboz; Mieloma; Limfoma; Leykemiya.', '/doctor-photos/dr-refiqe-muradova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Reyhan Tağıyeva', 'dr-reyhan-tagiyeva', 'emergency-medicine', '2003-2009 - Naxçıvan Dövlət Universiteti: Pediatriya fakültəsi.', 17, 'Təcili və təxirəsalınmaz tibbi yardım (uşaq) üzrə həkim. Şöbə: Təcili və Təxirəsalınmaz Tibbi Yardım. Müalicə etdiyi xəstəliklər: 0-18 yaş uşaqlar üçün təcili və təxirəsalınmaz yardım; Kritik xəstə dəyərləndirilməsi; Allergik xəstəliklər; Mədə-bağırsaq sistemi xəstəlikləri; Müxtəlif virus və bakterial mənşəli xəstəliklər; Tənəffüs sistemi xəstəlikləri; Sidik yollarının infeksiyaları; Anemiyalar; Qurd xəstəlikləri və s.. İş təcrübəsi: 2008 - Kocaeli Universiteti: Çoçuk Hastalıkları Ana bilim Dalı; 2009-2010 - Fırat Universiteti: Çoçuk Hastalıkları Ana bilim dalı; 2013-2023 - 15 saylı Birləşmiş Şəhər Xəstəxanası: Həkim-pediatr; 2024 - Yeni Klinika: Təcili və təxirəsalınmaz tibbi yardım şöbəsi: Təcili tibbi yardım üzrə həkim..', '/doctor-photos/dr-reyhan-tagiyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Sahabxanım Niftaliyeva', 'dr-sahabxanim-niftaliyeva', 'anesthesiology', '2005-2011 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2012-2015 - Azərbaycan Tibb Universiteti: Rezidentura - Anesteziologiya-reanimatologiya | 2015-2020 - Avrasiya Hospital - Anestezioloq | 2015-2020 - ATU Tədris Terapevtik Klinika - Reanimatoloq | 2020 - Yeni Klinika - Anestezioloq-reanimatoloq', 15, 'Anestezioloq-reanimatoloq. Şöbə: Reanimasiya.', '/doctor-photos/dr-sahabxanim-niftaliyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Şahanə Ələsgərli', 'dr-sahane-elesgerli', 'cardiology', NULL, NULL, 'Kardiologiya şöbəsinin müdiri. Şöbə: Kardiologiya.', '/doctor-photos/dr-sahane-elesgerli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Samirə Həsənova', 'dr-samire-hesenova', 'gastroenterology', NULL, NULL, 'Qastroenteroloq. Şöbə: Qastroenterologiya.', '/doctor-photos/dr-samire-hesenova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Səadət Əhmədova', 'dr-seadet-ehmedova', 'pediatrics', '1983-1989 - Azərbaycan Dövlət Tibb İnstitutu: Pediatriya fakültəsi - Fərqlənmə diplomu ilə bitirib. | 1989-1990 - K.Fərəcova adına Elmi-Tədqiqat Pediatriya İnstitutu: İnternatura.', 37, 'Pediatr. Şöbə: Reproduktiv Sağlamlıq və Ailə Planlaması Mərkəzi. Müalicə etdiyi xəstəliklər: Pediatrik Chek-up müayinələr; Allergik xəstəliklər; Mədə-bağırsaq sistemi xəstəlikləri; Müxtəlif virus və bakterial mənşəli xəstəliklər; Anemiyalar; Peyvənd öncəsi müayinələr; Uşaqlarda böyümə və inkişafın dəyərləndirilməsi; Yenidoğulmuşların müayinəsi və aylıq rutin müayinələrin aparılması; Qurd xəstəlikləri və s..', '/doctor-photos/dr-seadet-ehmedova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Səbinə Paşayeva', 'dr-sebine-pasayeva', 'endocrinology', NULL, NULL, 'Ambulatoriya şöbəsinin müdiri, Endokrinoloq. Şöbə: Terapiya.', '/doctor-photos/dr-sebine-pasayeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Səbinə Tağıyeva', 'dr-sebine-tagiyeva', 'neurology', '2010-2016 - Azərbaycan Tibb Universiteti: Pediatriya fakültəsi | 2016-2021 - Azərbaycan Tibb Universiteti: Tədris Terapevtik Klinikasında Nevrologiya ixtisası üzrə rezidentura təhsili.', 10, 'Nevroloq. Şöbə: Somatika və STROK Mərkəzi. Müalicə etdiyi xəstəliklər: Müxtəlif növ baş ağrıları, başgicəllənmələr; Depressiyalar və digər nevrotik pozğunluqlar; Serebrovaskulyar xəstəliklər (insultlar); Yuxu pozulmaları; Yaddaş pozulmaları; Parkinson; Multipl Skleroz; Müxtəlif növ onurğa problemləri və radikulopatiyalar; Müxtəlif sinir və əzələ xəstəlikləri..', '/doctor-photos/dr-sebine-tagiyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Şəbnəm Bağırlı', 'dr-sebnem-bagirli', 'neonatology', '2010-2016 - Azərbaycan Tibb Universiteti | 2018-2023 - Türkiyə Hacettepe Universiteti, Usaq Sağlığı və Xəstəlikləri Xəstəxanasında pediatriya üzrə uzmanlıq təhsili.', 10, 'Uzman pediatr-neonatoloq. Şöbə: Neonatologiya. Kurslar: 2015 -07 Okmeydanı Eğitim Araştırma Hastanesi Kadın Hastalıkları ve doğum - observer; 2017-09 - 2018-03 Hacettepe Üniversitesi Tıp Fakültesi - observer; 2018-04 Eskişehir Osmangazi Üniversitesi Tıp Fakültesi - Pediatriya - observer; 2019-09 VIII Ulusal Aşı Sempozyumu; 2019-06 Yenidoğan Canlandırma Programı (NRP); 2020-01 Pediatrik İleri Yaşam Desteği (PALS); 2020-11 Anne Sütü ve Emzirme Danışmanlığı Eğitim Programı; 2022-06 Çocuklarda Nörolojik Aciller Kursu; 2022-09 Pediatride Yaygın Nefrolojik Durumlar; 2022-04 Denver II Gelişimsel Tarama Testi..', '/doctor-photos/dr-sebnem-bagirli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr.Şəfəq Ağəliyeva', 'dr-sefeq-ageliyeva', 'emergency-medicine', '2007-2013 - Yaroslavl Dövlət Tibb Akademiyası | 2013-2014 - İnternatura: Mamalıq-Ginekologiya.', 13, 'Təcili və təxirəsalınmaz tibbi yardım üzrə həkim. Şöbə: Təcili və Təxirəsalınmaz Tibbi Yardım. İş təcrübəsi: 2013-2014 - 2 nömrəli Yaroslavl Doğum Evi; 2015-2019 - İnsan Klinika; 2019-2022- 16 BŞX; 2021-2022 - Pirallahı Tibb Mərkəzi; 2022 - Yeni Klinika,Təcili və təxirəsalınmaz tibbi yardım şöbəsi: Təcili və təxirəsalınmaz tibbi yardım üzrə həkim..', '/doctor-photos/dr-sefeq-ageliyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Sənubər İsmayılova', 'dr-senuber-ismayilova', 'pediatrics', '2006-2012 - Azərbaycan Tibb Universiteti | 2012-2015 - Akademik Zərifə Əliyeva adına Milli Oftalmologiya Mərkəzi - Oftalmologiya üzrə rezidentura təhsili | 2016-2020 - Türkiyə Ege Universiteti, Usaq Sağlığı və Xəstəlikləri Xəstəxanasında pediatriya üzrə uzmanlıq təhsili', 14, 'Pediatr. Şöbə: Pediatriya.', '/doctor-photos/dr-senuber-ismayilova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Sevil Cəlilova', 'dr-sevil-celilova', 'hematology', NULL, NULL, 'Sümük iliyi transplantasiyası şöbəsinin müdiri. Şöbə: Hematologiya.', '/doctor-photos/dr-sevil-celilova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Səxavət Xəlilli', 'dr-sexavet-xelilli', 'infectious-diseases', '2010-2015 - Azərbaycan Tibb Universiteti | 2015-2019 - Azərbaycan Tibb Universiteti: Rezidentura - Yoluxucu xəstəliklər ixtisası', 11, 'İnfeksionist. Şöbə: Terapiya. Müalicə etdiyi xəstəliklər: Yuxarı və aşağı tənəffüs yolu infeksiyaları; Dəri və yumşaq toxuma infeksiyaları; Həzm sistemi infeksiyaları; Virus hepatitləri; Sidik yolu infeksiyaları; Cinsi yolla keçən xəstəliklər; Sümük və oynaq infeksiyaları; Parazit infeksiyaları; Səbəbi bilinməyən qızdırmalar; Diabetik ayaq infeksiyaları.', '/doctor-photos/dr-sexavet-xelilli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Sona Məmmədova', 'dr-sona-memmedova', 'neurology', '2011-2017 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2017-2021 Respublika Dəri Zöhrəvi Mərkəzi: Rezidentura - Dermatovenerologiya | 2014 - "İstanbul Haseki Eğitim ve Araştırma Hastanesi": Təcrübə | 2019 - İzmir Ege Universiteti - Dermatovenerologiya şöbəsində rotasiya | 2018 - Dermatocərrahiyyə mövzusunda masterklas | 2021 - Dermatoskopiya mövzusunda kurs.', 9, 'Dermatoveneroloq. Şöbə: Somatika və STROK Mərkəzi. Müalicə etdiyi xəstəliklər: Sızanaq (akne ve rozasea); Psoriaz (pullu dəmrov); Dərinin allergik xəstəlikləri; Eqzemalar; Saç ve dırnaq xəstəlikləri; Piodermiyalar; Dərinin göbələk mənşəli xəstəlikləri; Dərinin virus mənşəli xəstəlikləri; Piqment xəstəliklər və s..', '/doctor-photos/dr-sona-memmedova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Taleh Nağdəliyev', 'dr-taleh-nagdeliyev', 'neurology', NULL, NULL, 'Həkim-nefroloq. Şöbə: Somatika və STROK Mərkəzi.', '/doctor-photos/dr-taleh-nagdeliyev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Tural Behbudsoy', 'dr-tural-behbudsoy', 'orthopedics', '2006-2012 - Azərbaycan Tibb Universiteti: Bakalavr | 2012-2017 - Elmi-Tədqiqat Travmatologiya və Ortopediya İnstitutu: - Mütəxəssis travmatoloq ortoped | 2017-2019 - ASAPES: Magistratura - İdman travmaları və reabilitasiya', 14, 'Travmatoloq-ortoped. Şöbə: Travmatologiya və Ortopediya. İcra etdiyi əməliyyatlar: Sınıq-travma cərrahiyyəsi; Artroplastika - bud-çanaq, diz oynağı endoprotezləşdirilməsi; Əl cərrahiyyəsi; Artroskopik cərrahiyyə; Anadangəlmə və qazanılma deformasiyaların cərrahiyyəsi və s..', '/doctor-photos/dr-tural-behbudsoy.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Tural Əhmədov', 'dr-tural-ehmedov', 'neurosurgery', '2001-2007 - Azərbaycan Tibb Universiteti: Müalicə-profilaktika fakültəsi | 2007-2008 - Bakı Onkoloji Dispanseri: İnternatura | 2016-2022 - İstanbul Universiteti Tibb fakültəsi: Neyrocərrahiyə üzrə uzmanlıq təhsili | 05-09 2022 - İstanbul Universiteti Tibb fakültəsi: Neyrocərrahiyə şöbəsi - Müşahidəçi.', 19, 'Uzman neyrocərrah. Şöbə: Neyrocərrahiyyə. İcra etdiyi əməliyyatlar: Baş beyninin törəmələri; Baş beyin və onurğa beyninin kavernomaları; Kiari Malformasiyası (Beyincik sürüşməsi); Epilepsiya cərrahiyyəsi; Baş beyin və onurğa beyninin absesləri, subdural ampiyemləri; Hidrosefaliya; Travmatik kəskin subdural qanamalar; Xronik subdural qanamalar; Baş beyindaxili qanamalar; Epidural qanamalar; Baş beyninin kistaları; Trigeminal nevralgiya, hemifasiyal spazm (mikrovasküler dekompression); Trigeminal nevralgiya (Balon kompresyon); Dekompressiv kraniyoektomiya; Spina bifida əməliyyatları; Bel və boyun fəqərəarası disk yırtıqları; Boyun, döş və bel spinal kanal darlıqları; Karpal tunel sindromu..', '/doctor-photos/dr-tural-ehmedov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Tural Əliyev', 'dr-tural-eliyev', 'emergency-medicine', '2002-2008 - Azərbaycan Tibb Universiteti: 1. Müalicə Profilaktika Fakültəsi | 2008-2009 - Azərsutikinti Xəstəxanası: İnternatura.', 18, 'Təcili və təxirəsalınmaz tibbi yardım üzrə həkim. Şöbə: Təcili və Təxirəsalınmaz Tibbi Yardım. İş təcrübəsi: 2016-2022 - Respublika TTTYS: Təcili və təxirəsalınmaz tibbi yardım üzrə həkim; 2020-2021 - Mediplus Tibb Mərkəzi: Terapevt-qastroenteroloq; 2019-2020 - ATU Tədris Terapevtik Klinika: Təcili və təxirəsalınmaz tibbi yardım üzrə həkim; 2020 - Caspian Hospital: Təcili və təxirəsalınmaz tibbi yardım üzrə həkim; 2022 - Yeni Klinika, Təcili və təxirəsalınmaz tibbi yardım şöbəsi: Təcili və təxirəsalınmaz tibbi yardım üzrə həkim; 2022 - Xırdalan Tibb Mərkəzi: Terapevt-qastroenteroloq..', '/doctor-photos/dr-tural-eliyev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Tural Məmmədov', 'dr-tural-memmedov-yeniklinika', 'cardiology', '2013-2019 - Orta təhsilini qızıl medalla bitirərək Azərbaycan Tibb Universitetinin Müalicə işi fakültəsini fərqlənmə ilə başa vurub | 2019-2023 - ATU Tədris Cərrahiyyə Klinikası: Rezidentura təhsili.', 7, 'İnvaziv-kardioloq. Şöbə: Ürək-Damar Mərkəzi. İş təcrübəsi: 2019-2023 - ATU Tədris Cərrahiyyə Klinikası: Kardioloq həkim-rezident; 2024 - Yeni Klinika: Həkim-kardioloq..', '/doctor-photos/dr-tural-memmedov-yeniklinika.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Tural Sadıqov', 'dr-tural-sadiqov', 'cardiology', '2009-2015 - Azərbaycan Tibb Universiteti | 2019 -2024 - Rezidentura təhsili.', 11, 'İnvaziv-kardioloq. Şöbə: Kardiologiya. İş təcrübəsi: 2015-2019 - Ədliyyə Nazirliyi Müalicə Müəssisəsi; 2019 - 2021 - Bakı Sağlamlıq Mərkəzi: Kardioloq rezident; 2021-2023 - ATU Tədris Cərrahiyyə Klinikası: Kardioloq rezident; 2023-2024 - Gülhane Eğitim Araşdırma Hastanesi: İnvaziv kardiologiya ixtisaslaşma kursu..', '/doctor-photos/dr-tural-sadiqov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Türkel Hüseynov', 'dr-turkel-huseynov', 'orthopedics', '2005-2009 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2009-2011 - Azərbaycan Tibb Universiteti: Hərbi tibb fakültəsi | 2012-2017 - Azərbaycan Tibb Universiteti: Rezidentura | 2017-2021 - Uzmanlıq təhsili.', 17, 'Uzman travmatoloq-ortoped. Şöbə: Travmatologiya və Ortopediya. İş təcrübəsi: 2012-2020 - Azərbaycan Respublikası Müdafiə Nazirliyi Baş Klinik Hospitalı; 2021 - N.Tusi adına klinika: Travmatoloq-ortoped; 2022 - Mediland Klinikası: Travmatoloq-ortoped; 2023 - bu günə kimi - Yeni Klinika: Travmatoloq-ortoped..', '/doctor-photos/dr-turkel-huseynov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Ülkər Mirzəzadə', 'dr-ulker-mirzezade', 'neurology', '2011-2017 - Azerbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2017-2022 - 3 saylı Şəhər Klinik Xəstəxanası: Nevrologiya üzrə rezidentura təhsili.', 9, 'Nevroloq. Şöbə: Somatika və STROK Mərkəzi. Müalicə etdiyi xəstəliklər: Müxtəlif növ baş ağrıları, başgicəllənmələr; Depressiyalar və digər nevrotik pozğunluqlar; Serebrovaskulyar xəstəliklər (insultlar); Yuxu pozulmaları; Yaddaş pozulmaları; Parkinson və digər hərəkət pozulmaları; Epilepsiya; Müxtəlif növ onurğa problemləri və radikulopatiyalar; Müxtəlif sinir və əzələ xəstəlikləri.. Üzvlük: Milli Nevroloqlar Assosasiyası üzvü; Epilepsiya Əleyginə Beynəlxalq Liqa üzvü (İİAE).', '/doctor-photos/dr-ulker-mirzezade.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Urfan İsmayılov', 'dr-urfan-ismayilov', 'general-surgery', '2009-2015 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2016-2021 - Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutu: Ümumi cərrahiyyə üzrə rezidentura | 2017-2018 - ci illərdə - Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutunun təşkil etdiyi laparoskopiya və endoskopiya kurslarında iştirakçı və nəzarətçi.', 11, 'Ümumi Cərrah. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İcra etdiyi əməliyyatlar: Mədəkiçiltmə əməliyyatı; Xolesistektomiya açıq və qapalı; Laparoskopik fundoplikasiya; Laparoskopik exinokokkektomiy; Açıq və qapalı üsulla appendektomiya; Proktoloji əməliyyatlar; Yırtıq cərrahiyyəsi; Mədə bağırsaq üzərində icra edilən əməliyyatlar; Tiroid vəzi üzərində icra edilən əməliyyatlar; Abdominoplastika..', '/doctor-photos/dr-urfan-ismayilov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Vaqif Qurbanov', 'dr-vaqif-qurbanov', 'general-surgery', '2007-2013 - Azərbaycan Tibb Universiteti | 2013-2017 - 3 saylı Klinik Xəstəxana:Həkim-rezident | 2017-2023 - Ege Universiteti (İzmir): Uzmanlıq təhsili', 13, 'Ümumi cərrahiyyə uzmanı. Şöbə: Cərrahiyyə və Transplantasiya Mərkəzi. İcra etdiyi əməliyyatlar: Endokrin sistemin cərrahi xəstəlikləri; Qalxanabənzər vəzi; Qalxanabənzər ətraf vəzi; Böyrəküstü vəzin cərrahi xəxtəlikləri.; Mədə bağırsaq sisteminin cərrahi xəstəlikləri:; Qida borusu; Mədə; Onikibarmaq bağırsaq; Nazik və yoğun bağırsağın cərrahi xəstəlikləri.; Hepatobilier sisteminin cərrahi xəstəlikləri:; Qaraciyər və öd yolları; Medealti vəzi; Öd kisəsi xəstəliklərinin cərrahi müalicəsi; Qarın divarı yırtıqları və dalağın cərrahi xəstəlikləri; Perianal bölgə xəstəlikləri; Anal çat; Hemorroid; Perianal fistula.. İş təcrübəsi: 2023 - Yeni Klinika: Həkim-ümumi cərrah..', '/doctor-photos/dr-vaqif-qurbanov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Xalidə Əfəndi', 'dr-xalide-efendi', 'obstetrics-gynecology', NULL, NULL, 'Uzman Mama-ginekoloq. Şöbə: Mamalıq və Ginekologiya.', '/doctor-photos/dr-xalide-efendi.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Xəyalə Kərimova', 'dr-xeyale-kerimova', 'neurology', '2000-2006 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2006-2007- Akademik M.Mirqasimov adına Respublika Kliniki Xəstəxanasında terapiya ixtisası üzrə internatura | Azərbaycan, Rusiya və Türkiyədə bir çox elmi konfranslarda iştirakçı.', 20, 'Terapevt. Şöbə: Somatika və STROK Mərkəzi. Müalicə etdiyi xəstəliklər: Anemiyalar (Qan azlığı); Qaraciyər xəstəlikləri (Hepatitlər); Mədəaltı vəz xəstəlikləri; Revmatoloji xəstəliklər; Vitamin çatışmazlıqları; Böyrək xəstəlikləri; Ağciyər xəstəlikləri; Səbəbi bilinməyən qızdırmalar.', '/doctor-photos/dr-xeyale-kerimova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Dr. Zərifə Əhmədova', 'dr-zerife-ehmedova', 'radiology', '2002-2008 - Azərbaycan Tibb Universiteti: Müalicə işi fakültəsi | 2008-2009 - Sumqayıt Təcili Tibbi Yardım Xəstəxanası: İnternatura:', 18, 'Radioloq. Şöbə: Radiologiya.', '/doctor-photos/dr-zerife-ehmedova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Gülnar Qasımzadə', 'gulnar-qasimzade', 'physiotherapy', '2019-2023- Türkiyə Respublikasının İstanbul Medipol Universiteti, Səhiyyə Elmləri Fakültəsi, Fizioterapiya və Tibbi Reabilitasiya sahəsi.', 3, 'Fizioterapevt-reabilitoloq. Şöbə: Fizioterapiya və Reabilitasiya. Müalicə etdiyi xəstəliklər: Ortopedik xəstəliklərin reabilitasiyası; Nevroloji xəstəliklərdə reabilitasiya; İnsult; Parkinson; Multiple Skleroz; Bel,boyun ağrıları; Skolioz, kifoz, lordoz; Rotator manjet vətər zədələnmələri zamanı reabilitasiya.. İş təcrübəsi: 2021-2022 - Türkiyə Respublikası,İstanbul Medipol Mega xəstəxanası:Təcrübəçi fizioterapevt; 2021-2022 - İstanbul Medipol Fındıkzade xəstəxanası:Təcrübəçi fizioterapevt; 2022-2023:İstanbul Medipol Esenler xəstəxanası-Təcrübəçi fizioterapevt; 2022-2023 - Duyusal Akademi:Təcrübəçi fizioterapevt; 2022-2023 - Engelsiz yaşam merkezi:Təcrübəçi fizioterapevt; 2023-2024 - Beykoz Akdem:Təcrübəçi fizioterapevt; 2023-2024 - North Clinics:Təcrübəçi fizioterapevt; 2024 - Maison de Pilates Studio: Fizioterapevt; 2024 - Yeni Klinika: Fizioterapevt-rehabilitoloq..', '/doctor-photos/gulnar-qasimzade.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Nəzrin Əsədli', 'nezrin-esedli', 'physiotherapy', '2018-2022- Manisa Celal Bayar Üniversiteti, Səhiyyə Elmləri Fakultəsi- Fizioterapiya və Reabilitasiya ixtisası (fərqləndirmə diplomu) | 2022-2024- İzmir Katip Çelebi Üniversiteti Fizioterapiya və Reabilitasiya üzrə uzmanlıq Təhsili', 4, 'Uzman fizioterapevt-reabilitoloq. Şöbə: Fizioterapiya və Reabilitasiya. İş təcrübəsi: 2021- Azərbaycan Respublika Diaqnostika Mərkəzi: Təcrübəçi fizioterapevt; 2022- İzmir Hatay Fizioterapiya Müailə Mərkəzi: Təcrübəçi Fizioterapevt; 2022-Manisa Hafsa Sultan Dövlət Xəstəxanası: Təcrübəçi fizioterapevt; 2023- Koreya Şərq Təbabəti Klinikası: Fizioterapevt; 2024-2025 - Yeni Klinika- Uzman Fizioterapevt ( Davam edir).', '/doctor-photos/nezrin-esedli.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Nigar Eyvazova', 'nigar-eyvazova', 'psychology', NULL, NULL, 'Uzman klinik psixoloq. Şöbə: Terapiya.', '/doctor-photos/nigar-eyvazova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Pinar Səfərova', 'pinar-seferova', 'physiotherapy', '2020-2024 - Azərbaycan Tibb Universiteti: Fizioterapiya və Tibbi Reabilitasiya ixtisası üzrə bakalavr təhsili (Fərqlənmə) | 2024 - Azərbaycan Tibb Universiteti: Menecment (əczaçılıq sahəsi üzrə) ixtisası üzrə magistr təhsili (davam edir).', 2, 'Fizioterapevt-Reabilitoloq. Şöbə: Fizioterapiya və Reabilitasiya. Müalicə etdiyi xəstəliklər: Ortopedik xəstəliklərin reabilitasiyası; Nevroloji xəstəliklərdə reabilitasiya; Revmatoloji xəstəliklərdə reabilitasiya; Post - operativ reabilitasiya; Donmuş çiyin sindromu; Skolioz ,kifoz , lordoz; Rotator manjet vətər zədələnmələri zamanı reabilitasiya; Sınıqlardan sonra reabilitasiya.', '/doctor-photos/pinar-seferova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Ramil Əhmədov', 'ramil-ehmedov', 'physiotherapy', '2017-2021 - Manisa Celal Bayar Universiteti, Səhiyyə Elmləri Fakültəsi (fərqlənmə diplomu, birincilik) | 2021-2024 - Dokuz Eylül Universiteti Nevroloji Fizioterapiya və Reabilitasiya üzrə uzmanlıq təhsili | 2024 - Dokuz Eylül Universiteti Fiziki Terapiya və Reabilitasiya üzrə doktorantura təhsili (davam edir).', 5, 'Uzman fizioterapevt-reabilitoloq. Şöbə: Fizioterapiya və Reabilitasiya. Müalicə etdiyi xəstəliklər: İnsult; Dağınıq skleroz; Parkinson; Kəllə-beyin və onurğa yaralanmaları; Miyopatiyalar; Neyropatiyalar; Serebral iflic; Spina bifida və Əzələ distrofiyaları kimi pediatrik və nevroloji xəstəliklərin fizioterapiya və reabilitasiyası.. İş təcrübəsi: 2022-2023 - İzmir Nefes Fizioterapiya Mərkəzi: Fizioterapevt-reabilitoloq; 2024 - Yeni Klinika: Fizioterapevt-reabilitoloq..', '/doctor-photos/ramil-ehmedov.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Səbinə Tağıyeva', 'sebine-tagiyeva', 'physiotherapy', '2017-2021 Türkiyə Hacettepe Universiteti, Fizioterapiya və Reabilitasiya Fakultəsi - Fizioterapiya və Reabilitasiya ixtisası.', 5, 'Fizioterapevt-Reabilitoloq. Şöbə: Fizioterapiya və Reabilitasiya. Müalicə etdiyi xəstəliklər: Qadın sağlamlığı (pelvic floor); Bel və boyun ağrıları (mexaniki bel ağrıları); İdmanda Rehabilitasiya; Ortopedik Rehabilitasiya; Skolioz,kifoz,lordoz. İş təcrübəsi: 2018- Gəncə Beynalxalq Xəstəxanası Təcrübəçi; 2019- Nəsrəddin Tusi Klinikası - Təcrübəçi; 2020- Respublilka Diaqnostika Mərkəzi Təcrübəçi; 2021 - Respublika Diaqnostika Mərkəzi - Fizioterapevt; 2022-Koreya Şərq Təbabəti Klinikası Fizioterapevt; 2022-2023 Hacettepe Universiteti Araştırma Xəstəxanası Fizioterapevt; 2023 Ankara Medifit Sporcu Sağlığı Mərkəzi Fizipterapevt; 2023-2024 Koreya Şərq təbabəti Fizioterapevt; 2024 Baku Medical Plaza Mərkəz Fizipterapevt; 2024-2025 Yeni Klinika Fizioterapevt (davam edir).', '/doctor-photos/sebine-tagiyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Turanə Əliyeva', 'turane-eliyeva', 'speech-therapy', '2019-2023-Bakı Dövlət Universiteti: Korreksiyaedici təlim.', 3, 'Loqoped. Şöbə: Terapiya. Müalicə etdiyi xəstəliklər: Ümumi nitq ləngiməsi; Artikulyasiya aparatının gimnastikası; Tələffüz pozuntuları; Nitq inkişafının geri qalmasının qarşısının alınması; Afaziya (insult sonrası); Kəkələmə; Disleksiya; Dislaliya; Alaliya; Bradilayiya; Taxilaliya; Disfoniya; Afoniya; Exolaliya; Expressiv nitq; Rinolaliya; Dizartriya..', '/doctor-photos/turane-eliyeva.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Vaqif Abdullayev', 'vaqif-abdullayev', 'physiotherapy', '2020-2024 - Azərbaycan Tibb Universiteti: Fizioterapiya və tibbi reabilitasiya ixtisası üzrə bakalavr təhsili (Fərqlənmə diplomu) | 2024-2026 - Azərbaycan Tibb Universiteti: Menecment ixtisası üzrə magistratura təhsili (davam edir).', 2, 'Fizioterapevt-Reabilitoloq. Şöbə: Fizioterapiya və Reabilitasiya. Müalicə etdiyi xəstəliklər: Nevroloji xəstəliklər - İnsult, kəllə və onurğa beyin travmaları, baş və onurğa beyin şişləri əməliyyatı sonrası reabilitasiya, fəqərə arası disk yırtıqları, protruziyalar, karpal və kubital sinir sindromları, mielit, osteoxondroz, nevrozlar, dağınıq skleroz, neyropatiyalar, pleksopatiyalar, fibromialgiya, nevralgiya, nevritlər, parkinson, ifliclər və s.; Ortopedik xəstəliklər - Onurğa əyrilikləri (skolioz, kifoz və lordoz), sınıq və çıxıqlar sonrası reabilitasiya, artroz, artrit, menisk yırtığı, bağ zədələnmələri, daban mahmızı, donmuş çiyin sindromu, diz və bud-çanaq oynaqların protezləşməsi sonrası reabilitasiya və s.; Uroloji xəstəliklər - müxtəlif mənşəli sidikqaçırmalar (nikturiya, gecə enurezləri və s.); Androloji xəstəliklər - Prostatit, peyroni, erektil disfunksiya (cinsi zəiflik), vezikulit və s.; Kardioloji və pulmonoloji xəstəliklər - Müxtəlif ürək və ağciyər xəstəlikləri sonrası ağırlaşmalar zamanı reabilitasiya.. İş təcrübəsi: 2022 - Kəpəz Hospital: Təcrübəçi; 2023 - Stimul Hospital: Təcrübəçi; 2024 - Koreya Şərq Təbabəti Klinikası: Fizioterapevt-reabilitoloq; 2024 - Yeni Klinika: Fizioterapevt-reabilitoloq..', '/doctor-photos/vaqif-abdullayev.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW()),
    ('Zeynəb Məmmədova', 'zeyneb-memmedova', 'physiotherapy', '2020-2024 - Türkiyə Respublikası, İstanbul Cerrahpaşa Universiteti, Səhiyyə Elmləri Fakültəsi, Fizioterapiya və Tibbi Reabilitasiya ixtisası üzrə bakalavr təhsili | 2020-2024 - Türkiyə Respublikası, İstanbul Universiteti,Səhiyyə Elmləri Fakültəsi, Uşaq İnkişafı ixtisası üzrə əlavə bakalavr təhsili (yan dal) | Türkiyə Respublikası,İstanbul Aydın Universiteti,Səhiyye Elmləri Fakültəsi, Pediatriyada Fizioterapiya ve Tibbi Reabilitasiya ixtisası üzre magistratura təhsili hazırda davam edir.', 2, 'Fizioterapevt-Reabilitoloq. Şöbə: Fizioterapiya və Reabilitasiya. Müalicə etdiyi xəstəliklər: İnsult sonrası reabilitasiya; Menisküs zədələrində reabilitasiya; Bel ağrıları; İmpingement sindromu; Serebral iflic; Doun sindromu; Braxial pleksus; Skolioz,kifoz,lordoz; Diz-hip endoprotezinden sonra reabilitasiya; Spina bfida; Dayaq-hərəkət sistemi xəstəlikləri; Multipl skleroz; Parkinson; Yerişin bərpası; Totikolis.. İş təcrübəsi: 2021-2022 - Türkiyə Respublikası, Medicine Hospital: Təcrübəçi fizioterapevt; 2022-2023 - Baku Medical Plaza: Təcrübəçi fizioterapevt; 2023-2024 - Türkiyə Respublikası, Cerrahpaşa Tibb Fakültəsi Xəstəxanası: Təcrübəçi fizioterapevt; 2023-2024 - Türkiyə Respublikası, Metin Sabancı Türkiye Spastik Çocuklar Vakfı: Təcrübəçi fizioterapevt; 2024 - Türkiyə Respublikası, Acıbadem Xəstəxanası: Fizioterapevt..', '/doctor-photos/zeyneb-memmedova.webp', 'az', 'UNCLAIMED', 'yeniklinika.gov.az', 0, 1, NOW(), NOW())
;

-- 101 new listings plus the doctor already here from Referans, who now has
-- both hospitals against his one listing.
CREATE TEMPORARY TABLE yeniklinika_placement (doctor_slug VARCHAR(255), clinic_slug VARCHAR(255));
INSERT INTO yeniklinika_placement (doctor_slug, clinic_slug) VALUES
    ('aytac-quliyeva', 'yeni-klinika'),
    ('dr-ahdab-ezim', 'yeni-klinika'),
    ('dr-almaz-eliyeva', 'yeni-klinika'),
    ('dr-aygul-dasdemir', 'yeni-klinika'),
    ('dr-aygul-qurbanova', 'yeni-klinika'),
    ('dr-aynur-haciyeva', 'yeni-klinika'),
    ('dr-aynur-huseynova', 'yeni-klinika'),
    ('dr-aynur-ismayilova', 'yeni-klinika'),
    ('dr-aysel-agalarova', 'yeni-klinika'),
    ('dr-aysel-ehmedova', 'yeni-klinika'),
    ('dr-aysel-hesenova', 'yeni-klinika'),
    ('dr-aysen-xanlarli', 'yeni-klinika'),
    ('dr-azad-suleymanov', 'yeni-klinika'),
    ('dr-azer-memmedov', 'yeni-klinika'),
    ('dr-cemile-ehmedova', 'yeni-klinika'),
    ('dr-cosqun-piriyev', 'yeni-klinika'),
    ('dr-ekber-quliyev', 'yeni-klinika'),
    ('dr-elcin-elizade', 'yeni-klinika'),
    ('dr-elgin-hacizade', 'yeni-klinika'),
    ('dr-ellada-nagiyeva', 'yeni-klinika'),
    ('dr-elnur-ziyadov', 'yeni-klinika'),
    ('dr-elsen-necefov', 'yeni-klinika'),
    ('dr-elsen-qedimov', 'yeni-klinika'),
    ('dr-elvin-eliyev', 'yeni-klinika'),
    ('dr-elvin-tanriverdi', 'yeni-klinika'),
    ('dr-elvira-babasova', 'yeni-klinika'),
    ('dr-emil-qasimov', 'yeni-klinika'),
    ('dr-emin-nesirov', 'yeni-klinika'),
    ('dr-fariz-huseynov', 'yeni-klinika'),
    ('dr-fatime-qafarova', 'yeni-klinika'),
    ('dr-fatma-memmedli', 'yeni-klinika'),
    ('dr-fexriyye-quliyeva', 'yeni-klinika'),
    ('dr-fidan-elesgerova', 'yeni-klinika'),
    ('dr-firdovsi-ferhadzade', 'yeni-klinika'),
    ('dr-goycek-memmedli', 'yeni-klinika'),
    ('dr-gulay-memmedova', 'yeni-klinika'),
    ('dr-gulnar-abdullayeva', 'yeni-klinika'),
    ('dr-gulxar-suleymanova', 'yeni-klinika'),
    ('dr-gunay-allahverdiyeva', 'yeni-klinika'),
    ('dr-gunel-esgerova', 'yeni-klinika'),
    ('dr-gunel-rzazade', 'yeni-klinika'),
    ('dr-hemzet-cigerov', 'yeni-klinika'),
    ('dr-hilal-budaqova', 'yeni-klinika'),
    ('dr-humay-rzayeva', 'yeni-klinika'),
    ('dr-ibrahim-rufullayev', 'yeni-klinika'),
    ('dr-ilahe-mecidova', 'yeni-klinika'),
    ('dr-lale-eliyeva-yeniklinika', 'yeni-klinika'),
    ('dr-lale-ismayilova', 'yeni-klinika'),
    ('dr-lamiye-zahidli', 'yeni-klinika'),
    ('dr-letife-memmedzade', 'yeni-klinika'),
    ('dr-mecid-haqverdiyev', 'yeni-klinika'),
    ('dr-minare-cerkezzade', 'yeni-klinika'),
    ('dr-mohsum-esgerov', 'yeni-klinika'),
    ('dr-munevver-muxtarova', 'yeni-klinika'),
    ('dr-musfiqe-quliyeva', 'yeni-klinika'),
    ('dr-natiq-mesimov', 'yeni-klinika'),
    ('dr-nermin-beydulova', 'yeni-klinika'),
    ('dr-nermin-eyyubova', 'yeni-klinika'),
    ('dr-nicat-mehraliyev', 'yeni-klinika'),
    ('dr-nigar-bayramova', 'yeni-klinika'),
    ('dr-nigar-bayramova-yeniklinika', 'yeni-klinika'),
    ('dr-nigar-memmedli', 'yeni-klinika'),
    ('dr-orxan-ferzeliyev', 'yeni-klinika'),
    ('dr-ramide-bayramova', 'yeni-klinika'),
    ('dr-ramine-rzayeva', 'yeni-klinika'),
    ('dr-refiqe-muradova', 'yeni-klinika'),
    ('dr-reyhan-tagiyeva', 'yeni-klinika'),
    ('dr-sahabxanim-niftaliyeva', 'yeni-klinika'),
    ('dr-sahane-elesgerli', 'yeni-klinika'),
    ('dr-samire-hesenova', 'yeni-klinika'),
    ('dr-seadet-ehmedova', 'yeni-klinika'),
    ('dr-sebine-pasayeva', 'yeni-klinika'),
    ('dr-sebine-tagiyeva', 'yeni-klinika'),
    ('dr-sebnem-bagirli', 'yeni-klinika'),
    ('dr-sefeq-ageliyeva', 'yeni-klinika'),
    ('dr-senuber-ismayilova', 'yeni-klinika'),
    ('dr-sevil-celilova', 'yeni-klinika'),
    ('dr-sexavet-xelilli', 'yeni-klinika'),
    ('dr-sona-memmedova', 'yeni-klinika'),
    ('dr-taleh-nagdeliyev', 'yeni-klinika'),
    ('dr-tural-behbudsoy', 'yeni-klinika'),
    ('dr-tural-ehmedov', 'yeni-klinika'),
    ('dr-tural-eliyev', 'yeni-klinika'),
    ('dr-tural-memmedov-yeniklinika', 'yeni-klinika'),
    ('dr-tural-sadiqov', 'yeni-klinika'),
    ('dr-turkel-huseynov', 'yeni-klinika'),
    ('dr-ulker-mirzezade', 'yeni-klinika'),
    ('dr-urfan-ismayilov', 'yeni-klinika'),
    ('dr-vaqif-qurbanov', 'yeni-klinika'),
    ('dr-xalide-efendi', 'yeni-klinika'),
    ('dr-xeyale-kerimova', 'yeni-klinika'),
    ('dr-zerife-ehmedova', 'yeni-klinika'),
    ('gulnar-qasimzade', 'yeni-klinika'),
    ('nezrin-esedli', 'yeni-klinika'),
    ('nigar-eyvazova', 'yeni-klinika'),
    ('pinar-seferova', 'yeni-klinika'),
    ('ramil-ehmedov', 'yeni-klinika'),
    ('sebine-tagiyeva', 'yeni-klinika'),
    ('turane-eliyeva', 'yeni-klinika'),
    ('uzm-dr-turan-memmedeliyev', 'yeni-klinika'),
    ('vaqif-abdullayev', 'yeni-klinika'),
    ('zeyneb-memmedova', 'yeni-klinika')
;

INSERT INTO doctor_clinic (doctor_id, clinic_id)
SELECT d.id, c.id
FROM yeniklinika_placement p
JOIN doctor d ON d.slug = p.doctor_slug
JOIN clinic c ON c.slug = p.clinic_slug
WHERE NOT EXISTS (
    SELECT 1 FROM doctor_clinic dc
    WHERE dc.doctor_id = d.id AND dc.clinic_id = c.id);

DROP TEMPORARY TABLE yeniklinika_placement;
