-- The 44 doctors Respublika Diaqnostika Merkezi publishes.
--
-- Read from rdm.az on 2026-09-19, in Azerbaijani. The eighth source.
--
-- The count is 44 and two readings agree exactly, with nothing on either side
-- the other lacks: the directory paginates four pages of 12, 12, 12 and 8, and
-- the site's own sitemap carries 44 doctor URLs. This is the first source
-- whose sitemap could simply be trusted.
--
-- None of these doctors asked to be here. Every row is UNCLAIMED with
-- accepts_bookings = 0.
--
-- One name already existed in this directory twice over. There is a Kenan
-- Ahmadov at Merkezi Klinika who is a cardiologist and qualified in 1997-2003,
-- and another who is a dermatologist; this one is a urologist and head of
-- department who qualified at the Pirogov university in Moscow in 2005-2011.
-- Three different men, one common name, so this one's slug is suffixed or
-- INSERT IGNORE would have dropped him without a word.
--
-- This source states length of service itself for 43 of the 44, so
-- years_experience is the centre's own figure rather than one worked out from
-- a graduation year. The one it leaves out, Elxan Zergerov, falls back to
-- years since his degree ended in 2008, which is how every source that
-- publishes no figure at all is handled.
--
-- Every doctor publishes their education and their career, and every one has a
-- portrait. What is deliberately not imported is the patient reviews: each
-- profile carries a star rating and named comments, and republishing somebody
-- else's reviews under our name would be passing off their word as ours.
-- Where a doctor's academic degree is simply "Hekim" it adds nothing to the
-- biography and is left out; a doctorate or professorship is kept.
--
-- Data only.

INSERT INTO clinic (name, slug, address, city, phone, description, active, created_at, updated_at)
SELECT * FROM (SELECT
    'Respublika Diaqnostika Mərkəzi' AS name, 'respublika-diaqnostika-merkezi' AS slug,
    'Tbilisi prospekti 147, 20 Yanvar, Bakı' AS address, 'Bakı' AS city,
    '*913' AS phone,
    'Respublika Diaqnostika Mərkəzi, Bakı. Siyahı mərkəzin rdm.az saytındakı həkim kataloqu əsasında hazırlanıb.' AS description,
    1 AS active, NOW() AS created_at, NOW() AS updated_at) AS c
WHERE NOT EXISTS (SELECT 1 FROM clinic WHERE slug = 'respublika-diaqnostika-merkezi');

-- INSERT IGNORE, not ON DUPLICATE KEY: MariaDB on production does not take
-- the row-alias form, and a slug that somehow already exists should be left
-- alone rather than overwritten by a scrape.
INSERT IGNORE INTO doctor
    (full_name, slug, specialty_code, qualifications, years_experience, bio,
     photo_url, languages, verification, source, accepts_bookings, active, created_at, updated_at)
VALUES
    ('Ağakişi Yəhyayev', 'agakisi-yehyayev', 'interventional-radiology', '1997-2003 Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi, Terapiya ixtisası | 2003-2004 Azərbaycan Tibb Universiteti, Ümumi cərrahiyyə ixtisası üzrə internatura | 2006-2011 İstanbul Universiteti, Tibb Fakültəsi, Uzmanlıq', 13, 'İnvaziv - radioloq. İş təcrübəsi: 2011-2012 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2012-ci ildən bu günədək Respublika Diaqnostika Mərkəzində fəaliyyət göstərir.', '/doctor-photos/agakisi-yehyayev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Akif Mir Seyid', 'akif-mir-seyid', 'anesthesiology', '1996-2002 Azərbaycan Tibb Universiteti.', 21, 'Anestezioloq-reanimatoloq. İş təcrübəsi: 2002-2006 Naxçıvan şəhər Respublika Xəstəxanasında anestezioloq-reanimatoloq vəzifəsində çalışıb.; 2004-2005 cəbhə bölgəsində N saylı hərbi hissədə tibb məntəqə rəisi - həkim kimi zabit olaraq həqiqi hərbi xidmətdə olub.; 2006-cı ildən bu günə kimi Bakı şəhər Təcili və Təxirəsalınmaz Tibbi Yardım Stansiyasında anestezioloq-reanimatoloq vəzifəsində çalışır.; 2021- dən Respublika Diaqnostika Mərkəzində Təcili və təxirəsalınmaz tibbi yardım üzrə həkim, şöbə müdiri.; 2013 ildə "Kayseri şeher Devlet Hastanesinde Yoğun bakım unitesində" kurs keçmişdir..', '/doctor-photos/akif-mir-seyid.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Almaz Səfərova', 'almaz-seferova', 'neurology', '1988-1994 Azər­baycan Dövlət Tibb Universiteti, Müalicə profilaktika fakültəsi | 1994-1995 Respublika Diaqnostika Mərkəzində (RDM) Neyrofiziologiya laboratoriyasında internatura | 2013 - İstanbul Cerrahpaşa Tıp Fakültesi Üniversitesi nevrologiya şöbəsi - ENMQ, yuxu EEQ və çağırılmış potensiallar üzrə kurs | 2018 - Əziz Əliyev adına Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutunun nevrologiya və klinik neyrofiziologiya kafedrasının doktorantı | 2022 - Sinir xəstəlikləri ixtisasında Tibb Elmləri üzr...', 28, 'Nevroloq-neyrofizioloq. Elmi dərəcə: Tibb üzrə fəlsəfə doktoru. İş təcrübəsi: 1996-2008 Respublika Diaqnostika Mərkəzində Neyrofiziologiya laboratoriyasında (EEQ, EXO EEQ) kabinetində çalışmışdır; 2008-2013 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2011- 2021 Kliniki Tibbi Mərkəzdə (Semaşko xəstəxanası) radiologiya şöbəsində həkim-nevroloq- EEQ-ma kabinetində çalışmşdır.; 2013-cü ildən bu günə qədər RDM-də həkim-nevroloq-EEQ , ENMQ, Çağırılmış potensiasllar üzrə mütəxəssis kimi çalışır..', '/doctor-photos/almaz-seferova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Altay Cəfərov', 'altay-ceferov', 'orthopedics', '1981-1987 Azərbaycan Tibb Universiteti | 1989-1990 Polşa, Lodz şəhəri, Kopernik adına Hospital, Woldemar link kursları | 1992 Rusiya Federasiyası, Moskva Şəhəri.Semaşko adına Tibb Akademiyas | 1994 Ukraina, Kiev şəhəri, NUPO OSTEOSİNTEZ | 1998-2001 Türkiyə Cümhuriyyəti, Ankara, Hacettepe Universiteti, Başkent Universiteti, İSAKOS Tədris mərkəzi | Tibb Elmləri Namizədi: Moskva Rusiya Federasiyası | İştirak etdiyi treninq və seminarlar: | 1999 Türkiyə, Ankara, GATA, AO-ASIF kursu | 2000 Türkiyə, Antalya, A...', 35, 'Travmatoloq-ortoped. Elmi dərəcə: Tibb elmləri namizədi. İş təcrübəsi: 1989-1998 Elmi-Tədqiqat Travmatologiya və Ortopediya İnstitutu (Travmatoloq-Ortoped); 2001-2006 Mərkəzi Kliniki Xəstəxana; 2006-2015 City Hospital; 2015-ci ildən bu günədək Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/altay-ceferov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Anar Əmrah', 'anar-emrah', 'cardiovascular-surgery', '1995-2001 Gülhanə Hərbi Tibb Akademiyasında tibb təhsili, Ankara, Türkiyə | 2005-2011 Gülhanə Hərbi Tibb Akademiyasının Ürək-damar Cərrahiyyəsi bölməsində uzmanlıq təhsili | İştirak etdiyi treninq və seminarlar: | 2006 Kardiyoloji ve Kardiyovasküler Cerrahide Antitrombotik Yaklaşımlar Sempozyumu | 2006 NATOnun təşkil etdiyi "Müasir cəmiyyətdə insanların terror aktlarından sonra yaşadıqları travmanın inteqrasiyası" mövzusunda seminar | 2008 Kalp Damar Cerrahisi Sempozyumu, Bursa, Türkiyə | 2008-cü Kardiyo...', 22, 'Ürək-damar cərrahı. Elmi dərəcə: Uzman. İş təcrübəsi: 2002-2003 Ankara Gülhanə Hərbi Tibb Akademiyasının Təcili Tibbi Yardım şöbəsində və Samsun şəhərində Səhra Səhiyyə Məktəbində həkim kimi çalışıb; 2003-2005 illərdə aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2010-2011 Ankara Başkent Universiteti Ürək-damar Cərrahiyyəsi Klinikasında 9 ay Ürək köçürülməsi və Pediatrik ürək cərrahiyyəsi bölmələrində fəal olaraq çalışıb; 2011-2012 Ankara Gülhanə Hərbi Tibb Akademiyası Ürək-damar Cərrahiyyəsi Klinikasında işləyib; 2012-2013 Ankara şəhərində yerləşən Kavaklıdere Umut Xəstəxanasında (Umut Kalp Merkezi) uzman kardiocərrah kimi fəaliyyət göstərib; 2013-2018 illərdə aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; Respublika Diaqnostika Mərkəzi Bakı Ürək Mərkəzi Ürək-damar Cərrahiyyəsi şöbəsinin müdiri vəzifəsində çalışır - 2019-cu ildən bu günədək.; Mükafatları:; Azərbaycan Respublikası "Qüsursuz xidmətə görə" 3-cü dərəcəli medal.; İcra etdiyi əməliyyatlar:; Minimal İnvaziv qapaq əməliyyatı; By pass; Full Arterial By pass əməliyyatı; Ürəyin işemik xəstəliyi zamanı koronar arteriyalarda şuntlama əməliyyatı; Anadangəlmə ürək qüsurlarının cərrahi üsulla aradan qaldırılması; Ürəyin işemik xəstəliyi zamanı koronar şuntlama əməliyyatı - ürəyi dayandırmadan, çalışan ürəkdə əməliyyat; Ürək qapaqlarının təmiri və protezləşdirilməsi əməliyyatı; Kiçik kəsikdən minimal invaziv ürək əməliyyatları; Ürək dəstək cihazlarının (süni ürək) implantasiyası; Ritm problemlərinin cərrahi ablasiya üsulu ilə aradan qaldırılması; Periferik arteriya və venalarda cərrahi əməliyyatlar; Lazer və yapışdırma üsulu ilə varis problemlərinin aradan qaldırılması; Ağciyər və periferik damarlarda olan trombların əridilməsi əməliyyatı..', '/doctor-photos/anar-emrah.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Aneta Səfərəliyeva', 'aneta-sefereliyeva', 'anesthesiology', '1992 Sumqayıt şəhəri TTTY Gimnaziya | 1993-2000 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi | 2000-2001 Sumqayıt TTYX-da Reanimasiya-anesteziologiya şöbəsində internatura', 23, 'Anestezioloq - reanimatoloq. İş təcrübəsi: 2001-2018 illərdə aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2018-ci ildən bu günədək Respublika Diaqnostika Mərkəzində Reanimasiya şöbəsinin müdiri vəzifəsində çalışır.', '/doctor-photos/aneta-sefereliyeva.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Araz Süleymanov', 'araz-suleymanov', 'anesthesiology', 'Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi. | İştirak etdiyi treninq və seminarlar: | 2019 "Neonatal Reanimasiya Proqramı" kursu | 2019 "Pediatrik İrəliləmiş Həyati Dəstək" kursu | 2019 "Təkmil Həyata Dəstək" (Təxirəsalınmaz kardioloji yardım) / "ACLS" üzrə təlim | 2020 BLS (Basic Life Support)', 29, 'Anestezioloq-reanimatoloq. İş təcrübəsi: Hal-hazırda Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/araz-suleymanov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Aynur Babayeva', 'aynur-babayeva', 'obstetrics-gynecology', '2003-2009 Azərbaycan Tibb Universitetində bakalavr dərəcəsi, Bakı, Azərbaycan | 2008-2009 5 №-li Dövlət Doğum Evi, Doğuş və Ginekologiya şöbəsində internatura, Bakı, Azərbaycan | 2009-2010 Mərkəzi Dəmiryol Xəstəxanasının Mamalıq və Ginekologiya kafedrasının aspiranturasının klinik ordinaturası, Bakı, Azərbaycan | 2023-cü bu günə kimi Doktorant, Azərbaycan Dövlət Doktorantura İnstitutu | İştirak etdiyi treninq və seminarlar: | 15-17 noyabr 2019-cu il Best of the Big Apple CME Ultrasəs müayinə kursu, Nyu-Y...', 21, 'Mama - ginekoloq. İş təcrübəsi: 2010-2022 Mərkəzi Neftçilər Xəstəxanası Mamalıq və Ginekologiya şöbəsinin mama-ginekoloqu, Bakı, Azərbaycan; 2019-2021 Caspian International Hospital, Mamalıq və Ginekologiya süni mayalanma şöbəsi, Bakı, Azərbaycan; 2021-ci ildən bu günə kimi Respublika Diaqnostika Mərkəzi, Mamalıq və Ginekologiya şöbəsi, Mama-ginekoloq, Bakı, Azərbaycan; İcra etdiyi xidmətlər:; - Hamiləlik planlaşdırılması və təqibi; - Təbii doğuş və keysəriyyə kəsiyi; - Laparoskopik ginekoloji əməliyyaylar; - Estetik ginekoloji əməliyyatlar; - Histerosalpinqografiya; - Sonsuzluğun müalicəsi; - Süni mayalanma; - Ginekoloji ultrasəs müayinəsi; - Kolposkopiya.', '/doctor-photos/aynur-babayeva.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Cabir Əliyev', 'cabir-eliyev', 'radiology', 'Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi, Terapiya ixtisası. | İştirak etdiyi treninq və seminarlar: | 1983 Həkimlərin Təkmilləşdirmə İnstitutu, Rentgenologiya kursu. | 1988 Sankt-Peterburq Hərbi-Tibbi Akademiyası. Onkoloji xəstələrin rentgen diaqnostikası | 2010 "Şüa diaqnostikası" kursu. | 2018 Radiasiya təhlükəsizliyinin əsasları kursu. | 2019 Amerika Ürək Assosiasiyasının və Amerika Kardiologiya Cəmiyyətinin "BLS" və "Heartsaver CPR AED" metodologiyası əsasında hazırlanmış həkim və tibb iş...', 40, 'Radioloq. Elmi dərəcə: Tibb elmləri namizədi. İş təcrübəsi: Hal-hazırda Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/cabir-eliyev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Ceyhun İsmayılov', 'ceyhun-ismayilov', 'orthopedics', '1996-2002 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi | 2002-2003 Akademik Z.Əliyeva adına Azərbaycan Elmi-Tədqiqat Göz Xəstəlikləri İnstitutunda, internatura | 2010-2012 Rusiya Xalqlar Dostluğu Universitetində ,ordinatura | İştirak etdiyi treninq və seminarlar: | 2018 V Congress of Traumatologists&Orthopaedics | 2017 Cadaveric Dissection Course on "Anatomical Surgical Approaches to the Extremities" | 2019 III Съезд Травматологов-Ортопедов Республики Казахстан | 2019 7th Emirates Interna...', 14, 'Travmatoloq-ortoped. İş təcrübəsi: 2013-2015 Moskva şəhərində 12 N-li Şəhər Xəstəxanasında həkim-travmatoloq kimi fəaliyyət göstərib; Hal hazırda Respublika Diaqnostika Mərkəzində fəaliyyət göstərir.', '/doctor-photos/ceyhun-ismayilov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Dilarə Əfəndiyeva', 'dilare-efendiyeva', 'laboratory', '1981-1987 Azərbaycan Tibb Universiteti, Pediatriya fakültəsi | 1987-1988 6 saylı Uşaq Kliniki Xəstəxanasında internatura | 2000 AR Səhiyyə Nazirliyi nəzdində Attestasiya Komissiyasından keçmiş və ali dərəcəli Həkim-laborant adını almışdır', 36, 'Həkim-laborant. İş təcrübəsi: 1988-2008 Respublika Diaqnostika Mərkəzində Laboratoriya şöbəsinin müdiri; 2008-2012 illərdə - Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2012-ci ildən Respublika Diaqnostika Mərkəzində Laboratoriya şöbəsinin müdiri kimi fəaliyyət göstərir..', '/doctor-photos/dilare-efendiyeva.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Dina Zotova', 'dina-zotova', 'internal-medicine', '1993- 1999 Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi | 1999-2000 Akademik C.M.Abdullayev adına Elmi-Tədqiqat Kardiologiya İnstitutunda həkim-kardioloq ixtisası üzrə internatura | 2000-2021 İntensiv terapiya şöbəsində həkim | İştirak etdiyi treninq və seminarlar: | 2011 " Kliniki kardiologiya", Almaniya | 2013 Belarusiya Respublika Elmi Tədqiqat Kardioloji Mərkəzi. Kliniki kardiologiya kursu. | 2014 Belarusiya Respublika Elmi Tədqiqat Kardioloji Mərkəzi. | 2018 Elmi Tibbi Tədqiqat Mərkəzi, Sankt...', 27, 'Terapevt. İş təcrübəsi: 2012-ci ildən bu günədək Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/dina-zotova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Eldar Vəliyev', 'eldar-veliyev', 'cardiovascular-surgery', '1986-1992 Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi, Ümumi cərrahiyyə ixtisası | 1992-1993 Akad. C.M.Abdullayev adına Elmi-Tədqiqat Kardiologiya İnstitutunda Ümumi cərrahiyyə ixtisası üzrə internatura | İştirak etdiyi treninq və seminarlar: | 1999, 2003, 2007, 2011 Türkiyənin Gülhanə Hərbi Tibb Akademiyasında cərrahiyyə kursları | 2014 Əziz Əliyev adına Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutunda Kardiocərrahiyyə (modul 3-4) kursu | 2014 İngiltərədə "Aort qapağının plastikası" kursu...', 31, 'Ürək-damar cərrahı. İş təcrübəsi: 2018-ci ildən bu günədək Respublika Diaqnostika Mərkəzinin Kardiocərrahiyyə şöbəsində ürək-damar cərrahı vəzifəsində fəaliyyət göstərir.', '/doctor-photos/eldar-veliyev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Elxan Zərgərov', 'elxan-zergerov', 'ent', '2002-2008 Azərbaycan Tibb Universiteti, Müalicə profilaktika fakultəsi | 2017-2022 Gülhanə Eğitim Araştırma Xəstəxanası, Ankara,Türkiyə | Treninq və seminarlar: | 2019 "Kadavra üzərində endoskopik sinus cərrahiyyəsi" Ankara, Türkiyə | 2020 "Qulaq cərrahiyyəsi" Ankara Universiteti, Türkiyə | 2021 "Rinoplastika kursu" Hacettəpə Universiteti, Türkiyə | 2021 "Xorlama və yuxu problemlərinin cərrahi yolla müalicəsi" GEAH, Türkiyə', 18, 'Otorinolarinqoloq. Elmi dərəcə: Uzman. İş təcrübəsi: 2022-2024 Naxçıvan Mərkəzi Hospitalı otorinolarinqologiya şöbəsi; 2024-ci ildən bu günədək Respublika Diaqnostika Mərkəzində otorinolarinqoloq kimi fəaliyyət göstərir..', '/doctor-photos/elxan-zergerov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Fərhad Qarayev', 'ferhad-qarayev', 'radiology', '1996 - 2001 Azərbaycan Dövlət Tibb İnstitutu (Həkim) | 2001 Azərbaycan Dövlət Həkimlərin Təkmilləşdirməsi İnstitutu (Həkim-rentgenoloq) | 2012 - 2019 Azərbaycan Dövlət Həkimlərin Təkmilləşdirməsi İnstitutu( Həkim şüa diaqnostik)', 24, 'Radioloq. İş təcrübəsi: 2001-2002 Turk-American Medical Center Radioloq; 2002-2014 Leyla Şixlinskaya Klinikası Radioloq; 2006-2014 Nəsrəddin Tusi adına Klinika Radioloq; 2008-2014 Uniklinika Radioloq; 2013-2016 Caspian International Hospital Radiologiya şöbəsinin müdiri; 2014-2016 Mərkəzi Klinik Xəstəxana Radiologiya şöbəsinin müdiri; 2016-2025 Hayat Clinic Radiologiya şöbəsinin müdiri.', '/doctor-photos/ferhad-qarayev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Fəxri Quliyev', 'fexri-quliyev', 'urology', '2001-2007 Azərbaycan Dövlət Tibb Universiteti, Müalicə-profilaktika fakültəsi | 2007-2008 Akademik Mirqasımov adına Respublika Klinik Xəstəxanasının Urologiya kafedrasında internatura | 2010-2011 Türkiyə Cumhuriyyəti Ankara Qazi Universiteti Urologiya kafedrasında təkmilləşmə | İştirak etdiyi treninq və seminarlar: | 2010 Ulusal Minimal İnvaziv Ürolojik Cerrahi Kongresi | 2011 10cu Üroonkoloji Kongresi Antalya | 2013 11ci Üroonkoloji Kongresi Antalya | 2015 6cı Uroonkologiya Qış Konqresi və Kursu | 2015...', 17, 'Uroloq-cərrah. İş təcrübəsi: 2011-2016 Milli Onkologiya Mərkəzi Onkourologiya şöbəsi, həkim-uroloq; 2016-2019 Medical Plaza xəstəxanası, həkim uroloq; 2019-2021 Ege Hospital, həkim-uroloq 2019-2021; 2021-2024 Caspian İnternational Hospital,h əkim-uroloq; Hal hazırda Respublika Diaqnostika Mərkəzində fəaliyyət göstərir; İcra etdiyi əməliyyatlar:; Böyrək və sidik yolları daşlarının endoskopik lazer cərrahiyəsi; Laparoskopik cərrahiyə; Prostat vəzi adenomasının endoskopik cərrahiyəsi; Sidik kisəsi törəmələrinin endoskopik cərrahiyəsi; Böyrək və sidik-cinsiyyət sisteminin bəd və xoşxassəli törəmələrinin cərrahiyəsi; Böyrək-sidik yollarının anadangəlmə və qazanılmış qüsurlarının rekonstruktiv cərrahi əməliyyatları; Kişi sonsuzluğu mikrocərrahi müalicəsi..', '/doctor-photos/fexri-quliyev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Gülnar Cəlilova', 'gulnar-celilova', 'endocrinology', '2004-2010 Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi | 2010-2011 Respublika Klinik Xəstəxanasında internatura | 2012-2015 Azərbaycan Respublikası Fövqəladə Hallar Nazirliyi Hospitalı poliklinika şöbəsində həkim | 2015-2019 Respublika Diaqnostika Mərkəzində Endokrinologiya ixtisası üzrə rezidentura | 2019 Ege Üniversitesi Endokrinoloji Bilim Dalında gözlemci doktor eğitimi, Türkiyə', 14, 'Endokrinoloq. İş təcrübəsi: 2010 - 2024- Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2020-ci ildən bu günədək Respublika Diaqnostika Mərkəzində həkim-endokrinoloq vəzifəsində çalışır.', '/doctor-photos/gulnar-celilova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Gülxanım İsmayılova', 'gulxanim-ismayilova', 'hematology', '2008-2014 Azərbaycan Tibb Universiteti | 2015-2019 B.Eyvazov adına Hematologiya və Transfuziologiya İnstitutu - həkim-rezident | 2018-ci ildə "Azərbaycanda ilkin miyelofibrozun epidemiologiyası,diaqnostikası və müalicəsi" adlı məqalə üzərində işləyib | 2017-ci ildə Ukraynanın Xarkov şəhəri Mərkəzi xəstəxanasında və 2019-cu ildə Rusiya Moskva şəhəri Prezident yanında idarəetmə Klinik xəstəxanasında (Volınskaya) tibbi təcrübə keçmişdir.', 8, 'Hematoloq. İş təcrübəsi: 2015-2019 illərdə B.Eyvazov adına Hematologiya və Transfuziologiya İnstitutu - həkim-rezident; 2020- dən Respublika Diaqnostika Mərkəzində Həkim-hematoloq, Qan Bankı şöbəsinin müdiri.; İştirak etdiyi treninq və seminarlar:; 1-ci Azərbaycan Beynəlxalq Hematoloqiya Mütəxəssisləri Konqresi.; 2-ci Azərbaycan Beynəlxalq Hematoloqiya Mütəxəssisləri Konqresi.; Müalicə etdiyi xəstəliklər:; Bütün növ anemiyalar (qan azlığı), talassemiyalar, sümük iliyinin bədxassəli şişləri (leykozlar, miyelom xəstəliyi və s.), miyelofibroz, miyelodisplastik sindrom(refrakter anemiya), aplastik anemiya.; Bacarıqları: sümük iliyinin aspirasion və trepanobiopsiyası, intratekal kimyəvi dərman müalicəsi..', '/doctor-photos/gulxanim-ismayilova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Hüseyn Babayev', 'huseyn-babayev', 'anesthesiology', '2007-2013 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi | 2014-2017 3 saylı Şəhər Klinik Xəstəxanasında rezidentura', 9, 'Anestezioloq-reanimatoloq. İş təcrübəsi: 2015 - 2018 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2015 - DTX Hospital; 2016 - Uludağ Universiteti Anesteziologiya və Reanimasiya üzrə kurs; 2017- German Hospital; 2018-ci ildən bu günədək Respublika Diaqnostika Mərkəzinin Anesteziologiya şöbəsində həkim anestezioloq-reanimatoloq vəzifəsində çalışır..', '/doctor-photos/huseyn-babayev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('İbrahim Əfəndiyev', 'ibrahim-efendiyev', 'general-surgery', '1987-1993 Azərbaycan Dövlət Tibb Universiteti, Müalicə-profilaktika fakültəsi | 1993-1994 M.Nağıyev adına Bakı şəhər Təcili Yardım Xəstəxanasının Cərrahiyyə şöbəsində internatura | İştirak etdiyi treninq və seminarlar: | 2012 İrlandiya Cərrahların Kral Kolleci | 2013 Ə.Əliyev adına Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutunda Həkim cərrah ixtisası üzrə hazırlıq kursu | 2014 İstanbul Universiteti Çapa Tibb fakültəsi Xəstəxanasında "Qastroskopiya və kolonoskopiya" kursu | Fundamental Critical Ca...', 37, 'Ümumi cərrah. İş təcrübəsi: 1987-1989 Rusiyanın Leninqrad şəhərindəki hərbi hospitalda məcburi hərbi xidmətdə tibb qardaşı; 1994 - 2003 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2013-2014 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2002-2013 Səudiyyə Ərəbistanı Krallıgı Səhiyyə Nazirliyi "Wothelan General Hospital"da ümumi cərrah; İstanbul Universiteti Çapa Tibb fakültəsi Xəstəxanasının Cərrahi Endoskopiya şöbəsində həkim-cərrah - sentyabr-dekabr 2014; 2015-ci ildən bu günədək Respublika Diaqnostika Mərkəzində ümumi cərrah; İcra etdiyi əməliyyatlar:; Öd kisəsi və öd yollarında açıq və laparoskopik cərrahi əməliyyatlar; Laparoskopik appendektomiya; Diafraqma yırtıqlarının laparoskopik təmiri (fundoplikasiya); Müxtəlif mənşəli bağırsaq keçməzliyinin ləğvi; Nazik və yoğun bağırsaqlarda aparılan açıq və laparoskopik əməliyyatlar; Yırtıqların açıq və laparoskopik üsulla təmiri (qasıq, göbək yırtıqları, orta xətt, əməliyyatdan sonra əmələ gələn yırtıqlar və s.); Diaqnostik laparoskopiya; Bariatrik və metabolik cərrahiyyə (mədə kiçiltmə əməliyyatı); Abdominoplastika; Babasil düyünlərinə lateks həlqələrinin qoyulması; Hemorroidektomiya; Pararektal fistulların ləğvi; Anal çatın cərrahi müalicəsi; Anal stenozlarda plastik rekonstruksiya (anoplastika)..', '/doctor-photos/ibrahim-efendiyev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('İlkin Göyüşov', 'ilkin-goyusov', 'urology', '2008-2014 Nijniy - Novqorod Dövlət Tibb Akademiyası, (Müalicə İşi fakültəsi), Rusiya Federasiyası | 2014-2016 Privoljski regional "Federal Tibbi və Bioloji Agentlik" Tibb Mərkəzin əsasında urologiya üzrə rezidentura | 2016-2017 Nijniy - Novqorod Regional Onkologiya Mərkəzində onkologiya ixtisası üzrə internatura ⁠ | 2017 "Ultrasəs diaqnostikası" sahəsində təkmillləşdirmə, Nijni Novqorod Dövlət Tibb Akademiyası', 10, 'Uroloq-onkoloq. İş təcrübəsi: 2014 - 2019 Priviljskiy Rayon Tibb Mərkəzi, 3 saylı Kliniki Xəstəxananın urologiya şöbəsi; 2018 - 2019 Nijniy - Novqorod, 30 saylı Şəhər Xəstəxanası, urologiya şöbəsi; ⁠2019 - 2022 Novqorod Regional Onkoloji Dispanser, Uroloji Onkologiya şöbəsi; 2023-cü ildən bu günə kimi Respublika Diaqnostika Mərkəzində uroloq - onkoloq..', '/doctor-photos/ilkin-goyusov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('İlqar İsmayılov', 'ilqar-ismayilov', 'general-surgery', '1994-2001 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi | 2007-2012 Türkiyənin Ankara şəhərində Gülhanə Hərbi Tibb Akademiyasında Ümumi Cərrahiyyə uzmanı ixtisasına sahib olub | İştirak etdiyi seminarlar: | 2017 XVI Türk Kolon ve Rektum Cerrahisi Kongresi, Antalya | 2018 Rektal Xəstəliklərə Yeni yanaşma. Transanal Total Mezorektal Eksizyon, Barselona | 2019 Mədə Cərrahiyyəsi Bölməsi və Yoğun Bağırsaq və Rektal Cərrahiyyə Bölməsi, ASAN Tibb Mərkəzi, Seul | 2019 NIDA Klinik Sınaqlar Şəbəkəsi...', 22, 'Ümumi cərrah. Elmi dərəcə: Uzman. İş təcrübəsi: 2002 - 2007 illərdə Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2017-ci ildən RDM-də həkim ümumi cərrah və 2018-ci ildən RDM Ümumi cərrahiyyə şöbəsinin müdiri vəzifəsində çalışır; Minimal invaziv (laparoskopik) qida borusu, mədə, bağırsaq əməliyyatları üzrə geniş təcrübəyə malikdir; Azərbaycan və ətraf regionda ilk və yeganə TransAnal Cərrahiyyə Mərkəzi qurmuşdur və düz bağırsaq xərçəngi xəstələrinə ən müasir cərrahi yardım göstərməkdədir; Avropanın ən böyük cərrahi virtual universiteti olan IRCAD-ın WebSurge portalında yayımlanan 4 expert videoların müəllifidir.; İcra etdiyi əməliyyatlar:; - Qarın divarının yırtıqlarının bərpası, laparoskopik; - Düz əzələ diastazının bərpası; - Süd vəzi cərrahiyyəsi; - Tiroid vəzi (zob) cərrahiyyəsi; - Öd kisəsi və öd yolları cərrahiyyəsi; - Qida borusunun xoş və bədxassəli şişlərinə görə laparoskopik əməliyyatlar; - Mədə xərçənginin laparoskopik əməliyyatları; - Bağırsaq şişlərinin laparoskopik cərrahiyyəsi; - Düz bağırsaq şişlərində TransAnal əməliyyatlar (TAMIS, TATME)..', '/doctor-photos/ilqar-ismayilov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('İradə Musayeva', 'irade-musayeva', 'radiology', '1997-2003 Azərbaycan Tibb Universiteti, II Müalicə-profilaktika fakültəsi | 2003-2004 Elmi-Tədqiqat Kardiologiya İnstitutu, Kardiologiya ixtisası üzrə internatura | 2008-2013 Türkiyənin Ege Universiteti, Tibb fakültəsi, Radiologiya kafedrasında uzmanlıq', 18, 'Radioloq. İş təcrübəsi: 2004 - 2013 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2013-cü ildən bu günədək Respublika Diaqnostika Mərkəzində Şüa diaqnoastikası şöbəsində həkim-radioloq; Azərbaycan və Türk Radiologiya Cəmiyyətlərinin, Avropa Radiologiya Cəmiyyəti, Şimali Amerika Radiologiya Cəmiyyətinin həqiqi üzvüdür; Çoxsaylı ixtisasartırma kurslarının, seminar və konfransların fəal iştirakçısı olmuşdur..', '/doctor-photos/irade-musayeva.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Kənan Əhmədov', 'kenan-ehmedov-rdm', 'urology', '2005-2011 İ. Piroqov adına Rusiya Dövlət Tibb Universiteti (Moskva ş.) | 2012 Rusiya Dövlət Tibb Universitetinin ümumi cərrahiyyə kafedrasında və 4 saylı Şəhər Klinik Xəstəxanasında internatura | 2014 Rusiya Tibb Akademiyasının urologiya və cərrahi andrologiya kafedrasında rezidentura | 2012-ci ildən Rusiya Uroloqlar Cəmiyyətinin üzvü | 2018-ci ildən Avropa Urologiya Assosiasiyasının üzvü | Elmi nəşrlərin, o cümlədən Ali Attestasiya Komissiyasının rəyindən keçənlərin müəllifi və həmmüəllifi. | Rusiya və...', 13, 'Uroloq, şöbə müdiri. İş təcrübəsi: 2014-2023 V. M. Buyanov adına Şəhər Klinik Xəstəxanası (Rusiya Federasiyası, Moskva), uroloq. Bu 10 il müddətində təcili və planlı uroloji müdaxilələr həyata keçirdib.; 2023-cü ildən bu günə kimi Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/kenan-ehmedov-rdm.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Lalə Əhmədova', 'lale-ehmedova', 'dermatology', '1995-2001 Azərbaycan Tibb Universiteti, müalicə-profilaktika fakultəsi | 2001-2002 Respublika Dəri-Zöhrəvi Dispanserində internatura | İştirak etdiyi treninq və seminarlar | İxtisas üzrə sertifikasiya kursu, 2014 | Hestorex, 1-ci Dünya Səhiyyə İdman və Turizm konqresi, Antalya, Türkiyə, Aprel 2017 | Mezoterapiya, Botulinoterapiya və Karboksiterapiya üzrə üzrə təlimlər, İnternational İnstitute of Esthetic Cosmetology, Sankt-peteburq, Rusiya, Yanvar 2018 | Hestorex, 1-ci Dünya Səhiyyə İdman və Turizm konqr...', 24, 'Dermatoloq. İş təcrübəsi: 2002-2006 Gəncə Dəri Zöhrəvi Dispanseri, həkim dermatoveneroloq; 2006-2014 World Med klinikası, həkim dermatoveneroloq; 2015-2022 - Respublika Diaqnostika Mərkəzi, həkim dermatoveneroloq; 2022-2023 Korea Təbabəti Mərkəzi, həkim dermatoveneroloq; 2023-2025 Paramed klinikası, həkim dermatoveneroloq; 2025 Mart ayından Respublika Diaqnostika Mərkəzi, həkim dermatonevroloq.', '/doctor-photos/lale-ehmedova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Leyla İsmayılova', 'leyla-ismayilova', 'radiology', '2000-2006 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi', 15, 'Radioloq. İş təcrübəsi: 2007 - 2018 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2018-ci ildən bu günədək Respublika Diaqnostika Mərkəzində İntervensional radiologiya və şüa diaqnostikası şöbəsində ultrasəs müayinə mütəxəssisi vəzifəsində çalışır.', '/doctor-photos/leyla-ismayilova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Leyla Matanova', 'leyla-matanova', 'physiotherapy', '1987-1993 Azərbaycan Tibb Universiteti, Pediatriya fakültəsi | Treninq və seminarlar: | 2005 Həkimlərin Təkmilləşdirmə İnsitutunda fizioterapiya və reabilitasiya fakültəsi | 2017,2022 Klassik və biometrik kineziologiya | 2019 FDM - osteopatiya', 17, 'Fizioterapevt. İş təcrübəsi: 2007 "Neurosphere Clinic", həkim-fizioterapevt; 2014 "Hayat Clinic", həkim-fizioterapevt; 2016-2022 Mediland klinikası fizioterapiya və reabilistasiya şöbəsinin müdiri, həkim-fizioterapevt, kinezioloq, FDM-osteopat; Respublika Diaqnostika Mərkəzində 2022-ci ildən bu günədək fəaliyyət göstərir.; İcra etdiyi prosedurlar:; Manual əzələ testləri ilə onurğa və oynaqaların funksional vəziyyəti, reflekslərin diaqnostikası; Manual və osteopatik üsullarla müalicə; Visseral manual və osteopatik müalicə üsulları; Fiziki, mexanki və optiki faktorların müalicədə tətbiqi.', '/doctor-photos/leyla-matanova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Mehriban Əfəndiyeva', 'mehriban-efendiyeva', 'internal-medicine', '2000-2006 Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi | 2006-2007 M.Ə.Əfəndiyev adına 2 saylı Şəhər Klinik Xəstəxanasında Terapevt ixtisası üzrə internatura | Asiya və Sakit okean ölkələrinin Qaraciyər Xəstəlikləri Assosiasiyasının (APASL) üzvü olub | Avropa Allergiya və Klinik İmmunologiya Akademiyasının üzvüdür.', 17, 'Terapevt. İş təcrübəsi: 2007-2019 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2012-2019 Daxili İşlər Nazirliyi Daxili Qoşunlarının Hərbi Hospitalı; 2019-cu ildən bu günədək Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/mehriban-efendiyeva.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Mətanət Abbasova', 'metanet-abbasova', 'physiotherapy', '2000-2006 Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi | 2006-2007 Elmi-Tədqiqat Tibbi Bərpa İnstitutunda internatura | İştirak etdiyi treninq və seminarlar: | 2009,2015,2013 Ə.Əliyev adına Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutunda 2 aylıq fizioterapiya kursu | 2015 Ə.Əliyev adına Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutunda 1 aylıq fizioterapiya kursu | 2015 Reha-Med Reabilitasiya Mərkəzində 2 həftəlik kurs, Zinsheym, Almaniya | 2017 IOC World Conference on Prevention of...', 17, 'Fizioterapevt. İş təcrübəsi: 2007 - 2017 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2017-ci ildən bu günədək Respublika Diaqnostika Mərkəzində fizioterapevt kimi fəaliyyət göstərir; 2021-ci ildən bu günədək fizioterapiya şöbə müdiri vəzifəsində çalışır.', '/doctor-photos/metanet-abbasova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Natiq Mirzəyev', 'natiq-mirzeyev', 'cardiovascular-surgery', '1998-2004 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi | 2004-2006 Rusiyanın Moskva şəhərində yerləşən A.N.Bakulev adına Ürək-Damar Cərrahiyyəsi Elmi-Tədqiqat Mərkəzində ürək-damar cərrahı, klinik ordinatura | 2006-2009 Rusiyanın Moskva şəhərində yerləşən A.N.Bakulev adına Ürək-Damar Cərrahiyyəsi Elmi Tədqiqat Mərkəzində ürək-damar cərrahı, aspirantura | 2010 Tibb üzrə fəlsəfə doktoru (Rusiya) | 2017 Diplom dənglik (STS)- Səviyyə təsbit imtahanı (Türkiyə) | 2023 Avropa Ürək-Döş qəfəsi cər...', 17, 'Ürək-damar cərrahı. Elmi dərəcə: Tibb üzrə fəlsəfə doktoru, PhD. İş təcrübəsi: 2009-2012 Mərkəzi Neftçilər xəstəxanasında ürək-damar cərrahı vəzifəsində fəaliyyət göstərib; Respublika Diaqnostika Mərkəzində ürək-damar cərrahı vəzifəsində çalışır - 2012-ci ildən bu günədək; Üzvlük:; Minimal invaziv ürək cərrahiyyəsi beynəlxalq cəmiyyəti- ISMICS; Avropa Kardio-Torakal Cərrahiyyə Assosiasiyası- EACTS; Azərbaycan Ürək-Damar Cərrahiyyəsi Cəmiyyəti- AÜDCC; İcra etdiyi cərrahi əməliyyatlar:; Minimal invaziv ürək əməliyyatları - 5-7 sm-lik kiçik kəsiklə və döş sümüyünü kəsmədən qabırğa arasından koronar, qapaq və anadangəlmə ürək qüsuru əməliyyatları; Aorta-koronar şuntlama (ürəyin tac damarları üzərində əməliyyatlar); Ürək qapaq əməliyyatları (protezləşdirmə və plastika); Aorta üzərində əməliyyatlar (anevrizma və disseksiyaların cərrahiyyəsi); Böyüklərdə anadangəlmə ürək qüsuru əməliyyatları (12 yaşdan yuxarı); Yuxu arteriyası üzərində əməliyyatlar (karotis arteriya cərrahiyyəsi)..', '/doctor-photos/natiq-mirzeyev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Nemət Məlikov', 'nemet-melikov', 'gastroenterology', '2007-2013 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi | 2011 Azərbaycan Tibb Universiteti və Ankara Tibb Universiteti arasında tələbə mübadiləsi proqramı çərçivəsində 1 aylıq yay praktikasında iştirak etmişdir | 2013-2014 Respublika Diaqnostika Mərkəzində (RDM) Qastroenterologiya ixtisası üzrə rezidentura | 2015-2016 Azərbaycan Səhiyyə Nazirliyi ilə Türkiyə Səhiyyə Nazirliyi arasındakı müqaviləyə əsasən, Türkiyənin Ankara Yüksək İxtisas Xəstəxanasında həkim-rezidentlərin xaricdə təhsili...', 13, 'Qastroenteroloq. İş təcrübəsi: 2019-cu ildən bu günədək Respublika Diaqnostika Mərkəzində həkim-qastroenteroloq vəzifəsində çalışır.', '/doctor-photos/nemet-melikov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Nigar Əsgərova', 'nigar-esgerova', 'obstetrics-gynecology', '1995 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi | 1995-1996 Bakı Perinatal Mərkəzi, mamalıq-ginekoloq üzrə internatura. | 1996 Elmi Tədqiqat Mamalıq və Ginekologiya İnstitutu, elmi işçi. | İştirak etdiyi treninq və seminarlar: | 2013 Mama-ginekologiya üzrə sertifikasiya | 2016 Həkimləri Təkmilləşdirmə İnstitutu, mamalıq-ginekologiya ixtisası üzrə kurs | 2021- Mama-ginekologiya üzrə sertifikasiya', 30, 'Mama-ginekoloq. İş təcrübəsi: 2011-2015 Medilux Klinikası, mama-ginekoloq; 2015-2018 Caspian İnternational Hospital, mama-ginekoloq; 2018-2022 Baku Medical Plaza klinikası, mama-ginekoloq; 2022-2024 Leyla Medical Center, mama-ginekoloq; Hal-hazırda Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/nigar-esgerova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Püstə Xəlilova', 'puste-xelilova', 'cardiology', '1998-2004 Azərbaycan Tibb Universiteti, Müalicə işi fakültəsi | 2004-2005 Akademik C.M.Abdullayev adına Elmi-Tədqiqat Kardiologiya İnstitutunda Kardiologiya ixtisası üzrə internatura', 10, 'Kardioloq. İş təcrübəsi: 2014-cü ildən bu günədək Respublika Diaqnostika Mərkəzində həkim-kardioloq vəzifəsində çalışır..', '/doctor-photos/puste-xelilova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Rauf Səmədov', 'rauf-semedov', 'cardiology', '1997-2004 Azərbaycan Tibb Universiteti', 10, 'Kardioloq. Elmi dərəcə: Tibb elmləri namizədi. İş təcrübəsi: Təlimlər: Kardiologiya üzrə kurslar, University Hospital. Friedrich Schiller - Jena; Hal-hazırda Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/rauf-semedov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Rəna Abasova', 'rena-abasova', 'radiology', '2000 Azərbaycan Tibb Universiteti | 2002 Radiologiya (USM) üzrə ixtisaslaşma | Təlimlər: | 2004 Moskva ş, «I. M. Seçenov» adına Tibb Akademiyası | «Perinatal diaqnostika» kursu | 2004 «A. V. Vignevski» adına cərrahiyyə institutu, təkmilləşmə kursu | 2013-2014 Amsterdam, «Fibroscan» müayinəsi üzrə kurs | Üzvlük: | EASL, APASL, ISUOG, RASUDM', 24, 'Radioloq. İş təcrübəsi: 2000-2003 7 saylı doğum evi; 2003-2013 "Leyla Şıxlinskaya" klinikası; 2013-2014 ""Baku" klinikası, FiBROSCAN üzrə mütəxəssis; 2013-2014 "Eurolab" klinikası, Radioloq (USM); 2014 Caspian International Hospital, Radioloq (USM); 2024-ci ildən bu günədək Respublika Diaqnostika Mərkəzində fəaliyyət göstərir; Fəaliyyət sahələri:; Perinatal diaqnostika (rəngli doppler, 3D, 4D); Ginekologiya; Mammologiya; Endokrinologiya; Neyrosonoqrafiya; Pediatriya; Hepatologiya; Urologiya; Müayinə istiqamətləri:; Perinatal diaqnostika (doppler, 3D, 4D); Ginekoloji-Mamoloji-Endokrinoloji USM; Pediatrik USM; Hepatoloji USM; Uroloji USM; Yumşaq toxumalar USM; Cərrahi xəstəlikler, punksiyalar, biopsiyalar va s..', '/doctor-photos/rena-abasova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Rəna Əmirova', 'rena-emirova', 'neurology', '2004-2010 Azərbaycan Tibb Universiteti, Pediatriya fakültəsi, bakalavr | 2011-2015 Azərbaycan Tibb Universiteti Tədris Terapevtik Klinika, Nevrologiya və tibbi genetika kafedrası, həkim-nevroloq,rezidentura təhsili | 2014-2015 T.C. Hacettepe Üniversitesi Tip Fakültəsi Nöroloji Anabilim Dalı Nöroloji Servisi,ixtisas artırma təhsili | İLAE ( Beynəlxalq Eplilepsiya Əleyhinə liqa) və WFN (Dünya Nevroloqlar Federasiyası) | İştirak etdiyi treninq və seminarlar: | Diagnosis and Management of Multipl Sclerosis T...', 13, 'Nevropatoloq. İş təcrübəsi: 2011-2015 Azərbaycan Tibb Universiteti Tədris Terapevtik Klinika Nevrologiya şöbəsi 2011-2015, nevroloq-rezident; 2015-2017 Azərbaycan Tibb Universiteti Tədris Terapevtik Klinika Nevrologiya şöbəsi 2015-2017, nevroloq-həkim; 2017-2019 Respublika Perinatal Mərkəz, nevroloq-həkim; 2019-cu ildən bu günədək Respublika Diaqnostika Mərkəzi, həkim-nevroloq.', '/doctor-photos/rena-emirova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Rəna Şirəliyeva', 'rena-sireliyeva', 'neurology', '1973-1979 Azərbaycan Dövlət Tibb Universiteti | 1977-1980 Semaşko adına 1 saylı Şəhər Klinik Xəstəxanasının 7-ci terapiya şöbəsində internatura | 1984-1987 Azərbaycan Dövlət Tibb İnstitutu Sinir xəstəlikləri ixtisası üzrə aspirantura | 2004 Tibb elmləri doktoru | 2007 Professor | 2015 "Əməkdar Elm xadimi" fəxri adına layiq görülmüşdür | İştirak etdiyi treninq və seminarlar: | 1993 "Tibbi diaqnostikanın aktual məsələləri" II Respublika elmi konfransı, Bakı | 2002 Epileptologiya üzrə 5-ci Avropa Konqresi...', 44, 'Nevropatoloq. Elmi dərəcə: Professor. İş təcrübəsi: 1980 - 2018 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; AR Prezidenti yanında Ali Attestasiya Komissiyasının ekspert şurasının, Azərbaycan Tibb jurnalının, Azərbaycan Kurortologiya, fizioterapiya və reabilitasiya jurnalının və Psixiatriya jurnalının redaksiya şuralarının üzvüdür, Milli Nevrologiya Jurnalının baş redaktorudur.; Nevrologiya sahəsində 100-dən artıq elmi əsər, o cümlədən 5 dərslik, 6 tədris vəsaiti, 2 monoqrafiya, 2 məlumat kitabçası, 8 metodik tövsiyyənin müəllifidir, məqalələri respublikada və xaricdə dövrü nəşriyyatda çap olunmuşdur..', '/doctor-photos/rena-sireliyeva.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Şahin Xəlilov', 'sahin-xelilov', 'cardiology', '1996-2002 Azərbaycan Tibb Universiteti, Müalicə-profilaktika fakültəsi | 2002-2003 Akademik C.M.Abdullayev adına Elmi-Tədqiqat Kardiologiya İnstitutunda Kardiologiya ixtisası üzrə internatura | 2004-2007 Akademik C.M.Abdullayev adına Elmi-Tədqiqat Kardiologiya İnstitutunda Kardiologiya ixtisası üzrə aspirantura | Tibb üzrə fəlsəfə doktoru. | İştirak etdiyi treninq və seminarlar: | 2006 Milano University, San Donato policlinic (Milano, Italy) | 2008 Pediatric echocardiography courses (Parma, Italy) | 2009...', 22, 'İnvaziv-kardioloq. Elmi dərəcə: Tibb üzrə fəlsəfə doktoru. İş təcrübəsi: 2002-2017-ci illərdə aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2012-ci ildən bu günədək Respublika Diaqnostika Mərkəzində invaziv kardioloq, şöbə müdiri vəzifəsində çalışır; İngilis, rus və Azərbaycan dillərində yazılmış 25-dən çox məqalənin müəllifidir. Son 10 ildə 50-dən çox beynəlxalq konqres və simpoziumda fəal iştirak etmişdir.; 2022-ci ildən ATU I-ci daxili xəstəliklər kafedrasının elmi pedaqoji fəaliyyəti ilə məşğuldur.; Hal-hazırda doktorluq dissertasiya üzrə çalışır.; İcra etdiyi əməliyyatlar:; Koronar angioqrafiya; Perkutan translyuminal koronar angioplastika (PTKA); CRT-D; ICD implantasiyası; Elektriki kardioversiya; Peysmekerin taxılması ..', '/doctor-photos/sahin-xelilov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Samirə Allahverdiyeva', 'samire-allahverdiyeva', 'ent', '2001-2007 ci illərdə Azərbaycan Tibb Universitetinin "Müalicə işi" fakültəsini bitirmişdir. | 2007-2008 ci illərdə akademik Mir Qasımov adına Respublika Klinik Xəstəxanasında "Otorinolarinqoloq" ixtisası üzrə internatura təhsili almışdır. | 2013-2014 cü illərdə La Sapienza Universitetində Tibb və Odontoyatriya fakultəsində Rino-allerqologiya üzrə magistr təhsili almışdır. Roma, İtaliya | 2013-2015 ci illərdə Policlinico Umberto Primo xəstəxanasının Qulaq Burun Boğaz Klinikasının Duyğu üzvləri departament...', 7, 'Otorinolarinqoloq-audioloq. İş təcrübəsi: 2017-2018 ci illərdə LOR hospital otorinolarinqoloq-audioloq; 2023-cü il National Prime Hospital , otorinolarinqoloq; 2023 -cü ildən bu günədək Respublika Diaqnostika Mərkəzində otorinolarinqoloq-audioloq vəzifəsində çalışır..', '/doctor-photos/samire-allahverdiyeva.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Təzibə Mirzəliyeva', 'tezibe-mirzeliyeva', 'neonatology', 'Qraz-Avstriya Tibb Universiteti - Yenidoğulmuşların Ürək-Ağciyər Reanimasiyası 2009', 8, 'Pediatr - neonatoloq. İş təcrübəsi: Səudiyyə Ərəbistanında Neonatologiya, Reanimasiya üzrə Birinci Səudiyyə Milli Simpoziumu, Riyad Tibb Kompleksi, Uşaq Xəstəxanası.; Uşaq Sağlamlığında Yenilik, Ər-Riyad - Səudiyyə Ərəbistanı Krallığı, Kral Faysal Mütəxəssis Xəstəxanası, Pediatriya Şöbəsi, Neonatologiya Bölməsi 2008.; Neonatologiyada Salzburg seminarı; Hal-hazırda Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/tezibe-mirzeliyeva.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Valeh Məmmədov', 'valeh-memmedov', 'cardiovascular-surgery', 'Azərbaycan Tibb Universiteti, Ümumi cərrahiyyə ixtisası | 2018 Gülhanə Hərbi Tibb Akademiyasının Tibb fakültəsində doktorantura təhsili', 23, 'Ürək-damar cərrahı. İş təcrübəsi: 2001 - 2018 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib; 2018-ci ildən bu günədək Respublika Diaqnostika Mərkəzində ürək-damar cərrahı kimi fəaliyyət göstərir.', '/doctor-photos/valeh-memmedov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Vüqar Əliyev', 'vuqar-eliyev', 'neurosurgery', '1978 - 1988 - V.V Mayakovski adına 20 saylı orta təhsil məktəbini gümüş medalla bitirib. | 1988-1994 - Azərbaycan Tibb Universiteti. N. Nərimanov, Müalicə-profilaktika fakültəsi II, ixtisas - "Tibb işi". Əyani təhsil. Fərqlənmə diplomu ilə | 2007-2011 - "Rusiya Ədliyyə Akademiyası" dövlət ali təhsil müəssisəsi, ixtisas - "Hüquqşünaslıq - mülki hüquq". Qiyabi təhsil | 2007-2011 - Dövlət ali peşə təhsili müəssisəsi "A.S. Puşkin adına Leninqrad Dövlət Universiteti", ixtisas | "Dövlət və bələdiyyə idarəçiliy...', 28, 'Neyrocərrah. Elmi dərəcə: Tibb elmləri doktoru. İş təcrübəsi: 1993 - 1996 Aparıcı özəl tibb mərkəzlərində fəaliyyət göstərib.; 2003-2015 Federal Dövlət Büdcə Müəssisəsi, Prof. A.L. Polenova adına Rusiya Neyrocərrahiyyə İnstitutu, Sankt-Peterburq, Rusiya - Serebral damar cərrahiyyəsi şöbəsinin neyrocərrahı; 2003-2015 Sankt-Peterburq Şəhər Büdcə Səhiyyə Təşkilatı "Mariinskaya Xəstəxanası", Sankt-Peterburq, Rusiya - Neyrocərrahiyyə şöbəsi, Neyrocərrah; 2005-2019 Federal Dövət Büdcə Təşkilatı, V. A. Almazova adlna Milli Tibbi Diaqnostika Mərkəzi., Prof. A.L. Polenova adına Rusiya Neyrocərrahiyyə İnstitutu, Sankt-Peterburq, Rusiya - Serebral qan dövran patologiyası elmi-tədqiqat laboratoriyasının baş elmi işçisi; 20015-2020 Sankt-Peterburq Şəhər Büdcə Səhiyyə Təşkilatı "Elizavetinskaya Xəstəxanası", Sankt-Peterburq, Rusiya - Neyrocərrah, 2 saylı Neyrocərrahiyyə şöbəsinin müdiri; 2019-2021 Federal Dövlət Büdcə Təşkilatı, V. A. Almazova adlna Milli Tibbi Diaqnostika Mərkəzi., Prof. A.L. Polenova adına Rusiya Neyrocərrahiyyə İnstitutu, Sankt-Peterburq, Rusiya - Serebral qan dövran patologiyası elmi-tədqiqat laboratoriyasının aparıcı elmi işçisi; 2021-2022 Sankt-Peterburq Şəhər Büdcə Səhiyyə Təşkilatı "Alexandrovskaya Xəstəxanası ", Sankt-Peterburq, Rusiya - Neyrocərrahiyyə şöbəsi, Neyrocərrah 2; Hal hazırda Respublika Diaqnostika Mərkəzində fəaliyyət göstərir; Sertifikatlar, dərəcələr; Rusiya Neyrocərrahlar Assosiasiyasının, prof. İ.S. Babçin adına Sankt-Peterburq Neyrocərrahlar Cəmiyyətinin,akademik F.A.Serbinenko adına Endovaskulyar Neyrocərrahlar Assosiasiyasının üzvü.; 2011-ci ildə Sankt-Peterburq Səhiyyə Komitəsinin Attestasiya Komissiyası "Neyrocərrahiyyə" ixtisası üzrə ən yüksək ixtisas kateqoriyasına layiq görülüb..', '/doctor-photos/vuqar-eliyev.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Vüqar Fiqarov', 'vuqar-fiqarov', 'urology', '2000-2006 Azərbaycan Dövlət Tibb Universiteti, Pediatriya fakültəsi | 2006-2007 Ə.Əliyev adına Azərbaycan Dövlət Həkimləri Təkmilləşdirmə İnstitutu (ADHTİ) , urologiya kafedrası, internatura | İştirak etdiyi treninq və seminarlar | 2004 Almaniya, Maynz Universitetin Klinikası, ümumi urologiya kursu | 2005 Bolqarıstan, Varna şəh., ümumi urologiya kursu | 2010 Almaniya Uroloqlar Assosiasiyasının konfransı | 2012 Türk Ürolojı Derneği kursu | Avropa Uroloqlar Assosiasiyasının üzvü (EAU). | Beynalxalq Uroloql...', 16, 'Uroloq-cərrah. İş təcrübəsi: 2008-2024 Akademik M.C.Cavadzadə adına Respublika Kliniki Urolojı Xəstəxana, həkim uroloq; 2015-2020 MediStyle Hospitalda həkim uroloq-androloq; 2020-2024 Caspian İnternational Hospital uroloq-androloq; İcra etdiyi əməliyyatlar:; Böyrək və sidik yolları daşlarının endoskopik lazer cərrahiyəsi; Laparoskopik cərrahiyə; Prostat vəzi adenomasının endoskopik cərrahiyəsi; Sidik kisəsi törəmələrinin endoskopik cərrahiyəsi; Böyrək və sidik-cinsiyyət sisteminin bəd və xoşxassəli törəmələrinin cərrahiyəsi; Böyrək-sidik yollarının anadangəlmə və qazanılmış qüsurlarının rekonstruktiv cərrahi əməliyyatları; Kişi sonsuzluğunun mikrocərrahi müalicəsi..', '/doctor-photos/vuqar-fiqarov.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW()),
    ('Xəyalə Həsənova', 'xeyale-hesenova', 'cardiology', '2009-2015 Azərbaycan Tibb Universiteti. | 2015-2019 Respublika Diaqnostika Mərkəzində Kardiologiya ixtisası üzrə rezidentura.', 8, 'Kardioloq. İş təcrübəsi: 2020-ci ildən bu günədək Respublika Diaqnostika Mərkəzində fəaliyyət göstərir..', '/doctor-photos/xeyale-hesenova.webp', 'az', 'UNCLAIMED', 'rdm.az', 0, 1, NOW(), NOW())
;

CREATE TEMPORARY TABLE rdm_placement (doctor_slug VARCHAR(255), clinic_slug VARCHAR(255));
INSERT INTO rdm_placement (doctor_slug, clinic_slug) VALUES
    ('agakisi-yehyayev', 'respublika-diaqnostika-merkezi'),
    ('akif-mir-seyid', 'respublika-diaqnostika-merkezi'),
    ('almaz-seferova', 'respublika-diaqnostika-merkezi'),
    ('altay-ceferov', 'respublika-diaqnostika-merkezi'),
    ('anar-emrah', 'respublika-diaqnostika-merkezi'),
    ('aneta-sefereliyeva', 'respublika-diaqnostika-merkezi'),
    ('araz-suleymanov', 'respublika-diaqnostika-merkezi'),
    ('aynur-babayeva', 'respublika-diaqnostika-merkezi'),
    ('cabir-eliyev', 'respublika-diaqnostika-merkezi'),
    ('ceyhun-ismayilov', 'respublika-diaqnostika-merkezi'),
    ('dilare-efendiyeva', 'respublika-diaqnostika-merkezi'),
    ('dina-zotova', 'respublika-diaqnostika-merkezi'),
    ('eldar-veliyev', 'respublika-diaqnostika-merkezi'),
    ('elxan-zergerov', 'respublika-diaqnostika-merkezi'),
    ('ferhad-qarayev', 'respublika-diaqnostika-merkezi'),
    ('fexri-quliyev', 'respublika-diaqnostika-merkezi'),
    ('gulnar-celilova', 'respublika-diaqnostika-merkezi'),
    ('gulxanim-ismayilova', 'respublika-diaqnostika-merkezi'),
    ('huseyn-babayev', 'respublika-diaqnostika-merkezi'),
    ('ibrahim-efendiyev', 'respublika-diaqnostika-merkezi'),
    ('ilkin-goyusov', 'respublika-diaqnostika-merkezi'),
    ('ilqar-ismayilov', 'respublika-diaqnostika-merkezi'),
    ('irade-musayeva', 'respublika-diaqnostika-merkezi'),
    ('kenan-ehmedov-rdm', 'respublika-diaqnostika-merkezi'),
    ('lale-ehmedova', 'respublika-diaqnostika-merkezi'),
    ('leyla-ismayilova', 'respublika-diaqnostika-merkezi'),
    ('leyla-matanova', 'respublika-diaqnostika-merkezi'),
    ('mehriban-efendiyeva', 'respublika-diaqnostika-merkezi'),
    ('metanet-abbasova', 'respublika-diaqnostika-merkezi'),
    ('natiq-mirzeyev', 'respublika-diaqnostika-merkezi'),
    ('nemet-melikov', 'respublika-diaqnostika-merkezi'),
    ('nigar-esgerova', 'respublika-diaqnostika-merkezi'),
    ('puste-xelilova', 'respublika-diaqnostika-merkezi'),
    ('rauf-semedov', 'respublika-diaqnostika-merkezi'),
    ('rena-abasova', 'respublika-diaqnostika-merkezi'),
    ('rena-emirova', 'respublika-diaqnostika-merkezi'),
    ('rena-sireliyeva', 'respublika-diaqnostika-merkezi'),
    ('sahin-xelilov', 'respublika-diaqnostika-merkezi'),
    ('samire-allahverdiyeva', 'respublika-diaqnostika-merkezi'),
    ('tezibe-mirzeliyeva', 'respublika-diaqnostika-merkezi'),
    ('valeh-memmedov', 'respublika-diaqnostika-merkezi'),
    ('vuqar-eliyev', 'respublika-diaqnostika-merkezi'),
    ('vuqar-fiqarov', 'respublika-diaqnostika-merkezi'),
    ('xeyale-hesenova', 'respublika-diaqnostika-merkezi')
;

INSERT INTO doctor_clinic (doctor_id, clinic_id)
SELECT d.id, c.id
FROM rdm_placement p
JOIN doctor d ON d.slug = p.doctor_slug AND d.source = 'rdm.az'
JOIN clinic c ON c.slug = p.clinic_slug
WHERE NOT EXISTS (
    SELECT 1 FROM doctor_clinic dc
    WHERE dc.doctor_id = d.id AND dc.clinic_id = c.id);

DROP TEMPORARY TABLE rdm_placement;
