import type { DirectoryLanguage } from "@/components/doctors/copy";

/** Wording for the doctor's own screen. */
const strings = {
  az: {
    claimTitle: "Profilinizi tapın",
    claimNote: "Adınızı yazın. Profiliniz siyahıdadırsa, sahiblik tələb edin.",
    claimSearch: "Ad üzrə axtarın",
    claimFind: "Axtar",
    claimNone: "Bu ada uyğun profil tapılmadı",
    claimButton: "Bu mənəm",
    claimEvidence: "Kimliyinizi təsdiqləyən məlumat",
    claimEvidenceHint: "Diplom nömrəsi, iş yeri, əlaqə - yoxlayan şəxs üçün",
    claimSubmit: "Sahiblik tələbi göndər",
    claimSending: "Göndərilir...",
    claimDone: "Tələbiniz göndərildi. Yoxlanışdan sonra sizə yazacağıq.",
    claimFailed: "Tələbi göndərmək mümkün olmadı",
    profile: "Profil məlumatları",
    bio: "Haqqınızda",
    qualifications: "Təhsil və ixtisaslaşma",
    fee: "Qəbul haqqı (AZN)",
    languages: "Danışdığınız dillər",
    save: "Yadda saxla",
    saving: "Saxlanılır...",
    saved: "Yadda saxlanıldı",
    saveFailed: "Yadda saxlamaq mümkün olmadı",
    timeOff: "Məzuniyyət və qeyri-iş günləri",
    timeOffNote: "Bu aralıqda heç bir randevu təklif edilmir.",
    timeOffNone: "Qeyd edilmiş qeyri-iş günü yoxdur",
    timeOffFrom: "Başlanğıc",
    timeOffTo: "Bitmə",
    timeOffReason: "Səbəb (istəyə bağlı)",
    timeOffAdd: "Əlavə et",
    timeOffRemove: "Sil",
    timeOffFailed: "Əlavə etmək mümkün olmadı",
    timeOffBadRange: "Bitmə vaxtı başlanğıcdan sonra olmalıdır",
    existingKept: "Artıq təsdiqlənmiş randevular avtomatik ləğv edilmir.",
    title: "Həkim paneli",
    loading: "Yüklənir...",
    signIn: "Davam etmək üçün daxil olun",
    signInLink: "Daxil ol",
    noListing: "Bu hesaba bağlı həkim profili yoxdur",
    noListingNote:
      "Siyahıda öz profilinizi tapıb sahiblik tələb edə bilərsiniz. Profil yoxlanışdan keçənədək randevu qəbul etmir.",
    findListing: "Həkimlər siyahısı",
    viewProfile: "Profilə bax",
    notBookable:
      "Profiliniz hələ randevu qəbul etmir. İş saatlarını indi doldura bilərsiniz; yoxlama bitdikdən sonra randevular açılacaq.",
    hours: "İş saatları",
    hoursNote:
      "Hər həftə təkrarlanır. Vaxtlar bu bloklardan avtomatik yaradılır.",
    noHours: "Hələ iş saatı əlavə etməmisiniz",
    day: "Gün",
    from: "Başlanğıc",
    to: "Bitmə",
    slotLength: "Qəbul müddəti",
    minutes: "dəq",
    add: "Əlavə et",
    adding: "Əlavə edilir...",
    remove: "Sil",
    removeConfirm: "Bu iş saatını silmək istəyirsiniz?",
    removeFailed: "Silmək mümkün olmadı",
    addFailed: "Əlavə etmək mümkün olmadı",
    badRange: "Bitmə vaxtı başlanğıcdan sonra olmalıdır",
    appointments: "Randevular",
    noAppointments: "Hələ randevu yoxdur",
    recordShared: "Sağlamlıq qeydləri paylaşılıb",
    confirm: "Təsdiqlə",
    decline: "İmtina et",
    declineConfirm: "Bu randevudan imtina etmək istəyirsiniz?",
    decideFailed: "Əməliyyat alınmadı",
    REQUESTED: "Gözləyir",
    CONFIRMED: "Təsdiqlənib",
    CANCELLED: "Ləğv edilib",
    COMPLETED: "Tamamlanıb",
    NO_SHOW: "Gəlmədi",
    UNCLAIMED: "Sahiblik tələb edilməyib",
    PENDING: "Yoxlanılır",
    VERIFIED: "Yoxlanılıb",
    REJECTED: "Rədd edilib",
  },
  en: {
    claimTitle: "Find your profile",
    claimNote: "Search your name. If your profile is listed, claim it.",
    claimSearch: "Search by name",
    claimFind: "Search",
    claimNone: "No profile matches that name",
    claimButton: "This is me",
    claimEvidence: "Something that shows this is you",
    claimEvidenceHint: "Licence number, place of work, a contact - for whoever reviews it",
    claimSubmit: "Send claim",
    claimSending: "Sending...",
    claimDone: "Your claim was sent. We will write once it has been reviewed.",
    claimFailed: "Could not send the claim",
    profile: "Profile details",
    bio: "About you",
    qualifications: "Training and specialisation",
    fee: "Consultation fee (AZN)",
    languages: "Languages you speak",
    save: "Save",
    saving: "Saving...",
    saved: "Saved",
    saveFailed: "Could not save",
    timeOff: "Time off",
    timeOffNote: "No appointments are offered during these periods.",
    timeOffNone: "No time off recorded",
    timeOffFrom: "From",
    timeOffTo: "To",
    timeOffReason: "Reason (optional)",
    timeOffAdd: "Add",
    timeOffRemove: "Remove",
    timeOffFailed: "Could not add it",
    timeOffBadRange: "The end must be after the start",
    existingKept: "Appointments already confirmed are not cancelled automatically.",
    title: "Doctor panel",
    loading: "Loading...",
    signIn: "Sign in to continue",
    signInLink: "Sign in",
    noListing: "This account has no doctor profile",
    noListingNote:
      "Find your entry in the directory and claim it. A claimed listing takes no appointments until it has been checked.",
    findListing: "Browse doctors",
    viewProfile: "View profile",
    notBookable:
      "Your listing does not take appointments yet. You can set your hours now; they open once the check is done.",
    hours: "Working hours",
    hoursNote: "Repeats weekly. Times are generated from these blocks.",
    noHours: "You have not added any hours yet",
    day: "Day",
    from: "From",
    to: "To",
    slotLength: "Appointment length",
    minutes: "min",
    add: "Add",
    adding: "Adding...",
    remove: "Remove",
    removeConfirm: "Remove this block of hours?",
    removeFailed: "Could not remove it",
    addFailed: "Could not add it",
    badRange: "The end time must be after the start",
    appointments: "Appointments",
    noAppointments: "No appointments yet",
    recordShared: "Health record shared",
    confirm: "Confirm",
    decline: "Decline",
    declineConfirm: "Decline this appointment?",
    decideFailed: "That did not work",
    REQUESTED: "Requested",
    CONFIRMED: "Confirmed",
    CANCELLED: "Cancelled",
    COMPLETED: "Completed",
    NO_SHOW: "Did not attend",
    UNCLAIMED: "Unclaimed",
    PENDING: "Under review",
    VERIFIED: "Verified",
    REJECTED: "Rejected",
  },
  ru: {
    claimTitle: "Найдите свой профиль",
    claimNote: "Введите своё имя. Если профиль есть в справочнике, заявите на него права.",
    claimSearch: "Поиск по имени",
    claimFind: "Найти",
    claimNone: "Профиль с таким именем не найден",
    claimButton: "Это я",
    claimEvidence: "Подтверждение, что это вы",
    claimEvidenceHint: "Номер диплома, место работы, контакт - для проверяющего",
    claimSubmit: "Отправить заявку",
    claimSending: "Отправка...",
    claimDone: "Заявка отправлена. Мы напишем после проверки.",
    claimFailed: "Не удалось отправить заявку",
    profile: "Данные профиля",
    bio: "О себе",
    qualifications: "Образование и специализация",
    fee: "Стоимость приёма (AZN)",
    languages: "Языки, на которых вы говорите",
    save: "Сохранить",
    saving: "Сохранение...",
    saved: "Сохранено",
    saveFailed: "Не удалось сохранить",
    timeOff: "Отсутствие",
    timeOffNote: "В эти периоды приём не предлагается.",
    timeOffNone: "Периодов отсутствия нет",
    timeOffFrom: "С",
    timeOffTo: "До",
    timeOffReason: "Причина (необязательно)",
    timeOffAdd: "Добавить",
    timeOffRemove: "Удалить",
    timeOffFailed: "Не удалось добавить",
    timeOffBadRange: "Окончание должно быть позже начала",
    existingKept: "Уже подтверждённые записи автоматически не отменяются.",
    title: "Панель врача",
    loading: "Загрузка...",
    signIn: "Войдите, чтобы продолжить",
    signInLink: "Войти",
    noListing: "К этому аккаунту не привязан профиль врача",
    noListingNote:
      "Найдите свою запись в справочнике и заявите на неё права. Запись не принимает приёмы, пока не пройдена проверка.",
    findListing: "Смотреть врачей",
    viewProfile: "Открыть профиль",
    notBookable:
      "Ваш профиль пока не принимает записи. Часы приёма можно заполнить сейчас, они откроются после проверки.",
    hours: "Часы приёма",
    hoursNote: "Повторяются еженедельно. Время формируется из этих блоков.",
    noHours: "Вы ещё не добавили часы приёма",
    day: "День",
    from: "С",
    to: "До",
    slotLength: "Длительность приёма",
    minutes: "мин",
    add: "Добавить",
    adding: "Добавление...",
    remove: "Удалить",
    removeConfirm: "Удалить этот блок часов?",
    removeFailed: "Не удалось удалить",
    addFailed: "Не удалось добавить",
    badRange: "Время окончания должно быть позже начала",
    appointments: "Записи",
    noAppointments: "Записей пока нет",
    recordShared: "Медицинская карта открыта",
    confirm: "Подтвердить",
    decline: "Отклонить",
    declineConfirm: "Отклонить эту запись?",
    decideFailed: "Не получилось",
    REQUESTED: "Ожидает",
    CONFIRMED: "Подтверждена",
    CANCELLED: "Отменена",
    COMPLETED: "Завершена",
    NO_SHOW: "Не пришёл",
    UNCLAIMED: "Не заявлена",
    PENDING: "На проверке",
    VERIFIED: "Проверена",
    REJECTED: "Отклонена",
  },
};

export type PortalCopy = typeof strings.az;

export const portalCopy = (language: DirectoryLanguage): PortalCopy =>
  strings[language] ?? strings.az;
