import type { DirectoryLanguage } from "@/components/doctors/copy";

/** Wording for the doctor's own screen. */
const strings = {
  az: {
    title: "Həkim paneli",
    loading: "Yüklənir...",
    signIn: "Davam etmək üçün daxil olun",
    signInLink: "Daxil ol",
    noListing: "Bu hesaba bağlı həkim profili yoxdur",
    noListingNote:
      "Siyahıda öz profilinizi tapıb sahiblik tələb edə bilərsiniz. Profil yoxlanışdan keçənədək randevu qəbul etmir.",
    findListing: "Həkimlər siyahısı",
    viewProfile: "Profilə bax",
    notBookable:
      "Profiliniz hələ randevu qəbul etmir. İş saatlarını indi doldura bilərsiniz; yoxlama bitdikdən sonra randevular açılacaq.",
    hours: "İş saatları",
    hoursNote:
      "Hər həftə təkrarlanır. Vaxtlar bu bloklardan avtomatik yaradılır.",
    noHours: "Hələ iş saatı əlavə etməmisiniz",
    day: "Gün",
    from: "Başlanğıc",
    to: "Bitmə",
    slotLength: "Qəbul müddəti",
    minutes: "dəq",
    add: "Əlavə et",
    adding: "Əlavə edilir...",
    remove: "Sil",
    removeConfirm: "Bu iş saatını silmək istəyirsiniz?",
    removeFailed: "Silmək mümkün olmadı",
    addFailed: "Əlavə etmək mümkün olmadı",
    badRange: "Bitmə vaxtı başlanğıcdan sonra olmalıdır",
    appointments: "Randevular",
    noAppointments: "Hələ randevu yoxdur",
    recordShared: "Sağlamlıq qeydləri paylaşılıb",
    confirm: "Təsdiqlə",
    decline: "İmtina et",
    declineConfirm: "Bu randevudan imtina etmək istəyirsiniz?",
    decideFailed: "Əməliyyat alınmadı",
    REQUESTED: "Gözləyir",
    CONFIRMED: "Təsdiqlənib",
    CANCELLED: "Ləğv edilib",
    COMPLETED: "Tamamlanıb",
    NO_SHOW: "Gəlmədi",
    UNCLAIMED: "Sahiblik tələb edilməyib",
    PENDING: "Yoxlanılır",
    VERIFIED: "Yoxlanılıb",
    REJECTED: "Rədd edilib",
  },
  en: {
    title: "Doctor panel",
    loading: "Loading...",
    signIn: "Sign in to continue",
    signInLink: "Sign in",
    noListing: "This account has no doctor profile",
    noListingNote:
      "Find your entry in the directory and claim it. A claimed listing takes no appointments until it has been checked.",
    findListing: "Browse doctors",
    viewProfile: "View profile",
    notBookable:
      "Your listing does not take appointments yet. You can set your hours now; they open once the check is done.",
    hours: "Working hours",
    hoursNote: "Repeats weekly. Times are generated from these blocks.",
    noHours: "You have not added any hours yet",
    day: "Day",
    from: "From",
    to: "To",
    slotLength: "Appointment length",
    minutes: "min",
    add: "Add",
    adding: "Adding...",
    remove: "Remove",
    removeConfirm: "Remove this block of hours?",
    removeFailed: "Could not remove it",
    addFailed: "Could not add it",
    badRange: "The end time must be after the start",
    appointments: "Appointments",
    noAppointments: "No appointments yet",
    recordShared: "Health record shared",
    confirm: "Confirm",
    decline: "Decline",
    declineConfirm: "Decline this appointment?",
    decideFailed: "That did not work",
    REQUESTED: "Requested",
    CONFIRMED: "Confirmed",
    CANCELLED: "Cancelled",
    COMPLETED: "Completed",
    NO_SHOW: "Did not attend",
    UNCLAIMED: "Unclaimed",
    PENDING: "Under review",
    VERIFIED: "Verified",
    REJECTED: "Rejected",
  },
  ru: {
    title: "Панель врача",
    loading: "Загрузка...",
    signIn: "Войдите, чтобы продолжить",
    signInLink: "Войти",
    noListing: "К этому аккаунту не привязан профиль врача",
    noListingNote:
      "Найдите свою запись в справочнике и заявите на неё права. Запись не принимает приёмы, пока не пройдена проверка.",
    findListing: "Смотреть врачей",
    viewProfile: "Открыть профиль",
    notBookable:
      "Ваш профиль пока не принимает записи. Часы приёма можно заполнить сейчас, они откроются после проверки.",
    hours: "Часы приёма",
    hoursNote: "Повторяются еженедельно. Время формируется из этих блоков.",
    noHours: "Вы ещё не добавили часы приёма",
    day: "День",
    from: "С",
    to: "До",
    slotLength: "Длительность приёма",
    minutes: "мин",
    add: "Добавить",
    adding: "Добавление...",
    remove: "Удалить",
    removeConfirm: "Удалить этот блок часов?",
    removeFailed: "Не удалось удалить",
    addFailed: "Не удалось добавить",
    badRange: "Время окончания должно быть позже начала",
    appointments: "Записи",
    noAppointments: "Записей пока нет",
    recordShared: "Медицинская карта открыта",
    confirm: "Подтвердить",
    decline: "Отклонить",
    declineConfirm: "Отклонить эту запись?",
    decideFailed: "Не получилось",
    REQUESTED: "Ожидает",
    CONFIRMED: "Подтверждена",
    CANCELLED: "Отменена",
    COMPLETED: "Завершена",
    NO_SHOW: "Не пришёл",
    UNCLAIMED: "Не заявлена",
    PENDING: "На проверке",
    VERIFIED: "Проверена",
    REJECTED: "Отклонена",
  },
};

export type PortalCopy = typeof strings.az;

export const portalCopy = (language: DirectoryLanguage): PortalCopy =>
  strings[language] ?? strings.az;
