spring:
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  mvc:
    throw-exception-if-no-handler-found: true  # Needed to catch 404s manually
  devtools:
    restart:
      enabled: true
      quiet-period: 2000
      poll-interval: 3000
    livereload:
      enabled: true
  profiles:
    active: local  # change to 'prod' when deploying to production
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: https://virtualhekim.az/api/login/oauth2/code/google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope: public_profile,email
            redirect-uri: https://virtualhekim.az/api/login/oauth2/code/facebook

  datasource:
    url: ${DATABASE_URL}?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          useUnicode: true
          charSet: UTF-8
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
      internal-proxies: .*
  use-forward-headers: true
  error:
    path: /custom-error   # Default is /error
    whitelabel:
      enabled: true # If true, uses default Spring Boot error page

app:
  chatgpt:
    use-dummy-data: false
    base-url: ${BASE_URL:http://localhost:8080}
    openai:
      key: ${OPENAI_API_KEY}
      # model: gpt-3.5-turbo
      model: gpt-4o-mini
      url: https://api.openai.com/v1/chat/completions
      responses:
        enabled: ${OPENAI_RESPONSES_ENABLED:true}
        url: https://api.openai.com/v1/responses
        fallback-to-chat: ${OPENAI_RESPONSES_FALLBACK:false}
        default-model: gpt-4o-mini
        conversation-ttl-days: 30
        tools:
          file-search: true
          web-search: false
          code-interpreter: true
        cost:
          alert-threshold: 10.00
          daily-limit: 50.00
        retry:
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2.0

logging:
  level:
    org.springframework.security: DEBUG


upload:
  base-dir: ${UPLOAD_BASE_DIR:../public_html}
  public-url: ${PUBLIC_URL:http://localhost:8080}
  max-batch-size: 10
  allowed-medical-formats:
    images: jpg,jpeg,png,webp,dicom
    documents: pdf,doc,docx,txt,csv
    max-file-size-mb:
      images: 50
      documents: 10

resilience4j:
  circuitbreaker:
    instances:
      openai-responses:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 60s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      openai-responses:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  ratelimiter:
    instances:
      openai-responses:
        limitForPeriod: 100
        limitRefreshPeriod: 1m
        timeoutDuration: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
