spring:
  profiles:
    active: local  # change to 'local' when running locally
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope: public_profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}

app:
  chatgpt:
    use-dummy-data: false
    openai:
      key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo
      url: https://api.openai.com/v1/chat/completions

