spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drcopad
    username: your_cpanel_mysql_user
    password: your_cpanel_mysql_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

openapi:
  api:
    key: <OPENAI_KEY>
    model: gpt-3.5-turbo
    url: https://api.openai.com/v1/chat/completions

openai:
  api-key: <OPENAI_KEY>
